repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Version mise à jour
    hooks:
      #- id: trailing-whitespace
      - id: end-of-file-fixer
      #- id: check-yaml
      #- id: check-added-large-files

  # NOUVEAU : Outil pour nettoyer les imports et variables inutilisés
  #- repo: https://github.com/PyCQA/autoflake
    #rev: v2.3.1
    #hooks:
      #- id: autoflake
        #args:
          #- --in-place
          #- --remove-all-unused-imports
          #- --remove-unused-variables

  # NOUVEAU : Outil pour moderniser la syntaxe Python
  #- repo: https://github.com/asottile/pyupgrade
    #rev: v3.20.0
    #hooks:
      #- id: pyupgrade
        #args: [--py310-plus] # Spécifie votre version de Python

  #- repo: https://github.com/psf/black
    #rev: 25.1.0 # Version mise à jour
    #hooks:
      #- id: black

  #- repo: https://github.com/PyCQA/isort
    #rev: 6.0.1 # Version mise à jour, depuis le repo officiel
    #hooks:
      #- id: isort

  #- repo: https://github.com/pycqa/flake8
    #rev: 7.3.0 # Version mise à jour
    #hooks:
      #- id: flake8
        # args: [--extend-ignore=E501] # Vous pouvez garder vos arguments ici

  #- repo: https://github.com/Yelp/detect-secrets
    #rev: v1.5.0 # Version mise à jour
    #hooks:
      #- id: detect-secrets
