from django.urls import include, path
from rest_framework_simplejwt.views import TokenRefreshView

from main.api.views_acheteur import *
from main.api.views_authentication import *
from main.api.views_bilans_bancaires import *
from main.api.views_bilans_irfs_cobac import *
from main.api.views_commande import *
from main.api.views_localisation import *
from main.api.views_modele import *
from main.api.views_modules_acheteur import *
from main.api.views_monitoring import *
from main.api.views_standard import *
from main.api.views_users import *
from main.api.views_warning import *
from main.views import *

# from .views import PaysViewSet


# router = DefaultRouter()
# router.register(r'pays', PaysViewSet, basename='pays')

urlpatterns = [

    ########################################################################################################################
    #                                                                                                                      #
    #  API ROUTES START FOR ANALYSTE                                                                                       #
    #                                                                                                                      #
    ########################################################################################################################

    path("analyste-dashboard/", dash_analyste, name="dash_analyste"),
    path(
        "analyste-dashboard/localisation/liste-des-pays",
        dash_analyste_pays,
        name="dash_analyste_pays",
    ),
    path(
        "analyste-dashboard/localisation/liste-des-provinces",
        dash_analyste_province,
        name="dash_analyste_province",
    ),
    path(
        "analyste-dashboard/localisation/liste-des-villes",
        dash_analyste_ville,
        name="dash_analyste_ville",
    ),
    path(
        "analyste-dashboard/utilisateurs/liste-des-utilisateurs",
        dash_analyste_user,
        name="dash_analyste_user",
    ),
    path(
        "analyste-dashboard/standard/liste-des-devises",
        dash_analyste_devise,
        name="dash_analyste_devise",
    ),
    path(
        "analyste-dashboard/standard/liste-des-annees-civiles",
        dash_analyste_annee,
        name="dash_analyste_annee",
    ),
    path(
        "analyste-dashboard/standard/liste-des-colorations",
        dash_analyste_coloration,
        name="dash_analyste_coloration",
    ),
    path(
        "analyste-dashboard/standard/liste-des-categories-nace",
        dash_analyste_category_nace,
        name="dash_analyste_category_nace",
    ),
    path(
        "analyste-dashboard/standard/liste-des-categories-naf",
        dash_analyste_category_naf,
        name="dash_analyste_category_naf",
    ),
    path(
        "analyste-dashboard/standard/liste-des-codes-nace",
        dash_analyste_code_nace,
        name="dash_analyste_code_nace",
    ),
    path(
        "analyste-dashboard/standard/liste-des-codes-naf",
        dash_analyste_code_naf,
        name="dash_analyste_code_naf",
    ),
    path(
        "analyste-dashboard/standard/liste-des-formes-juridiques",
        dash_analyste_forme_juridique,
        name="dash_analyste_forme_juridique",
    ),
    path(
        "analyste-dashboard/standard/liste-des-domaines",
        dash_analyste_domaine,
        name="dash_analyste_domaine",
    ),
    path(
        "analyste-dashboard/standard/liste-des-postes",
        dash_analyste_poste,
        name="dash_analyste_poste",
    ),
    path(
        "analyste-dashboard/standard/liste-des-categories-entreprise",
        dash_analyste_category_entreprise,
        name="dash_analyste_category_entreprise",
    ),
    path(
        "analyste-dashboard/standard/liste-des-structures-entreprise",
        dash_analyste_structure_entreprise,
        name="dash_analyste_structure_entreprise",
    ),
    path(
        "analyste-dashboard/standard/liste-des-status-entreprise",
        dash_analyste_statut_entreprise,
        name="dash_analyste_statut_entreprise",
    ),
    path(
        "analyste-dashboard/nomenclature/liste-des-modeles-de-bail",
        dash_analyste_modele_bail,
        name="dash_analyste_modele_bail",
    ),
    path(
        "analyste-dashboard/nomenclature/liste-des-modeles-de-bilan",
        dash_analyste_modele_bilan,
        name="dash_analyste_modele_bilan",
    ),
    path(
        "analyste-dashboard/nomenclature/liste-des-modeles-alarme",
        dash_analyste_modele_alarme,
        name="dash_analyste_modele_alarme",
    ),
    path(
        "analyste-dashboard/nomenclature/liste-des-modeles-de-rapport",
        dash_analyste_modele_rapport,
        name="dash_analyste_modele_rapport",
    ),
    path(
        "analyste-dashboard/nomenclature/liste-des-modeles-avis-commercial",
        dash_analyste_modele_avis_commercial,
        name="dash_analyste_modele_avis_commercial",
    ),
    path(
        "analyste-dashboard/nomenclature/liste-des-modeles-de-relation-entreprise",
        dash_analyste_modele_relation_entreprise,
        name="dash_analyste_modele_relation_entreprise",
    ),
    path(
        "analyste-dashboard/nomenclature/liste-des-modeles-de-notation",
        dash_analyste_modele_notation,
        name="dash_analyste_modele_notation",
    ),
    path(
        "analyste-dashboard/nomenclature/liste-des-modeles-de-comportement-paiement",
        dash_analyste_modele_comportement_paiement,
        name="dash_analyste_modele_comportement_paiement",
    ),
    path(
        "analyste-dashboard/nomenclature/liste-des-modeles-de-comportement-jugement",
        dash_analyste_modele_comportement_jugement,
        name="dash_analyste_modele_comportement_jugement",
    ),
    path(
        "analyste-dashboard/nomenclature/liste-des-modeles-information-notation-entreprise",
        dash_analyste_modele_information_notation_entreprise,
        name="dash_analyste_modele_information_notation_entreprise",
    ),
    path(
        "analyste-dashboard/acheteurs/liste-des-acheteurs",
        dash_analyste_acheteur,
        name="dash_analyste_acheteur",
    ),
    path(
        "analyste-dashboard/acheteurs/ajouter-un-acheteur",
        dash_analyste_add_acheteur,
        name="dash_analyste_add_acheteur",
    ),
    path(
        "analyste-dashboard/acheteurs/editer-un-acheteur/<int:acheteur_id>/",
        dash_analyste_edit_acheteur,
        name="dash_analyste_edit_acheteur",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/",
        dash_analyste_manage_acheteur,
        name="dash_analyste_manage_acheteur",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/resumes/",
        dash_analyste_manage_acheteur_resume,
        name="dash_analyste_manage_acheteur_resume",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/evaluation-risques/",
        dash_analyste_manage_acheteur_risk_rating,
        name="dash_analyste_manage_acheteur_risk_rating",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/donnees-enregistrees/",
        dash_analyste_manage_acheteur_data_save,
        name="dash_analyste_manage_acheteur_data_save",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/tendances/",
        dash_analyste_manage_acheteur_tendance,
        name="dash_analyste_manage_acheteur_tendance",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/responsables/",
        dash_analyste_manage_acheteur_responsable,
        name="dash_analyste_manage_acheteur_responsable",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/antecedents-juridiques/",
        dash_analyste_manage_acheteur_antecedent,
        name="dash_analyste_manage_acheteur_antecedent",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/gestion-des-risques/",
        dash_analyste_manage_acheteur_gestion_risque,
        name="dash_analyste_manage_acheteur_gestion_risque",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/membres-du-conseil/",
        dash_analyste_manage_acheteur_membre_conseil,
        name="dash_analyste_manage_acheteur_membre_conseil",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/compositions-du-capital-social/",
        dash_analyste_manage_acheteur_composition_capital,
        name="dash_analyste_manage_acheteur_composition_capital",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/actionnaires/",
        dash_analyste_manage_acheteur_actionnaire,
        name="dash_analyste_manage_acheteur_actionnaire",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/opinions-acremac/",
        dash_analyste_manage_acheteur_opinion_acremac,
        name="dash_analyste_manage_acheteur_opinion_acremac",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/filiales/",
        dash_analyste_manage_acheteur_filiale,
        name="dash_analyste_manage_acheteur_filiale",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/analyses-sectorielles/",
        dash_analyste_manage_acheteur_analyse_sectorielle,
        name="dash_analyste_manage_acheteur_analyse_sectorielle",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/comptes-financiers/",
        dash_analyste_manage_acheteur_compte_financier,
        name="dash_analyste_manage_acheteur_compte_financier",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/operations-et-historiques/",
        dash_analyste_manage_acheteur_operation_historique,
        name="dash_analyste_manage_acheteur_operation_historique",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/proprietes-et-actifs/",
        dash_analyste_manage_acheteur_propriete_actif,
        name="dash_analyste_manage_acheteur_propriete_actif",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/conditions-achat/",
        dash_analyste_manage_acheteur_condition_achat,
        name="dash_analyste_manage_acheteur_condition_achat",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/conditions-vente/",
        dash_analyste_manage_acheteur_condition_vente,
        name="dash_analyste_manage_acheteur_condition_vente",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/sommaires-et-avis/",
        dash_analyste_manage_acheteur_sommaire_avis,
        name="dash_analyste_manage_acheteur_sommaire_avis",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/conseils/",
        dash_analyste_manage_acheteur_advice,
        name="dash_analyste_manage_acheteur_advice",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/geopolitiques/",
        dash_analyste_manage_acheteur_geopolitic,
        name="dash_analyste_manage_acheteur_geopolitic",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/donnees-bancaires/",
        dash_analyste_manage_acheteur_banking,
        name="dash_analyste_manage_acheteur_banking",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/certifications/",
        dash_analyste_certification_acheteur,
        name="dash_analyste_certification_acheteur",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/innovations-et-developement/",
        dash_analyste_innovation_acheteur,
        name="dash_analyste_innovation_acheteur",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/strategies-et-planifications/",
        dash_analyste_strategie_acheteur,
        name="dash_analyste_strategie_acheteur",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/conformites-et-reglementations/",
        dash_analyste_conformite_acheteur,
        name="dash_analyste_conformite_acheteur",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-anglais/actifs/",
        dash_analyste_manage_acheteur_actif_anglais,
        name="dash_analyste_manage_acheteur_actif_anglais",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-anglais/passifs/",
        dash_analyste_manage_acheteur_passif_anglais,
        name="dash_analyste_manage_acheteur_passif_anglais",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-anglais/resultats/",
        dash_analyste_manage_acheteur_resultat_anglais,
        name="dash_analyste_manage_acheteur_resultat_anglais",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-classique/actifs/",
        dash_analyste_manage_acheteur_actif_classique,
        name="dash_analyste_manage_acheteur_actif_classique",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-classique/passifs/",
        dash_analyste_manage_acheteur_passif_classique,
        name="dash_analyste_manage_acheteur_passif_classique",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-classique/resultats/",
        dash_analyste_manage_acheteur_resultat_classique,
        name="dash_analyste_manage_acheteur_resultat_classique",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-syscohada/actifs/",
        dash_analyste_manage_acheteur_actif_syscohada,
        name="dash_analyste_manage_acheteur_actif_syscohada",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-syscohada/passifs/",
        dash_analyste_manage_acheteur_passif_syscohada,
        name="dash_analyste_manage_acheteur_passif_syscohada",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-syscohada/resultats/",
        dash_analyste_manage_acheteur_resultat_syscohada,
        name="dash_analyste_manage_acheteur_resultat_syscohada",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-bancaire/actifs/",
        dash_analyste_manage_acheteur_asset_bancaire,
        name="dash_analyste_manage_acheteur_asset_bancaire",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-bancaire/modules-bancaires/",
        dash_analyste_manage_acheteur_bilan_actif_bancaire,
        name="dash_analyste_manage_acheteur_bilan_actif_bancaire",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-irfs-cobac/modules-irfs-cobac/",
        dash_analyste_manage_acheteur_bilan_irfs_cobac,
        name="dash_analyste_manage_acheteur_bilan_irfs_cobac",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-bancaire/passifs/",
        dash_analyste_manage_acheteur_liabilitie_bancaire,
        name="dash_analyste_manage_acheteur_liabilitie_bancaire",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-bancaire/depenses/",
        dash_analyste_manage_acheteur_expense_bancaire,
        name="dash_analyste_manage_acheteur_expense_bancaire",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-bancaire/produits/",
        dash_analyste_manage_acheteur_product_bancaire,
        name="dash_analyste_manage_acheteur_product_bancaire",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-bancaire/donnees-hors-bilan/",
        dash_analyste_manage_acheteur_offbalancesheet_bancaire,
        name="dash_analyste_manage_acheteur_offbalancesheet_bancaire",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-irfs/comptes-financiers/",
        dash_analyste_manage_acheteur_compte_financier_irfs,
        name="dash_analyste_manage_acheteur_compte_financier_irfs",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-irfs/ratios-financiers/",
        dash_analyste_manage_acheteur_ratio_financier_irfs,
        name="dash_analyste_manage_acheteur_ratio_financier_irfs",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-irfs/liste-des-actifs/",
        dash_analyste_manage_acheteur_actif_irfs,
        name="dash_analyste_manage_acheteur_actif_irfs",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-irfs/ajouter-un-actif/",
        dash_analyste_manage_acheteur_add_actif_irfs,
        name="dash_analyste_manage_acheteur_add_actif_irfs",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-irfs/liste-des-passifs/",
        dash_analyste_manage_acheteur_passif_irfs,
        name="dash_analyste_manage_acheteur_passif_irfs",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/bilan-irfs/ajouter-un-passif/",
        dash_analyste_manage_acheteur_add_passif_irfs,
        name="dash_analyste_manage_acheteur_add_passif_irfs",
    ),
    path(
        "analyste-dashboard/acheteurs/manager-un-acheteur/<int:acheteur_id>/rapport-version-web/",
        dash_analyste_manage_acheteur_report_web,
        name="dash_analyste_manage_acheteur_report_web",
    ),
    path(
        "analyste-dashboard/commandes/liste-des-commandes",
        dash_analyste_commande,
        name="dash_analyste_commande",
    ),
    path(
        "analyste-dashboard/commandes/manager-une-commande/<int:commande_id>/",
        dash_analyste_manage_commande,
        name="dash_analyste_manage_commande",
    ),
    path(
        "analyste-dashboard/warnings/liste-des-alertes/",
        dash_analyste_alerte,
        name="dash_analyste_alerte",
    ),
    path(
        "analyste-dashboard/warnings/ajouter-une-alerte/etape-1/",
        dash_analyste_add_alerte,
        name="dash_analyste_add_alerte",
    ),
    path(
        "analyste-dashboard/warnings/ajouter-une-alerte/etape-1/<slug:reference>/",
        dash_analyste_edit_new_alerte,
        name="dash_analyste_edit_new_alerte",
    ),
    path(
        "analyste-dashboard/warnings/ajouter-une-alerte/etape-2/<slug:reference>/",
        dash_analyste_document_alerte,
        name="dash_analyste_document_alerte",
    ),
    path(
        "analyste-dashboard/warnings/ajouter-une-alerte/etape-3/<slug:reference>/",
        dash_analyste_client_alerte,
        name="dash_analyste_client_alerte",
    ),
    path(
        "analyste-dashboard/warnings/editer-une-alerte/<int:alerte_id>/",
        dash_analyste_edit_alerte,
        name="dash_analyste_edit_alerte",
    ),
    path(
        "analyste-dashboard/warnings/manager-une-alerte/<int:alerte_id>/",
        dash_analyste_manage_alerte,
        name="dash_analyste_manage_alerte",
    ),
    path(
        "analyste-dashboard/monitoring/liste-des-clients/",
        dash_analyste_client,
        name="dash_analyste_client",
    ),
    path(
        "analyste-dashboard/monitoring/liste-des-portefeuilles/",
        dash_analyste_portefeuille,
        name="dash_analyste_portefeuille",
    ),
    path(
        "analyste-dashboard/monitoring/ajouter-un-portefeuille/",
        dash_analyste_add_portefeuille,
        name="dash_analyste_add_portefeuille",
    ),
    path(
        "analyste-dashboard/monitoring/editer-une-portefeuille/<int:portefeuille_id>/",
        dash_analyste_edit_portefeuille,
        name="dash_analyste_edit_portefeuille",
    ),
    path(
        "analyste-dashboard/simulateurs/scoring-sans-bilan/",
        dash_analyste_simulateur_scoring_sb,
        name="dash_analyste_simulateur_scoring_sb",
    ),
    path(
        "analyste-dashboard/elements-de-surveillance/",
        dash_analyste_element_surveillance,
        name="dash_analyste_element_surveillance",
    ),
    path(
        "analyste-dashboard/monitoring/alertes-log/",
        dash_analyste_alerte_log,
        name="dash_analyste_alerte_log",
    ),




]
