# Generated by Django 5.0.9 on 2026-01-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="avatar",
            field=models.TextField(
                blank=True,
                default="media/avatars/avatar.png",
                help_text="Upload an image for your avatar.",
                max_length=100,
                null=True,
                verbose_name="avatar",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="media/avatars/avatar.png",
                help_text="Upload an image for your avatar.",
                null=True,
                upload_to="avatars/",
                verbose_name="avatar",
            ),
        ),
    ]
