# Generated by Django 5.0.9 on 2026-01-09 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_historicaluser_avatar_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalville",
            name="pays",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Pays auquel appartient la ville.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="main.pays",
                verbose_name="Pays",
            ),
        ),
        migrations.AddField(
            model_name="ville",
            name="pays",
            field=models.ForeignKey(
                blank=True,
                help_text="Pays auquel appartient la ville.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.pays",
                verbose_name="Pays",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="avatar",
            field=models.TextField(
                blank=True,
                default="avatars/avatar.png",
                help_text="Upload an image for your avatar.",
                max_length=100,
                null=True,
                verbose_name="avatar",
            ),
        ),
        migrations.AlterField(
            model_name="province",
            name="pays",
            field=models.ForeignKey(
                blank=True,
                help_text="Pays auquel appartient la province.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.pays",
                verbose_name="Pays",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/avatar.png",
                help_text="Upload an image for your avatar.",
                null=True,
                upload_to="avatars/",
                verbose_name="avatar",
            ),
        ),
        migrations.AlterField(
            model_name="ville",
            name="province",
            field=models.ForeignKey(
                blank=True,
                help_text="Province à laquelle appartient la ville.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.province",
                verbose_name="Province",
            ),
        ),
    ]
