# Generated by Django 5.1.4 on 2025-01-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="code_connexion",
            field=models.CharField(
                blank=True,
                help_text="A 6-digit code for two-factor authentication.",
                max_length=6,
                null=True,
                verbose_name="connexion code",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="code_secret",
            field=models.CharField(
                blank=True,
                help_text="A 6-digit code for forgot and reset password.",
                max_length=6,
                null=True,
                verbose_name="secret code",
            ),
        ),
    ]
