# Generated by Django 5.0.9 on 2026-01-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_historicalville_pays_ville_pays_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="province",
            unique_together={("nom", "pays")},
        ),
        migrations.AlterUniqueTogether(
            name="ville",
            unique_together={("nom", "province")},
        ),
    ]
