# Generated by Django 5.0.9 on 2026-01-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_province_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpays",
            name="code",
            field=models.CharField(
                help_text="Code unique du pays, par exemple 'FR' pour la France ou 'CM' pour le Cameroun.",
                max_length=10,
                verbose_name="Code du pays",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpays",
            name="nom",
            field=models.CharField(
                help_text="Nom complet du pays, par exemple 'France' ou 'Cameroun'.",
                max_length=50,
                verbose_name="Nom du pays",
            ),
        ),
        migrations.AlterField(
            model_name="historicalprovince",
            name="code",
            field=models.CharField(
                help_text="Code unique de la province, par exemple 'IDF' pour l'Île-de-France ou 'OUEST' pour l'Ouest.",
                max_length=10,
                verbose_name="Code de la province",
            ),
        ),
        migrations.AlterField(
            model_name="historicalprovince",
            name="nom",
            field=models.CharField(
                help_text="Nom complet de la province, par exemple 'Île-de-France' ou 'Ouest'.",
                max_length=50,
                verbose_name="Nom de la province",
            ),
        ),
        migrations.AlterField(
            model_name="historicalville",
            name="code",
            field=models.CharField(
                help_text="Code unique de la ville, par exemple 'PAR' pour Paris ou 'DOU' pour Douala.",
                max_length=10,
                verbose_name="Code de la ville",
            ),
        ),
        migrations.AlterField(
            model_name="historicalville",
            name="nom",
            field=models.CharField(
                help_text="Nom complet de la ville, par exemple 'Paris' ou 'Douala'.",
                max_length=50,
                verbose_name="Nom de la ville",
            ),
        ),
        migrations.AlterField(
            model_name="pays",
            name="code",
            field=models.CharField(
                help_text="Code unique du pays, par exemple 'FR' pour la France ou 'CM' pour le Cameroun.",
                max_length=10,
                verbose_name="Code du pays",
            ),
        ),
        migrations.AlterField(
            model_name="pays",
            name="nom",
            field=models.CharField(
                help_text="Nom complet du pays, par exemple 'France' ou 'Cameroun'.",
                max_length=50,
                verbose_name="Nom du pays",
            ),
        ),
        migrations.AlterField(
            model_name="province",
            name="code",
            field=models.CharField(
                help_text="Code unique de la province, par exemple 'IDF' pour l'Île-de-France ou 'OUEST' pour l'Ouest.",
                max_length=10,
                verbose_name="Code de la province",
            ),
        ),
        migrations.AlterField(
            model_name="province",
            name="nom",
            field=models.CharField(
                help_text="Nom complet de la province, par exemple 'Île-de-France' ou 'Ouest'.",
                max_length=50,
                verbose_name="Nom de la province",
            ),
        ),
        migrations.AlterField(
            model_name="ville",
            name="code",
            field=models.CharField(
                help_text="Code unique de la ville, par exemple 'PAR' pour Paris ou 'DOU' pour Douala.",
                max_length=10,
                verbose_name="Code de la ville",
            ),
        ),
        migrations.AlterField(
            model_name="ville",
            name="nom",
            field=models.CharField(
                help_text="Nom complet de la ville, par exemple 'Paris' ou 'Douala'.",
                max_length=50,
                verbose_name="Nom de la ville",
            ),
        ),
    ]
