# Generated by Django 5.1.4 on 2025-01-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_customuser_reset_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom complet du pays, par exemple 'France' ou 'Cameroun'.",
                        max_length=50,
                        unique=True,
                        verbose_name="Nom du pays",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code unique du pays, par exemple 'FR' pour la France ou 'CM' pour le Cameroun.",
                        max_length=10,
                        unique=True,
                        verbose_name="Code du pays",
                    ),
                ),
                (
                    "afficher_au_dashboard",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si ce pays doit apparaître dans les tableaux de bord.",
                        verbose_name="Afficher au dashboard",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure à laquelle ce pays a été ajouté.",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de la dernière mise à jour de ce pays.",
                        verbose_name="Date de dernière modification",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si le pays est actif ou désactivé.",
                        verbose_name="Actif",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pays",
                "verbose_name_plural": "Pays",
                "ordering": ["nom"],
            },
        ),
    ]
