# Generated by Django 5.0.9 on 2026-01-13 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_historicalpays_code_alter_historicalpays_nom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalresume",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="devise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="devise_capital_social",
                to="main.devise",
                verbose_name="Devise du capital social",
            ),
        ),
    ]
