# Generated by Django 5.0.9 on 2026-01-14 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_historicalresume_commentaire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donneesenregistrement",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="donneesenregistrement",
            name="date_registre",
            field=models.DateField(blank=True, null=True, verbose_name="Date registre"),
        ),
        migrations.AlterField(
            model_name="donneesenregistrement",
            name="forme_juridique",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Other - Unknown", "Other - Unknown"),
                    ("Private Individual", "Private Individual"),
                    ("ETS PUB. NAT. COMPTA PUB.", "ETS PUB. NAT. COMPTA PUB."),
                    ("ETS PUB. SANS COMPTA.PUB.", "ETS PUB. SANS COMPTA.PUB."),
                    ("SA", "SA"),
                    ("AUT. SA A C. ADMN.", "AUT. SA A C. ADMN."),
                    ("AUTRE SA A DIRECTOIRE", "AUTRE SA A DIRECTOIRE"),
                    ("SARL", "SARL"),
                    ("SC", "SC"),
                    ("SOCIETE CIVILE", "SOCIETE CIVILE"),
                    ("SOC CREEE DE FAIT", "SOC CREEE DE FAIT"),
                    ("SNC", "SNC"),
                ],
                default="Veuillez choisir la forme juridique",
                max_length=4000,
                null=True,
                verbose_name="Forme juridique",
            ),
        ),
        migrations.AlterField(
            model_name="donneesenregistrement",
            name="numero_fiscale",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Numéro fiscal"
            ),
        ),
        migrations.AlterField(
            model_name="donneesenregistrement",
            name="numero_registre_commerce",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Numéro registre commerce",
            ),
        ),
        migrations.AlterField(
            model_name="donneesenregistrement",
            name="statut_registre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("-------", "-------"),
                    ("Entreprise active", "Entreprise active"),
                    ("Entreprise inactive", "Entreprise inactive"),
                    ("Entreprise en fusion", "Entreprise en fusion"),
                    ("Entreprise fusionnée", "Entreprise fusionnée"),
                    ("L'entreprise n'existe pas", "L'entreprise n'existe pas"),
                    (
                        "L'entreprise n'a pas pu etre identifiée",
                        "L'entreprise n'a pas pu etre identifiée",
                    ),
                    ("Entreprise est en sommeil", "Entreprise est en sommeil"),
                    (
                        "Impossible de localiser l'entreprise",
                        "Impossible de localiser l'entreprise",
                    ),
                    ("L'activité a cessé", "L'activité a cessé"),
                    (
                        "L'entreprise n'est pas immatriculée",
                        "L'entreprise n'est pas immatriculée",
                    ),
                    (
                        "L'entreprise n'est pas immatriculée localement",
                        "L'entreprise n'est pas immatriculée localement",
                    ),
                    ("Activité commerciale limitée", "Activité commerciale limitée"),
                    (
                        "Aucune activité commerciale visible localement",
                        "Aucune activité commerciale visible localement",
                    ),
                    ("Dissolution volontaire", "Dissolution volontaire"),
                    (
                        "Dissolution volontaire du creancier",
                        "Dissolution volontaire du creancier",
                    ),
                    ("Dissolution forcée", "Dissolution forcée"),
                    ("Radiation", "Radiation"),
                    (
                        "Entreprise en cours de désimmatriculation",
                        "Entreprise en cours de désimmatriculation",
                    ),
                    ("Dissoute", "Dissoute"),
                    ("Va suivre", "Va suivre"),
                    ("Entreprise Introuvable", "Entreprise Introuvable"),
                ],
                default="--------",
                max_length=4000,
                null=True,
                verbose_name="Statut registre",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldonneesenregistrement",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldonneesenregistrement",
            name="date_registre",
            field=models.DateField(blank=True, null=True, verbose_name="Date registre"),
        ),
        migrations.AlterField(
            model_name="historicaldonneesenregistrement",
            name="forme_juridique",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Other - Unknown", "Other - Unknown"),
                    ("Private Individual", "Private Individual"),
                    ("ETS PUB. NAT. COMPTA PUB.", "ETS PUB. NAT. COMPTA PUB."),
                    ("ETS PUB. SANS COMPTA.PUB.", "ETS PUB. SANS COMPTA.PUB."),
                    ("SA", "SA"),
                    ("AUT. SA A C. ADMN.", "AUT. SA A C. ADMN."),
                    ("AUTRE SA A DIRECTOIRE", "AUTRE SA A DIRECTOIRE"),
                    ("SARL", "SARL"),
                    ("SC", "SC"),
                    ("SOCIETE CIVILE", "SOCIETE CIVILE"),
                    ("SOC CREEE DE FAIT", "SOC CREEE DE FAIT"),
                    ("SNC", "SNC"),
                ],
                default="Veuillez choisir la forme juridique",
                max_length=4000,
                null=True,
                verbose_name="Forme juridique",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldonneesenregistrement",
            name="numero_fiscale",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Numéro fiscal"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldonneesenregistrement",
            name="numero_registre_commerce",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Numéro registre commerce",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldonneesenregistrement",
            name="statut_registre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("-------", "-------"),
                    ("Entreprise active", "Entreprise active"),
                    ("Entreprise inactive", "Entreprise inactive"),
                    ("Entreprise en fusion", "Entreprise en fusion"),
                    ("Entreprise fusionnée", "Entreprise fusionnée"),
                    ("L'entreprise n'existe pas", "L'entreprise n'existe pas"),
                    (
                        "L'entreprise n'a pas pu etre identifiée",
                        "L'entreprise n'a pas pu etre identifiée",
                    ),
                    ("Entreprise est en sommeil", "Entreprise est en sommeil"),
                    (
                        "Impossible de localiser l'entreprise",
                        "Impossible de localiser l'entreprise",
                    ),
                    ("L'activité a cessé", "L'activité a cessé"),
                    (
                        "L'entreprise n'est pas immatriculée",
                        "L'entreprise n'est pas immatriculée",
                    ),
                    (
                        "L'entreprise n'est pas immatriculée localement",
                        "L'entreprise n'est pas immatriculée localement",
                    ),
                    ("Activité commerciale limitée", "Activité commerciale limitée"),
                    (
                        "Aucune activité commerciale visible localement",
                        "Aucune activité commerciale visible localement",
                    ),
                    ("Dissolution volontaire", "Dissolution volontaire"),
                    (
                        "Dissolution volontaire du creancier",
                        "Dissolution volontaire du creancier",
                    ),
                    ("Dissolution forcée", "Dissolution forcée"),
                    ("Radiation", "Radiation"),
                    (
                        "Entreprise en cours de désimmatriculation",
                        "Entreprise en cours de désimmatriculation",
                    ),
                    ("Dissoute", "Dissoute"),
                    ("Va suivre", "Va suivre"),
                    ("Entreprise Introuvable", "Entreprise Introuvable"),
                ],
                default="--------",
                max_length=4000,
                null=True,
                verbose_name="Statut registre",
            ),
        ),
        migrations.AlterField(
            model_name="historicalriskrating",
            name="analyse",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Analyse"
            ),
        ),
        migrations.AlterField(
            model_name="historicalriskrating",
            name="existence_garantie",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Existence garantie"
            ),
        ),
        migrations.AlterField(
            model_name="historicalriskrating",
            name="interpretation",
            field=models.TextField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Interprétation",
            ),
        ),
        migrations.AlterField(
            model_name="historicalriskrating",
            name="mesure_propre_soutenir_credit",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Mesure propre à soutenir le crédit",
            ),
        ),
        migrations.AlterField(
            model_name="historicalriskrating",
            name="performance_rentabilite",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Performance de rentabilité",
            ),
        ),
        migrations.AlterField(
            model_name="historicalriskrating",
            name="perspective_secteur",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Perspective secteur"
            ),
        ),
        migrations.AlterField(
            model_name="historicalriskrating",
            name="qualite_information_analyse",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Qualité information analyse",
            ),
        ),
        migrations.AlterField(
            model_name="historicalriskrating",
            name="remboursabilite",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Remboursabilité"
            ),
        ),
        migrations.AlterField(
            model_name="historicalriskrating",
            name="situation_liquidite",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Situation de liquidité",
            ),
        ),
        migrations.AlterField(
            model_name="historicalriskrating",
            name="terme_financier_duree_pret",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Terme financier durée prêt",
            ),
        ),
        migrations.AlterField(
            model_name="riskrating",
            name="acheteur",
            field=models.ForeignKey(
                blank=True,
                help_text="Acheteur concerné par l'évaluation du risque.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.acheteur",
                verbose_name="Acheteur",
            ),
        ),
        migrations.AlterField(
            model_name="riskrating",
            name="analyse",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Analyse"
            ),
        ),
        migrations.AlterField(
            model_name="riskrating",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="risk_rating_user_create",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="riskrating",
            name="existence_garantie",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Existence garantie"
            ),
        ),
        migrations.AlterField(
            model_name="riskrating",
            name="interpretation",
            field=models.TextField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Interprétation",
            ),
        ),
        migrations.AlterField(
            model_name="riskrating",
            name="mesure_propre_soutenir_credit",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Mesure propre à soutenir le crédit",
            ),
        ),
        migrations.AlterField(
            model_name="riskrating",
            name="performance_rentabilite",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Performance de rentabilité",
            ),
        ),
        migrations.AlterField(
            model_name="riskrating",
            name="perspective_secteur",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Perspective secteur"
            ),
        ),
        migrations.AlterField(
            model_name="riskrating",
            name="qualite_information_analyse",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Qualité information analyse",
            ),
        ),
        migrations.AlterField(
            model_name="riskrating",
            name="remboursabilite",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Remboursabilité"
            ),
        ),
        migrations.AlterField(
            model_name="riskrating",
            name="situation_liquidite",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Situation de liquidité",
            ),
        ),
        migrations.AlterField(
            model_name="riskrating",
            name="terme_financier_duree_pret",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Terme financier durée prêt",
            ),
        ),
        migrations.AlterField(
            model_name="riskrating",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="risk_rating_user_update",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mis à jour par",
            ),
        ),
    ]
