# Generated by Django 5.1.4 on 2025-01-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_pays"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("contenu", models.TextField()),
                ("date_publication", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
