# Generated by Django 5.0.9 on 2025-01-25 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom complet de la province, par exemple 'Île-de-France' ou 'Ouest'.", max_length=50, unique=True, verbose_name='Nom de la province')),
                ('code', models.CharField(help_text="Code unique de la province, par exemple 'IDF' pour l'Île-de-France ou 'OUEST' pour l'Ouest.", max_length=10, unique=True, verbose_name='Code de la province')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date et heure à laquelle cette province a été ajoutée.', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière mise à jour de cette province.', verbose_name='Date de dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si la province est active ou désactivée.', verbose_name='Actif')),
                ('pays', models.ForeignKey(help_text='Pays auquel appartient la province.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.pays', verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom complet de la ville, par exemple 'Paris' ou 'Douala'.", max_length=50, unique=True, verbose_name='Nom de la ville')),
                ('code', models.CharField(help_text="Code unique de la ville, par exemple 'PAR' pour Paris ou 'DOU' pour Douala.", max_length=10, unique=True, verbose_name='Code de la ville')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date et heure à laquelle cette ville a été ajoutée.', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière mise à jour de cette ville.', verbose_name='Date de dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si la ville est active ou désactivée.', verbose_name='Actif')),
                ('pays', models.ForeignKey(help_text='Pays auquel appartient la ville.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.pays', verbose_name='Pays')),
                ('province', models.ForeignKey(help_text='Province à laquelle appartient la ville.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.province', verbose_name='Province')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['nom'],
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
