# Generated by Django 5.0.9 on 2026-01-14 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_donneesenregistrement_commentaire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donneesenregistrement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="donnees_enregistrement_user_create",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="donneesenregistrement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="donnees_enregistrement_user_update",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltendance",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltendance",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltendance",
            name="presse_media",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Presse/Medias"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltendance",
            name="principaux_concurrent",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Principaux concurrents"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltendance",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Dernière mise à jour",
            ),
        ),
        migrations.AlterField(
            model_name="tendance",
            name="acheteur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.acheteur",
                verbose_name="Acheteur",
            ),
        ),
        migrations.AlterField(
            model_name="tendance",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="tendance",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="tendance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tendance_user_create",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="tendance",
            name="presse_media",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Presse/Medias"
            ),
        ),
        migrations.AlterField(
            model_name="tendance",
            name="principaux_concurrent",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Principaux concurrents"
            ),
        ),
        migrations.AlterField(
            model_name="tendance",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Dernière mise à jour"
            ),
        ),
        migrations.AlterField(
            model_name="tendance",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tendance_user_update",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mis à jour par",
            ),
        ),
    ]
