# Generated by Django 5.1.4 on 2025-01-27 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_annee_devise"),
    ]

    operations = [
        migrations.CreateModel(
            name="CouleurCommentaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "couleur",
                    models.CharField(
                        blank=True,
                        help_text="Code hexadécimal de la couleur, par exemple '#FF5733'.",
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#([0-9A-Fa-f]{3}){1,2}$",
                                "La couleur doit être au format hexadécimal (#RRGGBB ou #RGB).",
                            )
                        ],
                        verbose_name="Couleur",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Code de la couleur.",
                        max_length=255,
                        verbose_name="Code",
                    ),
                ),
            ],
        ),
    ]
