# Generated by Django 5.1.4 on 2025-01-27 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_couleurcommentaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couleurcommentaire',
            options={'ordering': ['code'], 'verbose_name': 'Coloration', 'verbose_name_plural': 'Colorations'},
        ),
        migrations.AlterField(
            model_name='couleurcommentaire',
            name='code',
            field=models.CharField(blank=True, help_text="Code hexadécimal de la couleur, par exemple '#FF5733'.", max_length=255, validators=[django.core.validators.RegexValidator('^#([0-9A-Fa-f]{3}){1,2}$', 'La couleur doit être au format hexadécimal (#RRGGBB ou #RGB).')], verbose_name='Code Couleur'),
        ),
        migrations.AlterField(
            model_name='couleurcommentaire',
            name='couleur',
            field=models.CharField(blank=True, help_text="Nom de la couleur, par exemple '#FF5733'.", max_length=255, verbose_name='Nom de la Couleur'),
        ),
    ]
