# Generated by Django 5.0.9 on 2026-01-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_historicalresponsableacheteur_poste_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalresponsableacheteur",
            old_name="sexe",
            new_name="Sexe",
        ),
        migrations.RenameField(
            model_name="responsableacheteur",
            old_name="sexe",
            new_name="Sexe",
        ),
    ]
