# Generated by Django 5.0.9 on 2026-01-14 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_rename_sexe_historicalresponsableacheteur_sexe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antecedantsjuridique",
            name="Autre",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Autre"
            ),
        ),
        migrations.AlterField(
            model_name="antecedantsjuridique",
            name="antecedant_redressement",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Antécédent de redressement",
            ),
        ),
        migrations.AlterField(
            model_name="antecedantsjuridique",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="antecedantsjuridique",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="antecedants_juridique_user_create",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="antecedantsjuridique",
            name="dossier_faillite",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Dossier faillite"
            ),
        ),
        migrations.AlterField(
            model_name="antecedantsjuridique",
            name="jugement_cour",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Jugement cour"
            ),
        ),
        migrations.AlterField(
            model_name="antecedantsjuridique",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Dernière mise à jour"
            ),
        ),
        migrations.AlterField(
            model_name="antecedantsjuridique",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="antecedants_juridique_user_update",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="historicalantecedantsjuridique",
            name="Autre",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Autre"
            ),
        ),
        migrations.AlterField(
            model_name="historicalantecedantsjuridique",
            name="antecedant_redressement",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Antécédent de redressement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalantecedantsjuridique",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="historicalantecedantsjuridique",
            name="dossier_faillite",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Dossier faillite"
            ),
        ),
        migrations.AlterField(
            model_name="historicalantecedantsjuridique",
            name="jugement_cour",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Jugement cour"
            ),
        ),
        migrations.AlterField(
            model_name="historicalantecedantsjuridique",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Dernière mise à jour",
            ),
        ),
    ]
