# Generated by Django 5.1.4 on 2025-01-30 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_categorynacecode_categorynafcode_domaineentreprise_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieEntreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Code"
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Libellé"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("active", models.IntegerField(default=0, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de Création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de Mise à Jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie d'Entreprise",
                "verbose_name_plural": "Catégories d'Entreprises",
            },
        ),
        migrations.CreateModel(
            name="Acheteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Code unique de l'acheteur",
                        max_length=255,
                        null=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "activite_principale",
                    models.CharField(
                        blank=True,
                        help_text="Activité principale de l'entreprise",
                        max_length=255,
                        verbose_name="Activité Principale",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom officiel de l'entreprise",
                        max_length=1000,
                        unique=True,
                        verbose_name="Raison sociale",
                    ),
                ),
                (
                    "sigle",
                    models.CharField(
                        blank=True,
                        help_text="Sigle de l'entreprise",
                        max_length=255,
                        verbose_name="Sigle",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description de l'entreprise",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "capital_social",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Capital social de l'entreprise",
                        max_digits=15,
                        null=True,
                        verbose_name="Capital Social",
                    ),
                ),
                (
                    "date_creation",
                    models.DateField(
                        blank=True,
                        help_text="Date de création de l'entreprise",
                        null=True,
                        verbose_name="Date de Création",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        blank=True,
                        help_text="Statut actuel de l'entreprise",
                        max_length=255,
                        null=True,
                        verbose_name="Statut actuel de l'entreprise",
                    ),
                ),
                (
                    "code_postal",
                    models.CharField(
                        blank=True,
                        help_text="Code postal de l'entreprise",
                        max_length=200,
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de fax de l'entreprise",
                        max_length=300,
                    ),
                ),
                (
                    "boite_postale",
                    models.CharField(
                        blank=True,
                        help_text="Boîte postale de l'entreprise",
                        max_length=200,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Adresse email de l'entreprise",
                        max_length=254,
                    ),
                ),
                (
                    "site_internet",
                    models.URLField(
                        blank=True,
                        help_text="Site internet de l'entreprise",
                        max_length=300,
                    ),
                ),
                (
                    "numero_adresse",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de l'adresse de l'entreprise",
                        max_length=200,
                    ),
                ),
                (
                    "rue_adresse",
                    models.CharField(
                        blank=True,
                        help_text="Rue de l'adresse de l'entreprise",
                        max_length=200,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude de l'entreprise",
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude de l'entreprise",
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True, help_text="Commentaire sur l'entreprise"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date de création de l'enregistrement",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date de la dernière mise à jour de l'enregistrement",
                        verbose_name="Date de Mise à Jour",
                    ),
                ),
                (
                    "couleur_commentaire",
                    models.ForeignKey(
                        blank=True,
                        help_text="Couleur du commentaire",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main.couleurcommentaire",
                    ),
                ),
                (
                    "forme_juridique",
                    models.ForeignKey(
                        blank=True,
                        help_text="Forme juridique de l'entreprise",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.formejuridique",
                        verbose_name="Forme Juridique",
                    ),
                ),
                (
                    "pays",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Pays où l'entreprise est située",
                        to="main.pays",
                        verbose_name="Pays",
                    ),
                ),
                (
                    "province",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Province où l'entreprise est située",
                        to="main.province",
                        verbose_name="Province",
                    ),
                ),
                (
                    "ville",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Ville où l'entreprise est située",
                        to="main.ville",
                        verbose_name="Ville",
                    ),
                ),
                (
                    "categorie_entreprise",
                    models.ForeignKey(
                        blank=True,
                        help_text="Catégorie à laquelle appartient l'entreprise",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.categorieentreprise",
                        verbose_name="Catégorie d'Entreprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acheteur",
                "verbose_name_plural": "Acheteurs",
                "ordering": ["nom"],
                "unique_together": {("nom", "email")},
            },
        ),
    ]
