# Generated by Django 5.0.9 on 2026-01-19 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_antecedantsjuridique_autre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compositioncapitalsocial",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="compositioncapitalsocial",
            name="devise",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.devise",
                verbose_name="Dévise du capital libéré",
            ),
        ),
        migrations.AlterField(
            model_name="compositioncapitalsocial",
            name="emis",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                help_text="Montant du capital émis",
                max_digits=100,
                null=True,
                verbose_name="Capital émis",
            ),
        ),
        migrations.AlterField(
            model_name="compositioncapitalsocial",
            name="libere",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                help_text="Montant du capital libéré",
                max_digits=100,
                null=True,
                verbose_name="Capital libéré",
            ),
        ),
        migrations.AlterField(
            model_name="compositioncapitalsocial",
            name="publie",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                help_text="Montant du capital publié",
                max_digits=100,
                null=True,
                verbose_name="Capital publié",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompositioncapitalsocial",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompositioncapitalsocial",
            name="devise",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="main.devise",
                verbose_name="Dévise du capital libéré",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompositioncapitalsocial",
            name="emis",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                help_text="Montant du capital émis",
                max_digits=100,
                null=True,
                verbose_name="Capital émis",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompositioncapitalsocial",
            name="libere",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                help_text="Montant du capital libéré",
                max_digits=100,
                null=True,
                verbose_name="Capital libéré",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompositioncapitalsocial",
            name="publie",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                help_text="Montant du capital publié",
                max_digits=100,
                null=True,
                verbose_name="Capital publié",
            ),
        ),
    ]
