# Generated by Django 5.1.4 on 2025-01-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_categorieentreprise_acheteur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorieentreprise",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
    ]
