# Generated by Django 5.0.9 on 2026-01-19 09:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_compositioncapitalsocial_commentaire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compositionaction",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="compositionaction",
            name="nom",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="compositionaction",
            name="pourcentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                help_text="Pourcentage de détention (0-100) avec 2 décimales max",
                max_digits=100,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="Pourcentage",
            ),
        ),
        migrations.AlterField(
            model_name="compositionaction",
            name="prenom",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Prénom"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompositionaction",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompositionaction",
            name="nom",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompositionaction",
            name="pourcentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                help_text="Pourcentage de détention (0-100) avec 2 décimales max",
                max_digits=100,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="Pourcentage",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompositionaction",
            name="prenom",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Prénom"
            ),
        ),
    ]
