# Generated by Django 5.0.9 on 2026-01-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_compositionaction_commentaire_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalstructure",
            name="type_affiliation_ref",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="type_affiliation_ref",
        ),
        migrations.AlterField(
            model_name="historicalstructure",
            name="code_postale_adresse",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Code postal adresse",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstructure",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstructure",
            name="nom",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstructure",
            name="numero_adresse",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Numéro adresse"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstructure",
            name="rue_adresse",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Rue adresse"
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="code_postale_adresse",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Code postal adresse",
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="nom",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="numero_adresse",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Numéro adresse"
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="rue_adresse",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Rue adresse"
            ),
        ),
    ]
