# Generated by Django 5.0.9 on 2026-01-19 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_remove_historicalstructure_type_affiliation_ref_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banquier",
            name="code_postal",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Code postal"
            ),
        ),
        migrations.AlterField(
            model_name="banquier",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="banquier",
            name="nom_banque",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nom de la banque"
            ),
        ),
        migrations.AlterField(
            model_name="banquier",
            name="numero",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Numéro"
            ),
        ),
        migrations.AlterField(
            model_name="banquier",
            name="rue",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Rue"
            ),
        ),
        migrations.AlterField(
            model_name="banquier",
            name="ville",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.ville",
                verbose_name="Ville",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbanquier",
            name="code_postal",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Code postal"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbanquier",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbanquier",
            name="nom_banque",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nom de la banque"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbanquier",
            name="numero",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Numéro"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbanquier",
            name="rue",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Rue"
            ),
        ),
    ]
