# Generated by Django 5.0.9 on 2026-01-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_banquier_code_postal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysesectorielle",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="analysesectorielle",
            name="impact_covid_19",
            field=models.TextField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Impact COVID-19",
            ),
        ),
        migrations.AlterField(
            model_name="historicalanalysesectorielle",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="historicalanalysesectorielle",
            name="impact_covid_19",
            field=models.TextField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Impact COVID-19",
            ),
        ),
        migrations.AddIndex(
            model_name="banquier",
            index=models.Index(
                fields=["acheteur", "deleted"], name="main_banqui_acheteu_6e2a48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banquier",
            index=models.Index(
                fields=["nom_banque"], name="main_banqui_nom_ban_b1e54b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banquier",
            index=models.Index(fields=["ville"], name="main_banqui_ville_i_3601e3_idx"),
        ),
        migrations.AddIndex(
            model_name="banquier",
            index=models.Index(
                fields=["couleur_commentaire"], name="main_banqui_couleur_5c2774_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banquier",
            index=models.Index(
                fields=["created_at"], name="main_banqui_created_c7f2ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banquier",
            index=models.Index(
                fields=["updated_at"], name="main_banqui_updated_76d1cc_idx"
            ),
        ),
    ]
