# Generated by Django 5.1.4 on 2025-02-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_acheteur_statut_acheteur_statut_entreprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acheteur',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='acheteur',
            name='longitude',
        ),
    ]
