# Generated by Django 5.0.9 on 2026-01-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_analysesectorielle_commentaire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geopolitics",
            name="donnees_economiques",
            field=models.TextField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Données économiques",
            ),
        ),
        migrations.AlterField(
            model_name="geopolitics",
            name="donnees_politiques",
            field=models.TextField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Données politiques",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgeopolitics",
            name="donnees_economiques",
            field=models.TextField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Données économiques",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgeopolitics",
            name="donnees_politiques",
            field=models.TextField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Données politiques",
            ),
        ),
    ]
