# Generated by Django 5.1.4 on 2025-02-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_remove_acheteur_latitude_remove_acheteur_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ville",
            name="pays",
        ),
    ]
