# Generated by Django 5.1.4 on 2025-02-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_remove_ville_pays"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acheteur",
            name="capital_social",
        ),
    ]
