# Generated by Django 5.0.9 on 2026-01-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_geopolitics_donnees_economiques_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advice",
            name="dynamisme_court_terme",
            field=models.TextField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Dynamisme à court terme",
            ),
        ),
        migrations.AlterField(
            model_name="advice",
            name="points_faibles",
            field=models.TextField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Points faibles",
            ),
        ),
        migrations.AlterField(
            model_name="advice",
            name="points_forts",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Points forts"
            ),
        ),
        migrations.AlterField(
            model_name="advice",
            name="risque_potentiel_court_terme",
            field=models.TextField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Risques potentiels à court terme",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladvice",
            name="dynamisme_court_terme",
            field=models.TextField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Dynamisme à court terme",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladvice",
            name="points_faibles",
            field=models.TextField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Points faibles",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladvice",
            name="points_forts",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Points forts"
            ),
        ),
        migrations.AlterField(
            model_name="historicaladvice",
            name="risque_potentiel_court_terme",
            field=models.TextField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Risques potentiels à court terme",
            ),
        ),
    ]
