# Generated by Django 5.0.9 on 2026-01-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_advice_dynamisme_court_terme_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comptefinancier",
            name="cabinet",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Cabinet"
            ),
        ),
        migrations.AlterField(
            model_name="comptefinancier",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="comptefinancier",
            name="credibilite_cabinet",
            field=models.CharField(
                blank=True,
                choices=[("OUI", "Oui"), ("NON", "Non")],
                max_length=200,
                null=True,
                verbose_name="Crédibilité du cabinet pour ACREMAC",
            ),
        ),
        migrations.AlterField(
            model_name="comptefinancier",
            name="date_compte",
            field=models.DateField(
                blank=True, null=True, verbose_name="Début de période de compte N"
            ),
        ),
        migrations.AlterField(
            model_name="comptefinancier",
            name="devise",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XAF", "XAF"),
                    ("XOF", "XOF"),
                    ("EUR", "EUR"),
                    ("USD", "USD"),
                    ("CHF", "CHF"),
                    ("GNF", "GNF"),
                    ("GHS", "GHS"),
                    ("MRU", "MRU"),
                    ("ZAR", "ZAR"),
                    ("DZD", "DZD"),
                    ("MAD", "MAD"),
                    ("TND", "TND"),
                    ("LYD", "LYD"),
                    ("SDG", "SDG"),
                    ("NGN", "NGN"),
                    ("KES", "KES"),
                    ("TZS", "TZS"),
                    ("UGX", "UGX"),
                    ("ETB", "ETB"),
                    ("EGP", "EGP"),
                    ("AOA", "AOA"),
                    ("MWK", "MWK"),
                    ("ZMW", "ZMW"),
                    ("BWP", "BWP"),
                ],
                default="XAF",
                max_length=20,
                null=True,
                verbose_name="Devise",
            ),
        ),
        migrations.AlterField(
            model_name="comptefinancier",
            name="presentation",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Présentation"
            ),
        ),
        migrations.AlterField(
            model_name="comptefinancier",
            name="requis_pour_deposer",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Requis pour déposer",
            ),
        ),
        migrations.AlterField(
            model_name="comptefinancier",
            name="source",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Source"
            ),
        ),
        migrations.AlterField(
            model_name="comptefinancier",
            name="type_bilan",
            field=models.CharField(
                choices=[
                    ("Classique", "Classique"),
                    ("Syscohada", "Syscohada"),
                    ("Anglais", "Anglais"),
                    ("Bancaire", "Bancaire"),
                ],
                default="",
                max_length=255,
                null=True,
                verbose_name="Type de bilan",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomptefinancier",
            name="cabinet",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Cabinet"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomptefinancier",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomptefinancier",
            name="credibilite_cabinet",
            field=models.CharField(
                blank=True,
                choices=[("OUI", "Oui"), ("NON", "Non")],
                max_length=200,
                null=True,
                verbose_name="Crédibilité du cabinet pour ACREMAC",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomptefinancier",
            name="date_compte",
            field=models.DateField(
                blank=True, null=True, verbose_name="Début de période de compte N"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomptefinancier",
            name="devise",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XAF", "XAF"),
                    ("XOF", "XOF"),
                    ("EUR", "EUR"),
                    ("USD", "USD"),
                    ("CHF", "CHF"),
                    ("GNF", "GNF"),
                    ("GHS", "GHS"),
                    ("MRU", "MRU"),
                    ("ZAR", "ZAR"),
                    ("DZD", "DZD"),
                    ("MAD", "MAD"),
                    ("TND", "TND"),
                    ("LYD", "LYD"),
                    ("SDG", "SDG"),
                    ("NGN", "NGN"),
                    ("KES", "KES"),
                    ("TZS", "TZS"),
                    ("UGX", "UGX"),
                    ("ETB", "ETB"),
                    ("EGP", "EGP"),
                    ("AOA", "AOA"),
                    ("MWK", "MWK"),
                    ("ZMW", "ZMW"),
                    ("BWP", "BWP"),
                ],
                default="XAF",
                max_length=20,
                null=True,
                verbose_name="Devise",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomptefinancier",
            name="presentation",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Présentation"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomptefinancier",
            name="requis_pour_deposer",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Requis pour déposer",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomptefinancier",
            name="source",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Source"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomptefinancier",
            name="type_bilan",
            field=models.CharField(
                choices=[
                    ("Classique", "Classique"),
                    ("Syscohada", "Syscohada"),
                    ("Anglais", "Anglais"),
                    ("Bancaire", "Bancaire"),
                ],
                default="",
                max_length=255,
                null=True,
                verbose_name="Type de bilan",
            ),
        ),
    ]
