# Generated by Django 5.1.4 on 2025-02-05 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_acheteur_capital_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acheteur',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='acheteur',
            name='province',
        ),
        migrations.RemoveField(
            model_name='acheteur',
            name='ville',
        ),
        migrations.AddField(
            model_name='acheteur',
            name='pays',
            field=models.ForeignKey(blank=True, help_text="Pays où l'entreprise est située", null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.pays', verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='acheteur',
            name='province',
            field=models.ForeignKey(blank=True, help_text="Province où l'entreprise est située", null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='acheteur',
            name='ville',
            field=models.ForeignKey(blank=True, help_text="Ville où l'entreprise est située", null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.ville', verbose_name='Ville'),
        ),
    ]
