# Generated by Django 5.1.4 on 2025-02-05 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_remove_acheteur_pays_remove_acheteur_province_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CredendoCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_id", models.CharField(max_length=255, unique=True)),
                ("reference", models.CharField(max_length=255)),
                ("internal_bp_id", models.CharField(max_length=255)),
                ("nom", models.CharField(max_length=255)),
                ("identifiants", models.TextField(blank=True, null=True)),
                ("rue", models.TextField()),
                ("ville", models.CharField(max_length=100)),
                ("pays", models.CharField(max_length=100)),
                ("remarque", models.TextField(blank=True, null=True)),
                ("priorite", models.CharField(max_length=50)),
                ("texte_complet", models.TextField()),
                (
                    "montant",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("devise", models.CharField(blank=True, max_length=10, null=True)),
                ("date_reception", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="pays",
            field=models.ForeignKey(
                blank=True,
                help_text="Pays où l'employé est affecté",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.pays",
                verbose_name="Pays",
            ),
        ),
    ]
