# Generated by Django 5.0.9 on 2026-01-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_alter_comptefinancier_cabinet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaloperationethistorique",
            name="commentaire_ratios",
            field=models.CharField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Commentaire sur les ratios",
            ),
        ),
        migrations.AlterField(
            model_name="historicaloperationethistorique",
            name="description_complete_activite",
            field=models.CharField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Description complète de l'activité",
            ),
        ),
        migrations.AlterField(
            model_name="historicaloperationethistorique",
            name="historique",
            field=models.TextField(blank=True, null=True, verbose_name="Historique"),
        ),
        migrations.AlterField(
            model_name="operationethistorique",
            name="commentaire_ratios",
            field=models.CharField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Commentaire sur les ratios",
            ),
        ),
        migrations.AlterField(
            model_name="operationethistorique",
            name="description_complete_activite",
            field=models.CharField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Description complète de l'activité",
            ),
        ),
        migrations.AlterField(
            model_name="operationethistorique",
            name="historique",
            field=models.TextField(blank=True, null=True, verbose_name="Historique"),
        ),
    ]
