# Generated by Django 5.0.9 on 2026-01-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0021_alter_historicaloperationethistorique_commentaire_ratios_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproprieteetactif",
            name="branche",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Branche"
            ),
        ),
        migrations.AlterField(
            model_name="proprieteetactif",
            name="branche",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Branche"
            ),
        ),
    ]
