# Generated by Django 5.1.4 on 2025-02-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_credendocommande_customuser_pays'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleNotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Libellé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Mise à Jour')),
            ],
            options={
                'verbose_name': 'Modèle de notation',
                'verbose_name_plural': 'Modèles de notation',
            },
        ),
    ]
