# Generated by Django 5.0.9 on 2026-01-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_alter_historicalproprieteetactif_branche_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conditionachat",
            name="fournisseur",
            field=models.TextField(blank=True, null=True, verbose_name="Fournisseur"),
        ),
        migrations.AlterField(
            model_name="conditionachat",
            name="importation",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="importation",
                to="main.listeconditionachat",
            ),
        ),
        migrations.AlterField(
            model_name="conditionachat",
            name="les_clients",
            field=models.TextField(blank=True, null=True, verbose_name="Les clients"),
        ),
        migrations.AlterField(
            model_name="conditionachat",
            name="local",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="local",
                to="main.listeconditionachat",
            ),
        ),
        migrations.AlterField(
            model_name="historicalconditionachat",
            name="fournisseur",
            field=models.TextField(blank=True, null=True, verbose_name="Fournisseur"),
        ),
        migrations.AlterField(
            model_name="historicalconditionachat",
            name="les_clients",
            field=models.TextField(blank=True, null=True, verbose_name="Les clients"),
        ),
    ]
