# Generated by Django 5.1.4 on 2025-02-07 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_advice_analysesectorielle_antecedantsjuridique_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banquier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_banque",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom de la banque"
                    ),
                ),
                (
                    "numero_compte",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        null=True,
                        verbose_name="Numéro de compte",
                    ),
                ),
                (
                    "type_relation",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Type de relation",
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=200, verbose_name="Numéro"),
                ),
                (
                    "rue",
                    models.CharField(blank=True, max_length=200, verbose_name="Rue"),
                ),
                (
                    "code_postal",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Code postal"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "acheteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main.acheteur",
                        verbose_name="Acheteur",
                    ),
                ),
                (
                    "couleur_commentaire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main.couleurcommentaire",
                        verbose_name="Couleur du commentaire",
                    ),
                ),
                (
                    "ville",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main.ville",
                        verbose_name="Ville",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donnée bancaire",
                "verbose_name_plural": "Données bancaires",
            },
        ),
    ]
