# Generated by Django 5.0.9 on 2026-01-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_alter_conditionachat_fournisseur_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conditiondevente",
            name="comportement_de_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("--------", "--------"),
                    ("En Avance", "En Avance"),
                    ("En Temps et en heure", "En Temps et en heure"),
                    ("En Retard", "En Retard"),
                    ("Normal", "Normal"),
                    ("Mauvais payeur", "Mauvais payeur"),
                    ("Plainte isolée", "Plainte isolée"),
                    ("Inconnu de nos sources", "Inconnu de nos sources"),
                    (
                        "En raison des informations sur les procédures d'insolvabilité/préliminaires/réglementaires, ACREMAC n'est pas en mesure de donner une évaluation finale du comportement de paiement de l'entreprise à ce stade",
                        "En raison des informations sur les procédures d'insolvabilité/préliminaires/réglementaires, ACREMAC n'est pas en mesure de donner une évaluation finale du comportement de paiement de l'entreprise à ce stade",
                    ),
                    (
                        "Aucune expérience de paiement d'une quelconque importance n'est disponible",
                        "Aucune expérience de paiement d'une quelconque importance n'est disponible",
                    ),
                ],
                default="",
                max_length=255,
                verbose_name="Comportement de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="conditiondevente",
            name="recouvrement_de_dette_jugement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("--------", "--------"),
                    (
                        "Aucune information négative n'a été trouvée",
                        "Aucune information négative n'a été trouvée",
                    ),
                    (
                        "Il n'existe aucune trace d'une quelconque action de recouvrement de créances par ACREMAC à l'encontre de cette entreprise",
                        "Il n'existe aucune trace d'une quelconque action de recouvrement de créances par ACREMAC à l'encontre de cette entreprise",
                    ),
                    (
                        "Selon nos sources, l'entreprise n'est pas en situation d'insolvabilité/procédure préliminaire/procédure de répartition des dettes",
                        "Selon nos sources, l'entreprise n'est pas en situation d'insolvabilité/procédure préliminaire/procédure de répartition des dettes",
                    ),
                    (
                        "Des actions en recouvrement judiciaire sont ouvertes contre l'acheteur",
                        "Des actions en recouvrement judiciaire sont ouvertes contre l'acheteur",
                    ),
                    (
                        "Des actions de recouvrement à l'amiable sont ouvertes contre l'acheteur",
                        "Des actions de recouvrement à l'amiable sont ouvertes contre l'acheteur",
                    ),
                    (
                        "Des cas de recouvrement fermés existent chez nos sources sur l'acheteur",
                        "Des cas de recouvrement fermés existent chez nos sources sur l'acheteur",
                    ),
                    ("Inconnu de nos sources", "Inconnu de nos sources"),
                ],
                default="",
                max_length=255,
                verbose_name="Recouvrement de dette jugement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalconditiondevente",
            name="comportement_de_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("--------", "--------"),
                    ("En Avance", "En Avance"),
                    ("En Temps et en heure", "En Temps et en heure"),
                    ("En Retard", "En Retard"),
                    ("Normal", "Normal"),
                    ("Mauvais payeur", "Mauvais payeur"),
                    ("Plainte isolée", "Plainte isolée"),
                    ("Inconnu de nos sources", "Inconnu de nos sources"),
                    (
                        "En raison des informations sur les procédures d'insolvabilité/préliminaires/réglementaires, ACREMAC n'est pas en mesure de donner une évaluation finale du comportement de paiement de l'entreprise à ce stade",
                        "En raison des informations sur les procédures d'insolvabilité/préliminaires/réglementaires, ACREMAC n'est pas en mesure de donner une évaluation finale du comportement de paiement de l'entreprise à ce stade",
                    ),
                    (
                        "Aucune expérience de paiement d'une quelconque importance n'est disponible",
                        "Aucune expérience de paiement d'une quelconque importance n'est disponible",
                    ),
                ],
                default="",
                max_length=255,
                verbose_name="Comportement de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalconditiondevente",
            name="recouvrement_de_dette_jugement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("--------", "--------"),
                    (
                        "Aucune information négative n'a été trouvée",
                        "Aucune information négative n'a été trouvée",
                    ),
                    (
                        "Il n'existe aucune trace d'une quelconque action de recouvrement de créances par ACREMAC à l'encontre de cette entreprise",
                        "Il n'existe aucune trace d'une quelconque action de recouvrement de créances par ACREMAC à l'encontre de cette entreprise",
                    ),
                    (
                        "Selon nos sources, l'entreprise n'est pas en situation d'insolvabilité/procédure préliminaire/procédure de répartition des dettes",
                        "Selon nos sources, l'entreprise n'est pas en situation d'insolvabilité/procédure préliminaire/procédure de répartition des dettes",
                    ),
                    (
                        "Des actions en recouvrement judiciaire sont ouvertes contre l'acheteur",
                        "Des actions en recouvrement judiciaire sont ouvertes contre l'acheteur",
                    ),
                    (
                        "Des actions de recouvrement à l'amiable sont ouvertes contre l'acheteur",
                        "Des actions de recouvrement à l'amiable sont ouvertes contre l'acheteur",
                    ),
                    (
                        "Des cas de recouvrement fermés existent chez nos sources sur l'acheteur",
                        "Des cas de recouvrement fermés existent chez nos sources sur l'acheteur",
                    ),
                    ("Inconnu de nos sources", "Inconnu de nos sources"),
                ],
                default="",
                max_length=255,
                verbose_name="Recouvrement de dette jugement",
            ),
        ),
    ]
