# Generated by Django 5.1.4 on 2025-02-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_banquier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opinioncreditacremac",
            name="risque_de_concentration_credit",
            field=models.IntegerField(
                default=0, verbose_name="Risque de concentration de crédit"
            ),
        ),
        migrations.AlterField(
            model_name="opinioncreditacremac",
            name="risque_de_defaut",
            field=models.IntegerField(default=0, verbose_name="Risque de défaut"),
        ),
        migrations.AlterField(
            model_name="opinioncreditacremac",
            name="risque_de_liquidite",
            field=models.IntegerField(default=0, verbose_name="Risque de liquidité"),
        ),
        migrations.AlterField(
            model_name="opinioncreditacremac",
            name="risque_de_reputation",
            field=models.IntegerField(default=0, verbose_name="Risque de réputation"),
        ),
        migrations.AlterField(
            model_name="opinioncreditacremac",
            name="risque_de_taux_dinteret",
            field=models.IntegerField(
                default=0, verbose_name="Risque de taux d'intérêt"
            ),
        ),
        migrations.AlterField(
            model_name="opinioncreditacremac",
            name="risque_eleve",
            field=models.IntegerField(default=0, verbose_name="Risque élevé"),
        ),
        migrations.AlterField(
            model_name="opinioncreditacremac",
            name="risque_faible",
            field=models.IntegerField(default=0, verbose_name="Risque faible"),
        ),
        migrations.AlterField(
            model_name="opinioncreditacremac",
            name="risque_moyen",
            field=models.IntegerField(default=0, verbose_name="Risque moyen"),
        ),
        migrations.AlterField(
            model_name="opinioncreditacremac",
            name="risque_pays",
            field=models.IntegerField(default=0, verbose_name="Risque pays"),
        ),
    ]
