# Generated by Django 5.0.9 on 2026-01-21 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_alter_conditiondevente_comportement_de_paiement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conditiondevente",
            name="local",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="local",
                to="main.listeconditionvente",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsommaireetavis",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsommaireetavis",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="main.couleurcommentaire",
                verbose_name="Couleur commentaire",
            ),
        ),
        migrations.AlterField(
            model_name="sommaireetavis",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, null=True, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="sommaireetavis",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.couleurcommentaire",
                verbose_name="Couleur commentaire",
            ),
        ),
    ]
