# Generated by Django 5.1.4 on 2025-02-14 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_opinioncreditacremac_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structure',
            options={'verbose_name': 'Filiale ou Branche', 'verbose_name_plural': 'Filiales ou Branches'},
        ),
        migrations.AddField(
            model_name='comptefinancier',
            name='type_bilan_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.modelebilan', verbose_name='Référence Type de bilan'),
        ),
    ]
