# Generated by Django 5.0.9 on 2026-01-23 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_historicalscoringsansbilanacheteur_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalscoring",
            name="commentaire",
            field=models.TextField(
                blank=True,
                help_text="Commentaire détaillé sur le scoring",
                max_length=10000000,
                null=True,
                verbose_name="Commentaire",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscoring",
            name="score",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Score sur 4 caractères maximum",
                max_length=4,
                null=True,
                verbose_name="Score",
            ),
        ),
        migrations.AlterField(
            model_name="scoring",
            name="acheteur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="scorings",
                to="main.acheteur",
                verbose_name="Acheteur",
            ),
        ),
        migrations.AlterField(
            model_name="scoring",
            name="annee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="scorings",
                to="main.annee",
                verbose_name="Année",
            ),
        ),
        migrations.AlterField(
            model_name="scoring",
            name="commentaire",
            field=models.TextField(
                blank=True,
                help_text="Commentaire détaillé sur le scoring",
                max_length=10000000,
                null=True,
                verbose_name="Commentaire",
            ),
        ),
        migrations.AlterField(
            model_name="scoring",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scoring_user_create",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="scoring",
            name="score",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Score sur 4 caractères maximum",
                max_length=4,
                null=True,
                verbose_name="Score",
            ),
        ),
        migrations.AlterField(
            model_name="scoring",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scoring_user_update",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mis à jour par",
            ),
        ),
        migrations.AddIndex(
            model_name="scoring",
            index=models.Index(
                fields=["created_at"], name="main_scorin_created_9ceca5_idx"
            ),
        ),
    ]
