# Generated by Django 5.0.9 on 2026-01-23 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_alter_historicalscoring_commentaire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoring",
            name="acheteur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.acheteur",
                verbose_name="Acheteur",
            ),
        ),
        migrations.AlterField(
            model_name="scoring",
            name="annee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.annee",
                verbose_name="Année",
            ),
        ),
    ]
