# Generated by Django 5.0.9 on 2026-01-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_alter_scoring_acheteur_alter_scoring_annee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Root", "Root"),
                    ("Validateur", "Validateur"),
                    ("Analyste", "Analyste"),
                    ("Client", "Client"),
                ],
                default="Root",
                max_length=100,
                null=True,
                verbose_name="Droits utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Root", "Root"),
                    ("Validateur", "Validateur"),
                    ("Analyste", "Analyste"),
                    ("Client", "Client"),
                ],
                default="Root",
                max_length=100,
                null=True,
                verbose_name="Droits utilisateur",
            ),
        ),
    ]
