# Generated by Django 5.1.4 on 2025-02-19 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_advice_options_actifa_actifc_actifs_assets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actifa',
            name='actif_impots_courant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="Actif d'Impôts courant"),
        ),
        migrations.AlterField(
            model_name='actifa',
            name='biens_installations_equipements',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Biens, installations et équipements'),
        ),
        migrations.AlterField(
            model_name='actifa',
            name='caisses_banques',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Caisse et banque'),
        ),
        migrations.AlterField(
            model_name='actifa',
            name='creances_commerciales_autres_creances',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Créances commerciales et autres'),
        ),
        migrations.AlterField(
            model_name='actifa',
            name='inventaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='amortissements',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Amortissements'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='autres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='autres_creances',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres creances'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='autres_immobilisations_incorporelles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres immobilisations incorporelles'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='autres_immos_corp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres immos corp'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='avances_acptes_verses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Avances acptes verses'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='avances_et_acptes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Avances et acptes'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='banques_cheques_postaux_caisse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Banques cheques postaux caisse'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='brevet_licence_logiciels',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Brevet licence logiciels'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='capital_souscrit_non_app',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Capital sousc. non app'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='cca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Cca'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='charges_a_repartir_et_frais_etablissement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Charges a repartir et frais etablissement'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='clients_et_cptes_rattaches',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Clients et cptes rattaches'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='constructions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Constructions'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='eca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Eca'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='eene',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Eene'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='effectif',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Effectif'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='fonds_commercial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Fonds commercial'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='frais_recherche_developpement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Frais recherche developpement'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='immos_en_cours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Immos en cours'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='materiel_de_transport',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Materiel de transport'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='materiels_et_outils',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Materiels et outils'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='participations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Participations'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='prets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Prets'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='primes_de_rbt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Primes de rbt'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='provisions_creances',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Provisions creances'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='provisions_stocks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Provisions stocks'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='provisions_vmp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Provisions vmp'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='stocks_encours_mp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Stocks encours mp'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='stocks_encours_pf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Stocks encours pf'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='stocks_encours_services',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Stocks encours services'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='stocks_mp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Stocks mp'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='stocks_mses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Stocks mses'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='stocks_pf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Stocks pf'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='terrains',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Terrains'),
        ),
        migrations.AlterField(
            model_name='actifc',
            name='valeurs_a_encaisser',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Valeurs a encaisser'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='actif_circulant_hao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Actif circulant HAO'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='agencements_amenagements_installations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Agencements, aménagements et installations'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='autres_creances',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres créances'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='autres_immo_incorporelles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres immobilisations incorporelles'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='autres_immobilisations_financieres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres immobilisations financières'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='avances_acompte_immobilisations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Avances et acomptes sur immobilisations'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='banque_cheque_postal_caisse_assimiles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Banque, chèque postal, caisse et assimilés'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='batiments',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Bâtiments'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='brevets_licences_logiciels',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Brevets, licences et logiciels'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='clients',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Clients'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='disponibilites',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Disponibilités'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='dons_investissements_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Dons et investissements nets'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='droits_propriete_commerciale_baux',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Droits de propriété commerciale et baux'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='ecart_conversion_actif',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Écart de conversion actif'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='fournisseurs_avances_versee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Fournisseurs, avances versées'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='frais_developpement_prospection',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Frais de développement et prospection'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='materiel_mobilier_actif_biologiques',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Matériel, mobilier et actifs biologiques'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='materiel_transport',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Matériel de transport'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='stock_encours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Stock et en-cours'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='terrains',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Terrains'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='titres_participation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Titres de participation'),
        ),
        migrations.AlterField(
            model_name='actifs',
            name='valeurs_mobilieres_placement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Valeurs mobilières de placement'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='a_terme',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='A Terme'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='actionnaire_ou_associe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='ACTIONNAIRES OU ASSOCIÉS'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='affacturage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Affacturage'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='autres_actifs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='AUTRES ACTIFS'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='autres_ets_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='-Autres établissements de crédit'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='banques_centrales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='-Banques centrales'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='caisse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Caisse'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='comptes_commande_divers',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='COMPTES DE COMMANDES ET DIVERS'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='creances_ordinaires',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Créances ordinaires'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='credits_campagne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='-Crédits de campagne'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='credits_campagne_acc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='-Crédits de campagne'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='credits_ordinaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='-Crédits ordinaires'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='credits_ordinaire_acc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='-Crédits ordinaires'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='immobilisation_corporelle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='IMMOBILISATIONS CORPORELLES'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='immobilisation_fin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='IMMOBILISATIONS FINANCIÈRES'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='immobilisation_incorporelle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='IMMOBILISATIONS INCORPORELLES'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='operation_credit_bail',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='OPÉRATIONS DE CRÉDIT-BAIL ET ASSIMILÉES'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='titres_placement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='TITRES DE PLACEMENT'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='tresorerie_cpp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='-Trésorerie, CCP'),
        ),
        migrations.AlterField(
            model_name='compositionaction',
            name='pourcentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Pourcentage de détention d'actions", max_digits=100, null=True, verbose_name='Pourcentage'),
        ),
        migrations.AlterField(
            model_name='compositioncapitalsocial',
            name='emis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant du capital émis', max_digits=100, null=True, verbose_name='Capital émis'),
        ),
        migrations.AlterField(
            model_name='compositioncapitalsocial',
            name='libere',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant du capital libéré', max_digits=100, null=True, verbose_name='Capital libéré'),
        ),
        migrations.AlterField(
            model_name='compositioncapitalsocial',
            name='publie',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant du capital publié', max_digits=100, null=True, verbose_name='Capital publié'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='achat_marchandises',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='ACHAT DE MARCHANDISES'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='autres_frais_generaux',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres frais généraux'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='autres_interets_charges_assimilee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres Intérêts et charges assimilées'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='charges_exceptionnelle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='LES CHARGES EXCEPTIONNELLES'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='charges_sur_op_credit_bail_assimile',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='CHARGES SUR OPÉRATIONS DE CRÉDIT-BAIL ET ASSIMILÉES'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='charges_sur_operation_change',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Charges sur titres de placement', max_digits=100, null=True, verbose_name='Charges sur opérations de change'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='charges_sur_operation_hors_bilan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Charges sur opérations hors bilan'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='charges_sur_titre_placement',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Charges sur titres de placement', max_digits=100, null=True, verbose_name='Charges sur titres de placement'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='chargesc_compte_bloque_dactionnaire_emprunt_sub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="Charges sur comptes bloqués d'actionnaires emprunts sur titres subordonnés"),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='commissions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='COMMISSIONS'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='dotations_amortissement_provision_immobilisation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='DOTATIONS AUX AMORTISSEMENTS ET PROVISIONS SUR IMMOBILISATIONS'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='excedent_dotation_reprises_fonds_pour_risque_bancaire_generaux',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='EXCÉDENT DES DOTATIONS SUR LES REPRISES DU FONDS POUR RISQUES BANCAIRES GÉNÉRAUX'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='frais_divers_exploitation_bancaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="FRAIS DIVERS D'EXPLOITATION BANCAIRE"),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='frais_personnel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Frais de personnel'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='impot_sur_revenu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='IMPÔTS SUR LE REVENU'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='interet_charge_assimilee_dette_clientele',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Intérêts et charges assimilées sur dettes envers la clientèle'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='interet_charge_assimilee_titre_creance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Intérêts et charges assimilées sur titres de créances'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='interet_charges_assimilee_dette_interbancaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Intérêts et charges assimilées sur dettes interbancaires'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='pertes_exercice_anterieurs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='PERTES SUR EXERCICES ANTÉRIEURS'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='solde_perte_creance_hors_bilan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='SOLDE DES PERTES SUR CRÉANCES ET HORS BILAN'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='stocks_vendus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='STOCKS VENDUS'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='total_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='TOTAL DES CHARGES'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='variations_stocks_marchanides',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='VARIATIONS DES STOCKS DE MARCHANDISES'),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='a_terme',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='A Terme'),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='autres_dette_a_terme',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres dettes à terme'),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='autres_dette_a_vue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres dettes à vue'),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='autres_etablissement_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='-Autres établissements de crédit'),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='benefices_non_distribue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='BÉNÉFICES NON DISTRIBUÉS (+/-)'),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='bons_caisse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Bons de caisse'),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='capital_ou_dotation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='CAPITAL OU DOTATIONS'),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='compte_dordre_divers',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="COMPTES D'ORDRE ET DIVERS"),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='comptes_epargne_court_terme',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="Comptes d'épargne à court terme"),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='comptes_epargne_terme',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="Comptes d'épargne à terme"),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='ecarts_reevaluation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='ÉCARTS DE RÉÉVALUATION'),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='emprunt_subordonne_tire_emis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='EMPRUNTS SUBORDONNÉS ET TITRES ÉMIS'),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='fonds_affecte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='FONDS AFFECTÉS'),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='fonds_pour_risque_bancaire_generaux',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='FONDS POUR RISQUES BANCAIRES GÉNÉRAUX'),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='primes_liees_reserve_capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='PRIMES LIÉES AUX RÉSERVES DE CAPITAL'),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='provision_pour_risque_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='PROVISIONS POUR RISQUES ET CHARGES'),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='provision_reglementee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='PROVISIONS RÉGLEMENTÉES'),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='resultat_net_exercie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="RÉSULTAT NET DE L'EXERCICE (+/-)"),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='subventions_investissement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="SUBVENTIONS D'INVESTISSEMENT"),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='titres_creance_autres_dettes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='TITRES DE CRÉANCE AUTRES DETTES'),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='tresorerie_ccp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='-Trésorerie, CCP'),
        ),
        migrations.AlterField(
            model_name='offbalancesheet',
            name='en_faveur_clientele',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='En faveur de la clientèle'),
        ),
        migrations.AlterField(
            model_name='offbalancesheet',
            name='en_faveur_des_ets_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='En faveur des établissements de crédit'),
        ),
        migrations.AlterField(
            model_name='offbalancesheet',
            name='engagement_sur_titre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='ENGAGEMENTS SUR TITRES'),
        ),
        migrations.AlterField(
            model_name='offbalancesheet',
            name='engagement_sur_titre2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='ENGAGEMENTS SUR TITRES'),
        ),
        migrations.AlterField(
            model_name='offbalancesheet',
            name='pour_compte_clientele',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Pour le compte de la clientèle'),
        ),
        migrations.AlterField(
            model_name='offbalancesheet',
            name='pour_compte_ets_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Pour le compte des établissements de crédit'),
        ),
        migrations.AlterField(
            model_name='offbalancesheet',
            name='recu_clientele',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Reçus de la clientèle'),
        ),
        migrations.AlterField(
            model_name='offbalancesheet',
            name='recu_ets_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="Reçus d'établissements de crédit"),
        ),
        migrations.AlterField(
            model_name='offbalancesheet',
            name='recu_ets_credit2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="Reçus d'établissements de crédit"),
        ),
        migrations.AlterField(
            model_name='passifa',
            name='benefices_non_distribues',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Bénéfices non distribués'),
        ),
        migrations.AlterField(
            model_name='passifa',
            name='capital_declare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Capital déclaré'),
        ),
        migrations.AlterField(
            model_name='passifa',
            name='capital_reserves',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Capital et Réserves'),
        ),
        migrations.AlterField(
            model_name='passifa',
            name='compte_courant_administrateurs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Compte courant des administrateurs'),
        ),
        migrations.AlterField(
            model_name='passifa',
            name='decouvert_bancaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Découvert bancaire'),
        ),
        migrations.AlterField(
            model_name='passifa',
            name='dettes_commerciales_autres_dettes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Dettes commerciales et autres dettes'),
        ),
        migrations.AlterField(
            model_name='passifa',
            name='impots',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Impôts'),
        ),
        migrations.AlterField(
            model_name='passifa',
            name='pret_bancaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Prêt bancaire'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='autres_dettes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres dettes'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='avance_et_acomptes_recu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Avance et acomptes recu'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='banque_credit_caisse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Banque credit caisse'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='banques_credit_escompte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Banques credit escompte'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='banques_decouvert',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Banques decouvert'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='capital_social',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Capital social'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='dette_credit_bail_contrat_assimile',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Credit lease debts and related contracts'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='dettes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Dettes'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='dettes_financiere_diverses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Dettes financiere diverses'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='dettes_fiscales_sociales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Dettes fiscales sociales'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='dettes_fournisseurs_divers',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Dettes fournisseurs divers'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='ecart_conversion_passif',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Ecart conversion passif'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='ecarts_de_reevaluation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Eca'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='emprunts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Emprunts'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='primes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Primes'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='provision_financiere_risque_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Provision financiere risque charge'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='provision_regl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Provision regle'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='report_a_nouveau',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Report a nouveau'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='reserve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Reserve'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='resultat_exercice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Resultat exercice'),
        ),
        migrations.AlterField(
            model_name='passifc',
            name='subv_invest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Subventions investies'),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='autres_dettes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres dettes'),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='banques_credit_escompte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="Banques, crédits d'escompte"),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='banques_etablissements_financiers_credit_caisse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Banques, établissements financiers et crédits de caisse'),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Capital'),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='capital_non_appele_apporteurs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Capital non appelé des apporteurs'),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='clients_avances_recues',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Clients, avances reçues'),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='dettes_fiscales_sociales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Dettes fiscales et sociales'),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='dettes_location_vente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Dettes de location-vente'),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='ecart_conversion_passif',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Écarts de conversion - Passif'),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='ecart_reevaluation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Écart de réévaluation'),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='emprunts_dettes_financieres_diverse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Emprunts et dettes financières diverses'),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='fournisseurs_exploitation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="Fournisseurs d'exploitation"),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='passif_circulant_hao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Passif circulant HAO'),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='primes_liees_capital_social',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Primes liées au capital social'),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='provisions_reglees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Provisions réglées'),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='provisions_risques_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Provisions pour risques et charges'),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='provisions_risques_court_terme',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Provisions pour risques à court terme'),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='report_nouveau',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Report à nouveau (+ ou -)'),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='reserves_indisponibles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Réserves indisponibles'),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='reserves_libres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Réserves libres'),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='resultat_net_exercice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="Résultat net de l'exercice (bénéfice + ou perte -)"),
        ),
        migrations.AlterField(
            model_name='passifs',
            name='subventions_investissements',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="Subventions d'investissement"),
        ),
        migrations.AlterField(
            model_name='products',
            name='autres_interets_produits_assimiles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres intérêts et produits assimilés'),
        ),
        migrations.AlterField(
            model_name='products',
            name='benefice_sur_exercice_anterieur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='BÉNÉFICES SUR EXERCICES ANTÉRIEURS'),
        ),
        migrations.AlterField(
            model_name='products',
            name='commissions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='COMMISSIONS'),
        ),
        migrations.AlterField(
            model_name='products',
            name='dividendes_produits_assimiles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Dividendes et produits assimilés'),
        ),
        migrations.AlterField(
            model_name='products',
            name='excedent_reprise_fonds_pour_risque_bancaire_generaux',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='EXCÉDENT DES REPRISES DU FONDS POUR RISQUES BANCAIRES GÉNÉRAUX'),
        ),
        migrations.AlterField(
            model_name='products',
            name='ineterets_produit_assimile_pret_avance_clientele',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Intérêts et produits assimilés sur prêts et avances à la clientèle'),
        ),
        migrations.AlterField(
            model_name='products',
            name='interet_produit_sur_titre_dinvestissement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="Intérêts et produits assimilés sur titres d'investissement"),
        ),
        migrations.AlterField(
            model_name='products',
            name='interets_produit_assimile_sur_pret_avance_interbancaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Intérêts et produits assimilés sur prêts et avances interbancaires'),
        ),
        migrations.AlterField(
            model_name='products',
            name='marges_vente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='MARGES DE VENTE'),
        ),
        migrations.AlterField(
            model_name='products',
            name='perte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='PERTES'),
        ),
        migrations.AlterField(
            model_name='products',
            name='produit_dexploitation_generale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="PRODUITS D'EXPLOITATION GÉNÉRALE"),
        ),
        migrations.AlterField(
            model_name='products',
            name='produits_bancaire_divers',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='PRODUITS BANCAIRES DIVERS'),
        ),
        migrations.AlterField(
            model_name='products',
            name='produits_exceptionnels',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='PRODUITS EXCEPTIONNELS'),
        ),
        migrations.AlterField(
            model_name='products',
            name='produits_leansing_operation_connexes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='PRODUITS DE LEASING ET OPÉRATIONS CONNEXES '),
        ),
        migrations.AlterField(
            model_name='products',
            name='produits_opeations_hors_bilan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Produits des opérations hors bilan'),
        ),
        migrations.AlterField(
            model_name='products',
            name='reprise_damortissement_provisions_sur_immobilisation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="REPRISES D'AMORTISSEMENTS ET DE PROVISIONS SUR IMMOBILISATIONS"),
        ),
        migrations.AlterField(
            model_name='products',
            name='revenu_gains_titre_pret_titre_subordonne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Revenus et gains sur titres de prêts et titres subordonnés émis'),
        ),
        migrations.AlterField(
            model_name='products',
            name='revenus_operation_de_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="Revenus d'opérations de change"),
        ),
        migrations.AlterField(
            model_name='products',
            name='revenus_titre_negociable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Revenus de titres négociables'),
        ),
        migrations.AlterField(
            model_name='products',
            name='solde_resultat_correction_valeur_sur_creance_hors_bilan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='SOLDE DU RÉSULTAT DES CORRECTIONS DE VALEUR SUR CRÉANCES ET HORS BILAN'),
        ),
        migrations.AlterField(
            model_name='products',
            name='variation_stocks_marchandises',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='VARIATION DES STOCKS DE MARCHANDISES'),
        ),
        migrations.AlterField(
            model_name='products',
            name='ventes_marchandises',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='VENTES DE MARCHANDISES'),
        ),
        migrations.AlterField(
            model_name='resultata',
            name='autres_elements_resultat_global',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres éléments du résultat global'),
        ),
        migrations.AlterField(
            model_name='resultata',
            name='autres_revenus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultata',
            name='charge_impot_sur_revenu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="Charge d'impôt sur le revenu"),
        ),
        migrations.AlterField(
            model_name='resultata',
            name='charges_exploitation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="Charges d'exploitation"),
        ),
        migrations.AlterField(
            model_name='resultata',
            name='frais_financier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultata',
            name='frais_vente_generaux_administratifs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Frais de vente, généraux et administratifs'),
        ),
        migrations.AlterField(
            model_name='resultata',
            name='produits_activites_ordinaires',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Produits des activités ordinaires'),
        ),
        migrations.AlterField(
            model_name='resultata',
            name='ventes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='achat_mdses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Achat mdses'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='achat_mp_autres_appro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Achat mp autres appro'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='autres_achats',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres achats'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='autres_charges_excedent_brute',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres charges excedent brute'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='autres_charges_valeur_ajoutee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres charges valeur ajoutee'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='autres_produits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres produits'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='ch_nettes_cessions_vmp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Ch nettes cessions vmp'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='charges_personnel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Charges personnel'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='dap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Dot. aux prov. & depreciations'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='dap_et_transfert_charg_except',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Dap et transfert charg except'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='diff_negatives_de_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Diff negatives de change'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='diff_positive_de_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Diff positive de change'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='dotation_aux_amorts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Dotation aux amorts'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='dotation_aux_provisions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Dotation aux provisions'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='frais_fin_charges_assi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Frais fin. & chrges assimilées'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='impot_sur_benefices',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Impôts sur les bénéfices'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='impots_taxes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Impots taxes'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='interets_produit_assim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Interets produit assim'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='participation_salairies',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Participations des salariés'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='prod_nets_cessions_vmp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Prod nets cessions vmp'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='production_imblise',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Production imblise'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='production_stockee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Production stockee'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='produit_accessoires',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Produit accessoires'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='prof_vmp_et_cre_actif_immo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Prof vmp et cre actif immo'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='reprise_prov_et_transfert',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Reprise prov et transfert'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='reprise_prov_transfert',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Reprise prov transfert'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='reprises_de_provision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Reprises de provision'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='revenus_fin_assimiles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Revenus fin assimiles'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='services_ext',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Services ext'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='subventions_exploitations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Subventions exploitations'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='sur_op_en_capital_charg_except',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Sur op en capital charg except'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='sur_op_en_capital_prod_except',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Sur op en capital prod except'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='sur_op_gestion_charg_except',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Sur op gestion charg except'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='sur_op_gestion_prod_except',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Sur op gestion prod except'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='transferts_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Transferts charges'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='transports',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Transports'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='travaux_services_vendus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Travaux services vendus'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='var_stk_mp_app',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Var stk mp app'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='variation_de_stocks_autres_appro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Variation de stocks autres appro'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='variation_stock_mdses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Variation stock mdses'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='vente_de_mdses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Vente de mdses'),
        ),
        migrations.AlterField(
            model_name='resultatc',
            name='ventes_de_produits_fabriques',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Ventes de produits fabriques'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='achats_marchandises',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Achats de marchandises (-)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='achats_matieres_premieres_fournitures_connexes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Achats de matières premières et fournitures connexes (-)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='autres_achats',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres achats (-)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='autres_charges_hao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres charges HAO (-)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='autres_depenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres dépenses (-)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='autres_produits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres produits (+)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='autres_produits_hao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Autres produits HAO (+)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='charge_impot_revenu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="Charge d'impôt sur le revenu (-)"),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='charges_financieres_assimilees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Charges financières et assimilées (-)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='dotations_provisions_depreciations_financieres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Dotations aux provisions et dépréciations financières (-)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='frais_personnel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Frais de personnel (-)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='impots_taxes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Impots et taxes (-)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='participation_travailleurs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Participation des travailleurs (-)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='production_immobilisee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Production Immobilisée (+)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='production_stockee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Production stockée (ou déstockage) (-/+)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='produits_accessoires_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Produits accessoires D (+)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='produits_cession_immobilisations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="Produits des cessions d'immobilisations (+)"),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='produits_financiers_assimiles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Produits financiers et assimilés (+)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='reprise_depreciations_amortissements_provision_pertes_valeurs_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Reprises de dépréciations, amortissements, provisions et pertes de valeur (-)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='reprise_depreciations_amortissements_provision_pertes_valeurs_p',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Reprises de dépréciations, amortissements, provisions et pertes de valeur (+)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='reprise_provision_perte_valeur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Reprises sur provisions et pertes de valeur (+)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='services_exterieurs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Services extérieurs (-)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='subvention_exploitation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="Subvention d'exploitation (+)"),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='transfert_charges_exploitation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="Transfert de charges d'exploitation (+)"),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='transfert_charges_financieres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Transfert de charges financières (+)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='transport',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Transport (-)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='travaux_services_vendus_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Travaux, services vendus C (+)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='valeur_comptable_cessions_actifs_immobilises',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="Valeur comptable des cessions d'actifs immobilisés (-)"),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='variation_stock_autres_fournitures',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name="Variation des stocks d'autres fournitures (-/+)"),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='variation_stock_marchandises',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Variation des stocks de marchandises (-/+)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='variation_stock_matieres_premieres_fournitures_connexes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Variation des stocks de matières premières et fournitures connexes (-/+)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='ventes_marchandises_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Ventes de marchandises A (+)'),
        ),
        migrations.AlterField(
            model_name='resultats',
            name='ventes_produits_manufactures',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Ventes de produits manufacturés B (+)'),
        ),
        migrations.CreateModel(
            name='Cnss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text="Numéro de sécurité sociale de l'entreprise", max_length=255, verbose_name='Numéro de sécurité sociale')),
                ('date_affiliation', models.DateField(blank=True, help_text="Date d'affiliation à la sécurité sociale", null=True, verbose_name="Date d'affiliation")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('acheteur', models.ForeignKey(blank=True, help_text='Acheteur associé au numéro de sécurité sociale', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cnss', to='main.acheteur', verbose_name='Acheteur')),
            ],
            options={
                'verbose_name': 'CNSS',
                'verbose_name_plural': 'CNSS',
            },
        ),
        migrations.CreateModel(
            name='CodeNaceAcheteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Code NACE de l'entreprise", max_length=255, verbose_name='Code NACE')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('acheteur', models.ForeignKey(blank=True, help_text='Acheteur associé au code NACE', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='code_nace', to='main.acheteur', verbose_name='Acheteur')),
            ],
            options={
                'verbose_name': 'Code NACE Acheteur',
                'verbose_name_plural': 'Codes NACE Acheteur',
            },
        ),
        migrations.CreateModel(
            name='CodeNafAcheteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Code NAF de l'entreprise", max_length=255, verbose_name='Code NAF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('acheteur', models.ForeignKey(blank=True, help_text='Acheteur associé au code NAF', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='code_naf', to='main.acheteur', verbose_name='Acheteur')),
            ],
            options={
                'verbose_name': 'Code NAF Acheteur',
                'verbose_name_plural': 'Codes NAF Acheteur',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre du document', max_length=255, verbose_name='Titre')),
                ('fichier', models.FileField(help_text='Fichier du document', upload_to='documents/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, help_text='Description du document', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('acheteur', models.ForeignKey(blank=True, help_text='Acheteur associé au document', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='main.acheteur', verbose_name='Acheteur')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.EmailField(help_text="Adresse email de l'entreprise", max_length=254, verbose_name='Adresse email')),
                ('type', models.CharField(choices=[('professionnel', 'Professionnel'), ('personnel', 'Personnel')], help_text="Type d'adresse email", max_length=50, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('acheteur', models.ForeignKey(blank=True, help_text="Acheteur associé à l'adresse email", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emails', to='main.acheteur', verbose_name='Acheteur')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text="Image du logo de l'entreprise", null=True, upload_to='logos/', verbose_name='Image')),
                ('description', models.TextField(blank=True, help_text='Description du logo', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('acheteur', models.ForeignKey(blank=True, help_text='Acheteur associé au logo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logo', to='main.acheteur', verbose_name='Acheteur')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
            },
        ),
        migrations.CreateModel(
            name='NumeroIdentificationFiscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text="Numéro d'identification fiscale de l'entreprise", max_length=255, verbose_name="Numéro d'identification fiscale")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('acheteur', models.ForeignKey(blank=True, help_text="Acheteur associé au numéro d'identification fiscale", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='numero_identification_fiscale', to='main.acheteur', verbose_name='Acheteur')),
            ],
            options={
                'verbose_name': "Numéro d'Identification Fiscale",
                'verbose_name_plural': "Numéros d'Identification Fiscale",
            },
        ),
        migrations.CreateModel(
            name='NumeroIdentificationUnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text="Numéro d'identification unique de l'entreprise", max_length=255, verbose_name="Numéro d'identification unique")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('acheteur', models.ForeignKey(blank=True, help_text="Acheteur associé au numéro d'identification unique", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='numero_identification_unique', to='main.acheteur', verbose_name='Acheteur')),
            ],
            options={
                'verbose_name': "Numéro d'Identification Unique",
                'verbose_name_plural': "Numéros d'Identification Unique",
            },
        ),
        migrations.CreateModel(
            name='ProcedureCollective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_procedure', models.CharField(help_text='Type de procédure collective', max_length=255, verbose_name='Type de procédure')),
                ('date_ouverture', models.DateField(blank=True, help_text="Date d'ouverture de la procédure", null=True, verbose_name="Date d'ouverture")),
                ('date_cloture', models.DateField(blank=True, help_text='Date de clôture de la procédure', null=True, verbose_name='Date de clôture')),
                ('description', models.TextField(blank=True, help_text='Description de la procédure collective', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('acheteur', models.ForeignKey(blank=True, help_text='Acheteur associé à la procédure collective', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procedures_collectives', to='main.acheteur', verbose_name='Acheteur')),
            ],
            options={
                'verbose_name': 'Procédure Collective',
                'verbose_name_plural': 'Procédures Collectives',
            },
        ),
        migrations.CreateModel(
            name='RegistreCommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text="Numéro de registre de commerce de l'entreprise", max_length=255, verbose_name='Numéro de registre de commerce')),
                ('date_inscription', models.DateField(blank=True, help_text="Date d'inscription au registre de commerce", null=True, verbose_name="Date d'inscription")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('acheteur', models.ForeignKey(blank=True, help_text='Acheteur associé au registre de commerce', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='registre_commerce', to='main.acheteur', verbose_name='Acheteur')),
            ],
            options={
                'verbose_name': 'Registre de Commerce',
                'verbose_name_plural': 'Registres de Commerce',
            },
        ),
        migrations.CreateModel(
            name='Swot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forces', models.TextField(blank=True, help_text="Forces de l'entreprise", null=True, verbose_name='Forces')),
                ('faiblesses', models.TextField(blank=True, help_text="Faiblesses de l'entreprise", null=True, verbose_name='Faiblesses')),
                ('opportunites', models.TextField(blank=True, help_text="Opportunités de l'entreprise", null=True, verbose_name='Opportunités')),
                ('menaces', models.TextField(blank=True, help_text="Menaces de l'entreprise", null=True, verbose_name='Menaces')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('acheteur', models.ForeignKey(blank=True, help_text="Acheteur associé à l'analyse SWOT", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='swot', to='main.acheteur', verbose_name='Acheteur')),
            ],
            options={
                'verbose_name': 'SWOT',
                'verbose_name_plural': 'SWOT',
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text="Numéro de téléphone de l'entreprise", max_length=20, verbose_name='Numéro de téléphone')),
                ('type', models.CharField(choices=[('fixe', 'Fixe'), ('mobile', 'Mobile'), ('fax', 'Fax')], help_text='Type de numéro de téléphone', max_length=50, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('acheteur', models.ForeignKey(blank=True, help_text='Acheteur associé au numéro de téléphone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='telephones', to='main.acheteur', verbose_name='Acheteur')),
            ],
            options={
                'verbose_name': 'Téléphone',
                'verbose_name_plural': 'Téléphones',
            },
        ),
    ]
