# Generated by Django 5.1.4 on 2025-02-24 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_actifa_actif_impots_courant_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cnss',
            new_name='Cotisation',
        ),
        migrations.RemoveField(
            model_name='numeroidentificationfiscale',
            name='acheteur',
        ),
        migrations.RemoveField(
            model_name='numeroidentificationunique',
            name='acheteur',
        ),
        migrations.RemoveField(
            model_name='telephone',
            name='acheteur',
        ),
        migrations.AlterModelOptions(
            name='cotisation',
            options={'verbose_name': 'Cotisation Sociale', 'verbose_name_plural': 'Cotisations Sociales'},
        ),
        migrations.CreateModel(
            name='EmailAcheteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=254, verbose_name='Adresse email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('acheteur', models.ForeignKey(blank=True, help_text="Acheteur associé à l'email", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emails', to='main.acheteur', verbose_name='Acheteur')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emails_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emails_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='PortableAcheteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portable', models.TextField(max_length=100, verbose_name='Numéro portable')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('acheteur', models.ForeignKey(blank=True, help_text='Acheteur associé au portable', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='portables', to='main.acheteur', verbose_name='Acheteur')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='portables_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='portables_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portable',
                'verbose_name_plural': 'Portables',
            },
        ),
        migrations.CreateModel(
            name='TelephoneAcheteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.TextField(max_length=100, verbose_name='Téléphone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('acheteur', models.ForeignKey(blank=True, help_text='Acheteur associé au téléphone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='telephones', to='main.acheteur', verbose_name='Acheteur')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='telephones_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='telephones_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Téléphone',
                'verbose_name_plural': 'Téléphones',
            },
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='NumeroIdentificationFiscale',
        ),
        migrations.DeleteModel(
            name='NumeroIdentificationUnique',
        ),
        migrations.DeleteModel(
            name='Telephone',
        ),
    ]
