# Generated by Django 5.0.9 on 2026-02-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0033_remove_historicaloffbalancesheet_engagement_financement_donne_clientele_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="conditionachat",
            name="importation",
            field=models.ManyToManyField(
                blank=True, related_name="importation", to="main.listeconditionachat"
            ),
        ),
        migrations.AlterField(
            model_name="conditionachat",
            name="local",
            field=models.ManyToManyField(
                blank=True, related_name="local", to="main.listeconditionachat"
            ),
        ),
        migrations.AlterField(
            model_name="conditiondevente",
            name="local",
            field=models.ManyToManyField(
                blank=True, related_name="local", to="main.listeconditionvente"
            ),
        ),
    ]
