# Generated by Django 5.1.4 on 2025-02-27 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_credendocommande_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produits', models.TextField(blank=True, help_text="Produits de l'entreprise", null=True, verbose_name='Produits')),
                ('services', models.TextField(blank=True, help_text="Services de l'entreprise", null=True, verbose_name='Services')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('acheteur', models.ForeignKey(blank=True, help_text='Acheteur associé', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='produits_services', to='main.acheteur', verbose_name='Acheteur')),
            ],
            options={
                'verbose_name': 'Produit & Service',
                'verbose_name_plural': 'Produits & Services',
            },
        ),
    ]
