# Generated by Django 5.0.9 on 2026-02-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_alter_conditionachat_importation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="is_client",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user is a client user.",
                verbose_name="is client",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_client",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user is a client user.",
                verbose_name="is client",
            ),
        ),
    ]
