# Generated by Django 5.1.4 on 2025-02-27 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_produitservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marques', models.TextField(blank=True, help_text="Marques de l'entreprise", null=True, verbose_name='Marques')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('acheteur', models.ForeignKey(blank=True, help_text='Acheteur associé', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='marques', to='main.acheteur', verbose_name='Acheteur')),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
            },
        ),
    ]
