# Generated by Django 5.0.9 on 2025-02-27 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_marque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notre_ref', models.CharField(blank=True, help_text='Référence interne de la commande.', max_length=100, null=True, verbose_name='Notre référence')),
                ('reference_client', models.CharField(blank=True, help_text='Référence attribuée par le client.', max_length=100, null=True, verbose_name='Référence client')),
                ('date_recept_commande', models.DateField(blank=True, help_text='Date à laquelle la demande a été reçue.', null=True, verbose_name='Date de réception de la demande')),
                ('date_rapport', models.DateField(blank=True, help_text="Date prévue pour l'émission du rapport.", null=True, verbose_name='Date du rapport')),
                ('delais', models.CharField(blank=True, help_text='Délai de traitement de la commande.', max_length=100, null=True, verbose_name='Délais')),
                ('priorite', models.CharField(blank=True, help_text='Niveau de priorité de la commande.', max_length=100, null=True, verbose_name='Priorité')),
                ('raison_sociale', models.CharField(help_text="Nom de l'entreprise ou de l'entité concernée par la commande.", max_length=100, verbose_name='Raison sociale')),
                ('type_rapport', models.CharField(choices=[('--------', '--------'), ('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Flash', 'Flash'), ('Super flash', 'Super flash')], default='--------', help_text='Type de rapport demandé par le client.', max_length=100, verbose_name='Type de rapport')),
                ('credit_demande', models.DecimalField(blank=True, decimal_places=5, help_text='Montant du crédit initialement demandé par le client.', max_digits=100, null=True, verbose_name='Crédit demandé')),
                ('credit_recommande', models.DecimalField(blank=True, decimal_places=5, help_text='Montant du crédit finalement recommandé.', max_digits=100, null=True, verbose_name='Crédit recommandé')),
                ('numero_adresse', models.CharField(blank=True, help_text="Numéro de rue ou d'unité de l'adresse concernée.", max_length=100, null=True, verbose_name="Numéro d'adresse")),
                ('rue_adresse', models.CharField(blank=True, help_text="Nom de la rue de l'adresse concernée.", max_length=200, null=True, verbose_name='Rue adresse')),
                ('code_postale_adresse', models.CharField(blank=True, help_text="Code postal de l'adresse concernée.", max_length=200, null=True, verbose_name='Code postal adresse')),
                ('telephone', models.CharField(blank=True, help_text='Numéro de téléphone du contact.', max_length=100, null=True, verbose_name='Téléphone')),
                ('email', models.CharField(blank=True, help_text='Adresse email du contact.', max_length=100, null=True, verbose_name='Email')),
                ('status', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours de traitement'), ('rapport_soumis', 'Rapport soumis'), ('rapport_valide', 'Rapport validé'), ('envoye_client', 'Envoyé au client'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='nouvelle', max_length=20, verbose_name='Statut de la commande')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de la création de la commande.', verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière mise à jour de la commande.', verbose_name='Date de mise à jour')),
                ('acheteur', models.ForeignKey(blank=True, help_text='Personne ou entité achetant le service ou produit.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.acheteur', verbose_name='Acheteur')),
                ('client', models.ForeignKey(blank=True, help_text='Client ayant passé la commande.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('devise_credit_demande', models.ForeignKey(blank=True, help_text='Devise utilisée pour le crédit demandé.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='devise_credit_demande', to='main.devise', verbose_name='Devise du crédit demandé')),
                ('devise_credit_recommande', models.ForeignKey(blank=True, help_text='Devise utilisée pour le crédit recommandé.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='devise_credit_recommande', to='main.devise', verbose_name='Devise du crédit recommandé')),
                ('ref_type_rapport', models.ForeignKey(blank=True, help_text='Modèle de rapport utilisé pour cette commande.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.modelerapport', verbose_name='Référence du modèle de rapport')),
                ('ville', models.ForeignKey(blank=True, help_text="Ville où se trouve l'entreprise ou le client.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.ville', verbose_name='Ville')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='AffectationAnalyste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'affectation")),
                ('analyste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analystes', to=settings.AUTH_USER_MODEL, verbose_name='Analyste')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': "Affectation d'analyste",
                'verbose_name_plural': 'Affectations des analystes',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AFFECTATION', 'Nouvelle affectation'), ('RAPPORT_SOUMIS', 'Rapport soumis'), ('VALIDATION', 'Rapport validé'), ('CORRECTION', 'Correction demandée'), ('ENVOI_CLIENT', 'Rapport envoyé au client'), ('RAPPEL', 'Rappel de notification')], max_length=50, verbose_name='Type de notification')),
                ('message', models.TextField(verbose_name='Message de notification')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.commande', verbose_name='Commande associée')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur concerné')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='rapports/', verbose_name='Fichier rapport')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('analyste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to=settings.AUTH_USER_MODEL, verbose_name='Analyste')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
            },
        ),
        migrations.CreateModel(
            name='SuiviCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Action')),
                ('type', models.CharField(choices=[('CREATION', 'Création'), ('AFFECTATION', 'Affectation'), ('SOUMISSION', 'Soumission de rapport'), ('VALIDATION', 'Validation'), ('CORRECTION', 'Correction demandée'), ('ENVOI_CLIENT', 'Envoi au client'), ('CLOTURE', 'Clôture'), ('ANNULATION', 'Annulation'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50, verbose_name="Type d'action")),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.commande', verbose_name='Commande')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Suivi de commande',
                'verbose_name_plural': 'Suivis de commande',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('a_corriger', 'À corriger')], default='en_attente', max_length=20, verbose_name='Statut de validation')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire du validateur')),
                ('date_validation', models.DateTimeField(auto_now=True, verbose_name='Date de validation')),
                ('rapport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.rapport', verbose_name='Rapport')),
                ('validateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to=settings.AUTH_USER_MODEL, verbose_name='Analyste validateur')),
            ],
            options={
                'verbose_name': 'Validation de rapport',
                'verbose_name_plural': 'Validations de rapports',
            },
        ),
    ]
