# Generated by Django 5.0.9 on 2026-02-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_commande_client_nom_commande_type_commande_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalnotification",
            name="type",
            field=models.CharField(
                choices=[
                    ("AFFECTATION", "Nouvelle affectation"),
                    ("RAPPORT_SOUMIS", "Rapport soumis"),
                    ("VALIDATION", "Rapport validé"),
                    ("CORRECTION", "Correction demandée"),
                    ("ENVOI_CLIENT", "Rapport envoyé au client"),
                    ("RAPPEL", "Rappel de notification"),
                    ("ENVOI_REUSSI", "Envoi réussi"),
                    ("ENVOI_ECHEC", "Échec d'envoi"),
                    ("RAPPORT_GENERE", "Rapport généré"),
                    ("TACHE_TERMINEE", "Tâche terminée"),
                    ("INFO", "Information"),
                    ("ALERTE", "Alerte"),
                ],
                max_length=50,
                verbose_name="Type de notification",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("AFFECTATION", "Nouvelle affectation"),
                    ("RAPPORT_SOUMIS", "Rapport soumis"),
                    ("VALIDATION", "Rapport validé"),
                    ("CORRECTION", "Correction demandée"),
                    ("ENVOI_CLIENT", "Rapport envoyé au client"),
                    ("RAPPEL", "Rappel de notification"),
                    ("ENVOI_REUSSI", "Envoi réussi"),
                    ("ENVOI_ECHEC", "Échec d'envoi"),
                    ("RAPPORT_GENERE", "Rapport généré"),
                    ("TACHE_TERMINEE", "Tâche terminée"),
                    ("INFO", "Information"),
                    ("ALERTE", "Alerte"),
                ],
                max_length=50,
                verbose_name="Type de notification",
            ),
        ),
    ]
