# Generated by Django 5.0.9 on 2026-03-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0037_alter_historicalnotification_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalregistrecommerce",
            name="est_actif",
            field=models.BooleanField(
                default=True,
                help_text="Indique si ce registre de commerce est celui actuellement en vigueur",
                verbose_name="Registre actif",
            ),
        ),
        migrations.AddField(
            model_name="registrecommerce",
            name="est_actif",
            field=models.BooleanField(
                default=True,
                help_text="Indique si ce registre de commerce est celui actuellement en vigueur",
                verbose_name="Registre actif",
            ),
        ),
    ]
