# Generated by Django 5.0.9 on 2025-02-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0037_commande_affectationanalyste_notification_rapport_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="commande",
        ),
    ]
