# Generated by Django 5.0.9 on 2026-03-03 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0039_alter_historicalregistrecommerce_est_actif_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Commentaire"
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.couleurcommentaire",
                verbose_name="Couleur Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="cotisation",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Commentaire"
            ),
        ),
        migrations.AddField(
            model_name="cotisation",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.couleurcommentaire",
                verbose_name="Couleur Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Commentaire"
            ),
        ),
        migrations.AddField(
            model_name="historicalcertification",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="main.couleurcommentaire",
                verbose_name="Couleur Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="historicalcotisation",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Commentaire"
            ),
        ),
        migrations.AddField(
            model_name="historicalcotisation",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="main.couleurcommentaire",
                verbose_name="Couleur Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="historicalinnovationdeveloppement",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Commentaire"
            ),
        ),
        migrations.AddField(
            model_name="historicalinnovationdeveloppement",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="main.couleurcommentaire",
                verbose_name="Couleur Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="historicalmarque",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Commentaire"
            ),
        ),
        migrations.AddField(
            model_name="historicalmarque",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="main.couleurcommentaire",
                verbose_name="Couleur Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="historicalprocedurecollective",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Commentaire"
            ),
        ),
        migrations.AddField(
            model_name="historicalprocedurecollective",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="main.couleurcommentaire",
                verbose_name="Couleur Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="historicalproduitservice",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Commentaire"
            ),
        ),
        migrations.AddField(
            model_name="historicalproduitservice",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="main.couleurcommentaire",
                verbose_name="Couleur Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="historicalregistrecommerce",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Commentaire"
            ),
        ),
        migrations.AddField(
            model_name="historicalregistrecommerce",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="main.couleurcommentaire",
                verbose_name="Couleur Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="historicalstrategieplanification",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Commentaire"
            ),
        ),
        migrations.AddField(
            model_name="historicalstrategieplanification",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="main.couleurcommentaire",
                verbose_name="Couleur Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="historicalswot",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Commentaire"
            ),
        ),
        migrations.AddField(
            model_name="historicalswot",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="main.couleurcommentaire",
                verbose_name="Couleur Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="innovationdeveloppement",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Commentaire"
            ),
        ),
        migrations.AddField(
            model_name="innovationdeveloppement",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.couleurcommentaire",
                verbose_name="Couleur Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="marque",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Commentaire"
            ),
        ),
        migrations.AddField(
            model_name="marque",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.couleurcommentaire",
                verbose_name="Couleur Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="procedurecollective",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Commentaire"
            ),
        ),
        migrations.AddField(
            model_name="procedurecollective",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.couleurcommentaire",
                verbose_name="Couleur Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="produitservice",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Commentaire"
            ),
        ),
        migrations.AddField(
            model_name="produitservice",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.couleurcommentaire",
                verbose_name="Couleur Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="registrecommerce",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Commentaire"
            ),
        ),
        migrations.AddField(
            model_name="registrecommerce",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.couleurcommentaire",
                verbose_name="Couleur Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="strategieplanification",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Commentaire"
            ),
        ),
        migrations.AddField(
            model_name="strategieplanification",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.couleurcommentaire",
                verbose_name="Couleur Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="swot",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=10000000, verbose_name="Commentaire"
            ),
        ),
        migrations.AddField(
            model_name="swot",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.couleurcommentaire",
                verbose_name="Couleur Commentaire",
            ),
        ),
    ]
