# Generated by Django 5.1.4 on 2025-03-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0039_alerte_documentalerte"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alerte",
            old_name="message",
            new_name="content",
        ),
    ]
