# Generated by Django 5.1.5 on 2026-04-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_certification_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acheteur',
            name='creation_complete',
            field=models.BooleanField(default=False, help_text='Indique si le wizard de création a été complété (4 étapes)', verbose_name='Création complète'),
        ),
        migrations.AddField(
            model_name='historicalacheteur',
            name='creation_complete',
            field=models.BooleanField(default=False, help_text='Indique si le wizard de création a été complété (4 étapes)', verbose_name='Création complète'),
        ),
    ]
