# Generated by Django 5.1.5 on 2026-04-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_acheteur_creation_complete'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ville',
            unique_together={('nom', 'pays')},
        ),
    ]
