# Generated by Django 5.1.5 on 2026-04-19 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_ville_unique_par_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='pays_actif',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Dernier pays sélectionné dans la toolbar — persisté entre les sessions.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.pays', verbose_name='Pays actif (toolbar)'),
        ),
        migrations.AddField(
            model_name='user',
            name='pays_actif',
            field=models.ForeignKey(blank=True, help_text='Dernier pays sélectionné dans la toolbar — persisté entre les sessions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_pays_actif', to='main.pays', verbose_name='Pays actif (toolbar)'),
        ),
    ]
