# Generated by Django 5.1.5 on 2026-05-02 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_user_pays_actif'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaceSpecifique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('activity', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('denomination', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NACE Code (Specific)',
                'verbose_name_plural': 'NACE Codes (Specific)',
                'ordering': ['activity', 'type', 'code'],
                'indexes': [models.Index(fields=['activity', 'type'], name='main_nacesp_activit_371210_idx')],
            },
        ),
        migrations.AddField(
            model_name='acheteur',
            name='nace_specifique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acheteurs', to='main.nacespecifique', verbose_name='NACE Code (Specific)'),
        ),
        migrations.AddField(
            model_name='historicalacheteur',
            name='nace_specifique',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.nacespecifique', verbose_name='NACE Code (Specific)'),
        ),
    ]
