# Generated by Django 5.1.5 on 2026-05-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_nace_specifique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acheteur',
            name='categorie_entreprise',
        ),
        migrations.RemoveField(
            model_name='historicalacheteur',
            name='categorie_entreprise',
        ),
    ]
