# Generated by Django 5.1.4 on 2025-03-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0045_opinioncreditacremac_montant_credit_maximum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opinioncreditacremac",
            name="montant_credit_maximum",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Montant crédit maximum conseillée",
                max_digits=100,
                null=True,
                verbose_name="Capital émis",
            ),
        ),
    ]
