# Generated by Django 5.1.5 on 2026-05-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_remove_categorie_entreprise_acheteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='preferred_language',
            field=models.CharField(blank=True, help_text="Langue de l'interface sélectionnée — persistée entre les sessions.", max_length=10, null=True, verbose_name='Langue préférée'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, help_text="Langue de l'interface sélectionnée — persistée entre les sessions.", max_length=10, null=True, verbose_name='Langue préférée'),
        ),
    ]
