# Generated by Django 5.1.5 on 2025-05-08 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0046_alter_opinioncreditacremac_montant_credit_maximum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotisation",
            name="acheteur",
            field=models.ForeignKey(
                blank=True,
                help_text="Acheteur associé au numéro de sécurité sociale",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cotisations",
                to="main.acheteur",
                verbose_name="Acheteur",
            ),
        ),
        migrations.CreateModel(
            name="AdresseAcheteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adresse", models.TextField(max_length=100, verbose_name="Adresse")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "acheteur",
                    models.ForeignKey(
                        blank=True,
                        help_text="Acheteur associé au téléphone",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="adresses",
                        to="main.acheteur",
                        verbose_name="Acheteur",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="adresses_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="adresses_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Adresse",
                "verbose_name_plural": "Adresses",
            },
        ),
    ]
