# Generated by Django 5.0.9 on 2025-05-20 11:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0047_alter_cotisation_acheteur_adresseacheteur"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElementSurveillance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex: Changement de niveau de scoring, Dissolution de l'entreprise",
                        max_length=255,
                        unique=True,
                        verbose_name="Nom de l'élément de surveillance",
                    ),
                ),
                (
                    "code_interne",
                    models.CharField(
                        help_text="Ex: SCORING_CHANGE, DISSOLUTION_ENTREPRISE",
                        max_length=100,
                        unique=True,
                        verbose_name="Code interne",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        help_text="Ex: Santé Financière et Risque de Crédit, Procédures Collectives",
                        max_length=150,
                        verbose_name="Catégorie de surveillance",
                    ),
                ),
                (
                    "sous_categorie",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Évaluation et Notation, Cessation d'Activité",
                        max_length=150,
                        null=True,
                        verbose_name="Sous-catégorie de surveillance",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description de ce que cet élément surveille.",
                        null=True,
                        verbose_name="Description détaillée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élément de Surveillance",
                "verbose_name_plural": "Éléments de Surveillance",
                "ordering": ["categorie", "sous_categorie", "nom"],
            },
        ),
        migrations.AddField(
            model_name="portefeuille",
            name="frequence_alertes",
            field=models.CharField(
                choices=[
                    ("quotidienne", "Quotidienne"),
                    ("hebdomadaire", "Hebdomadaire"),
                    ("mensuelle", "Mensuelle"),
                ],
                default="quotidienne",
                help_text="Choisissez la fréquence à laquelle vous souhaitez recevoir des alertes.",
                max_length=20,
                verbose_name="Fréquence des Alertes",
            ),
        ),
        migrations.AddField(
            model_name="portefeuille",
            name="elements_surveillance_actifs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Choisissez les événements à surveiller pour ce portefeuille.",
                to="main.elementsurveillance",
                verbose_name="Éléments de surveillance activés",
            ),
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_evenement", models.CharField(max_length=100)),
                (
                    "date_notification",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "portefeuille",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.portefeuille",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal des Notifications",
                "verbose_name_plural": "Journaux des Notifications",
            },
        ),
    ]
