# Generated by Django 5.0.9 on 2025-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0048_elementsurveillance_portefeuille_frequence_alertes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="actif",
            field=models.BooleanField(
                default=False,
                help_text="Indique si la notification a été envoyée.",
                verbose_name="Actif",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description de ce que cet élément surveille.",
                null=True,
                verbose_name="Description détaillée",
            ),
        ),
    ]
