# Generated by Django 5.0.9 on 2025-06-14 09:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("main", "0049_notificationlog_actif_notificationlog_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="portefeuille",
            name="derniere_verification",
            field=models.DateTimeField(
                blank=True,
                help_text="Date de la dernière exécution de la routine de surveillance pour ce portefeuille.",
                null=True,
                verbose_name="Dernière vérification effectuée le",
            ),
        ),
        migrations.CreateModel(
            name="AlerteLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message de l'alerte")),
                (
                    "lu",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si le client a consulté cette alerte.",
                        verbose_name="Lu",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "acheteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.acheteur",
                        verbose_name="Acheteur Concerné",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "element_surveille",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.elementsurveillance",
                        verbose_name="Élément Déclenché",
                    ),
                ),
                (
                    "portefeuille",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.portefeuille",
                        verbose_name="Portefeuille",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte",
                "verbose_name_plural": "Alertes",
                "ordering": ["-date_creation"],
            },
        ),
    ]
