# Generated by Django 5.0.9 on 2025-06-24 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0051_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConformiteReglementation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_conformite",
                    models.CharField(
                        choices=[
                            ("reglementaire", "La conformité réglementaire"),
                            ("sectorielle", "La conformité sectorielle"),
                            ("donnees", "La conformité des données"),
                            ("non_conformite", "Non-conformité aux principes établis"),
                        ],
                        max_length=50,
                        verbose_name="Type de Conformité",
                    ),
                ),
                (
                    "statut",
                    models.BooleanField(default=True, verbose_name="Est Conforme ?"),
                ),
                (
                    "details_non_conformite",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Détails de la Non-conformité (si applicable)",
                    ),
                ),
                (
                    "date_verification",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date de la dernière vérification",
                    ),
                ),
                (
                    "organisme_controle",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Organisme de Contrôle",
                    ),
                ),
                (
                    "commentaires",
                    models.TextField(
                        blank=True, null=True, verbose_name="Commentaires"
                    ),
                ),
                (
                    "acheteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conformites",
                        to="main.acheteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conformité et Réglementation",
                "verbose_name_plural": "Conformités et Réglementations",
            },
        ),
        migrations.CreateModel(
            name="InnovationDeveloppement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_innovation",
                    models.CharField(
                        choices=[
                            (
                                "nouveau_produit_service",
                                "Développement de Nouveau produit ou service",
                            ),
                            (
                                "nouveaux_outils_production",
                                "Acquisition de nouveaux outils de production",
                            ),
                            ("innovation_produit", "L'innovation de produit"),
                            ("innovation_procede", "L'innovation de procédé"),
                            (
                                "innovation_commercialisation",
                                "L'innovation de commercialisation",
                            ),
                            ("innovation_organisation", "L'innovation d'organisation"),
                        ],
                        max_length=50,
                        verbose_name="Type d'Innovation",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Titre de l'Innovation",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description / Commentaires"
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de Début"
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date de Fin (si applicable)",
                    ),
                ),
                (
                    "acheteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="innovations",
                        to="main.acheteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Innovation et Développement",
                "verbose_name_plural": "Innovations et Développements",
            },
        ),
        migrations.CreateModel(
            name="StrategiePlanification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_strategie",
                    models.CharField(
                        choices=[
                            (
                                "specialisation",
                                "La spécialisation (faire une seule activité)",
                            ),
                            (
                                "diversification_liees",
                                "La diversification (activités liées)",
                            ),
                            (
                                "diversification_non_liees",
                                "La diversification (activités non liées)",
                            ),
                            ("integration", "L'intégration (faire tout, seul)"),
                            ("externalisation", "L'externalisation (faire-faire)"),
                            (
                                "planification_strategique",
                                "Planification stratégique (objectifs long terme)",
                            ),
                            (
                                "planification_tactique",
                                "Planification tactique (implémentation stratégies)",
                            ),
                            (
                                "planification_operationnelle",
                                "Planification opérationnelle (détails quotidiens)",
                            ),
                        ],
                        max_length=50,
                        verbose_name="Type de Stratégie",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description / Commentaires"
                    ),
                ),
                (
                    "date_mise_en_place",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de Mise en Place"
                    ),
                ),
                (
                    "acheteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategies",
                        to="main.acheteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stratégie et Planification",
                "verbose_name_plural": "Stratégies et Planifications",
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_certification",
                    models.CharField(
                        choices=[
                            ("management_risque", "Management du risque"),
                            (
                                "securite_information",
                                "Management de la sécurité de l'information",
                            ),
                            (
                                "risk_manager",
                                "Risk Manager & Méthodes d'Appréciation du Risque",
                            ),
                            (
                                "continuite_activite",
                                "Management de la continuité d'activité (SMCA)",
                            ),
                            ("anti_corruption", "Management Anti–Corruption"),
                            ("cybersecurity_manager", "Lead Cybersecurity Manager"),
                            ("qualite", "Management de la Qualité"),
                            (
                                "dpo_rgpd",
                                "DPO : RGPD, Certified Data Protection Officer",
                            ),
                            ("bon_payeur", "Certificat de Bon payeur"),
                            ("autre", "Autre certification"),
                        ],
                        max_length=50,
                        verbose_name="Type de Certification",
                    ),
                ),
                (
                    "nom_certification",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nom Spécifique de la Certification",
                    ),
                ),
                (
                    "date_obtention",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'Obtention"
                    ),
                ),
                (
                    "organisme_delivreur",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Organisme Délivreur",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description / Commentaires"
                    ),
                ),
                (
                    "acheteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="main.acheteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "unique_together": {
                    ("acheteur", "type_certification", "nom_certification")
                },
            },
        ),
    ]
