# Generated by Django 5.0.9 on 2025-06-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0052_conformitereglementation_innovationdeveloppement_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alertelog",
            options={
                "ordering": ["-date_creation"],
                "verbose_name": "Alerte Log",
                "verbose_name_plural": "Alertes Log",
            },
        ),
    ]
