# Generated by Django 5.0.9 on 2025-07-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0053_alter_alertelog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="assets",
            name="semestre",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1er semestre (Janvier - Juin)"),
                    (2, "2e semestre (Juillet - Décembre)"),
                ],
                help_text="Laisser vide si le bilan est annuel.",
                null=True,
                verbose_name="Semestre",
            ),
        ),
    ]
