# Generated by Django 5.0.9 on 2025-07-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0054_assets_semestre"),
    ]

    operations = [
        migrations.AddField(
            model_name="assets",
            name="type_bilan",
            field=models.CharField(
                choices=[
                    ("annuel", "Bilan annuel"),
                    ("semestriel", "Bilan semestriel"),
                ],
                default="annuel",
                help_text="Précise s’il s’agit d’un bilan annuel ou semestriel.",
                max_length=20,
                verbose_name="Type de bilan",
            ),
        ),
    ]
