# Generated by Django 5.0.9 on 2025-07-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0056_liabilities_semestre_liabilities_type_bilan"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenses",
            name="semestre",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1er semestre (Janvier - Juin)"),
                    (2, "2e semestre (Juillet - Décembre)"),
                ],
                help_text="Laisser vide si le bilan est annuel.",
                null=True,
                verbose_name="Semestre",
            ),
        ),
        migrations.AddField(
            model_name="expenses",
            name="type_bilan",
            field=models.CharField(
                choices=[
                    ("annuel", "Bilan annuel"),
                    ("semestriel", "Bilan semestriel"),
                ],
                default="annuel",
                help_text="Précise s’il s’agit d’un bilan annuel ou semestriel.",
                max_length=20,
                verbose_name="Type de bilan",
            ),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="charges_sur_operation_change",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Charges sur opérations de change",
                max_digits=100,
                null=True,
                verbose_name="Charges sur opérations de change",
            ),
        ),
    ]
