# Generated by Django 5.0.9 on 2025-07-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0057_expenses_semestre_expenses_type_bilan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="semestre",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1er semestre (Janvier - Juin)"),
                    (2, "2e semestre (Juillet - Décembre)"),
                ],
                help_text="Laisser vide si le bilan est annuel.",
                null=True,
                verbose_name="Semestre",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="type_bilan",
            field=models.CharField(
                choices=[
                    ("annuel", "Bilan annuel"),
                    ("semestriel", "Bilan semestriel"),
                ],
                default="annuel",
                help_text="Précise s’il s’agit d’un bilan annuel ou semestriel.",
                max_length=20,
                verbose_name="Type de bilan",
            ),
        ),
    ]
