# Generated by Django 5.0.9 on 2025-07-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0059_offbalancesheet_semestre_offbalancesheet_type_bilan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offbalancesheet",
            name="en_faveur_clientele",
        ),
        migrations.RemoveField(
            model_name="offbalancesheet",
            name="en_faveur_des_ets_credit",
        ),
        migrations.RemoveField(
            model_name="offbalancesheet",
            name="engagement_sur_titre",
        ),
        migrations.RemoveField(
            model_name="offbalancesheet",
            name="engagement_sur_titre2",
        ),
        migrations.RemoveField(
            model_name="offbalancesheet",
            name="pour_compte_clientele",
        ),
        migrations.RemoveField(
            model_name="offbalancesheet",
            name="pour_compte_ets_credit",
        ),
        migrations.RemoveField(
            model_name="offbalancesheet",
            name="recu_clientele",
        ),
        migrations.RemoveField(
            model_name="offbalancesheet",
            name="recu_ets_credit",
        ),
        migrations.RemoveField(
            model_name="offbalancesheet",
            name="recu_ets_credit2",
        ),
        migrations.AddField(
            model_name="offbalancesheet",
            name="engagement_financement_donne_clientele",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=100,
                null=True,
                verbose_name="Engagements de financement donnés en faveur de la clientèle",
            ),
        ),
        migrations.AddField(
            model_name="offbalancesheet",
            name="engagement_financement_donne_ets_credit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=100,
                null=True,
                verbose_name="Engagements de financement donnés en faveur des établissements de crédit",
            ),
        ),
        migrations.AddField(
            model_name="offbalancesheet",
            name="engagement_financement_recu_clientele",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=100,
                null=True,
                verbose_name="Engagements de financement reçus de la clientèle",
            ),
        ),
        migrations.AddField(
            model_name="offbalancesheet",
            name="engagement_financement_recu_ets_credit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=100,
                null=True,
                verbose_name="Engagements de financement reçus d'établissements de crédit",
            ),
        ),
        migrations.AddField(
            model_name="offbalancesheet",
            name="engagement_garantie_donne_clientele",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=100,
                null=True,
                verbose_name="Engagements de garantie donnés pour le compte de la clientèle",
            ),
        ),
        migrations.AddField(
            model_name="offbalancesheet",
            name="engagement_garantie_donne_ets_credit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=100,
                null=True,
                verbose_name="Engagements de garantie donnés pour le compte des établissements de crédit",
            ),
        ),
        migrations.AddField(
            model_name="offbalancesheet",
            name="engagement_garantie_recu_ets_credit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=100,
                null=True,
                verbose_name="Engagements de garantie reçus d'établissements de crédit",
            ),
        ),
        migrations.AddField(
            model_name="offbalancesheet",
            name="engagement_sur_titres_donnes",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=100,
                null=True,
                verbose_name="Engagements sur titres donnés",
            ),
        ),
        migrations.AddField(
            model_name="offbalancesheet",
            name="engagement_sur_titres_recus",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=100,
                null=True,
                verbose_name="Engagements sur titres reçus",
            ),
        ),
    ]
