# Generated by Django 5.0.9 on 2025-07-07 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0060_remove_offbalancesheet_en_faveur_clientele_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActifIFRS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_bilan",
                    models.CharField(
                        choices=[
                            ("annuel", "Bilan annuel"),
                            ("semestriel", "Bilan semestriel"),
                        ],
                        default="annuel",
                        max_length=20,
                        verbose_name="Type de bilan",
                    ),
                ),
                (
                    "semestre",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "1er semestre (Janvier - Juin)"),
                            (2, "2e semestre (Juillet - Décembre)"),
                        ],
                        help_text="Laisser vide si le bilan est annuel.",
                        null=True,
                        verbose_name="Semestre",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "caisse_banques_centrales_ccp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Caisse, Banques Centrales et CCP",
                    ),
                ),
                (
                    "actifs_financiers_juste_valeur_par_resultat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Actifs financiers à la juste valeur par résultat",
                    ),
                ),
                (
                    "actifs_financiers_disponibles_vente",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Actifs financiers disponibles à la vente",
                    ),
                ),
                (
                    "actifs_financiers_detenus_jusqu_echeance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Actifs financiers détenus jusqu’à l’échéance",
                    ),
                ),
                (
                    "prets_creances_etablissements_credit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Prêts et créances sur établissements de crédit",
                    ),
                ),
                (
                    "prets_creances_clientele",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Prêts et créances sur la clientèle",
                    ),
                ),
                (
                    "ecart_acquisition",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Écart d’acquisition",
                    ),
                ),
                (
                    "immobilisations_incorporelles",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Immobilisations incorporelles",
                    ),
                ),
                (
                    "immobilisations_corporelles",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Immobilisations corporelles",
                    ),
                ),
                (
                    "immeubles_placement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Immeubles de placement",
                    ),
                ),
                (
                    "actifs_impots_exigibles",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Actifs d’impôts exigibles",
                    ),
                ),
                (
                    "actifs_impots_differes",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Actifs d’impôts différés",
                    ),
                ),
                (
                    "comptes_regularisation_assimiles",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Comptes de régularisation et assimilés",
                    ),
                ),
                (
                    "actifs_non_courants_cedes",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Actifs non courants destinés à être cédés",
                    ),
                ),
                (
                    "acheteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.acheteur",
                        verbose_name="Acheteur",
                    ),
                ),
                (
                    "annee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.annee",
                        verbose_name="Année Civile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Actif IFRS",
                "verbose_name_plural": "Actifs IFRS",
                "ordering": ["-annee", "-semestre"],
                "abstract": False,
                "unique_together": {("acheteur", "annee", "semestre")},
            },
        ),
        migrations.CreateModel(
            name="PassifIFRS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_bilan",
                    models.CharField(
                        choices=[
                            ("annuel", "Bilan annuel"),
                            ("semestriel", "Bilan semestriel"),
                        ],
                        default="annuel",
                        max_length=20,
                        verbose_name="Type de bilan",
                    ),
                ),
                (
                    "semestre",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "1er semestre (Janvier - Juin)"),
                            (2, "2e semestre (Juillet - Décembre)"),
                        ],
                        help_text="Laisser vide si le bilan est annuel.",
                        null=True,
                        verbose_name="Semestre",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "banques_centrales_ccp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Banques centrales et CCP (Passif)",
                    ),
                ),
                (
                    "passifs_financiers_juste_valeur_par_resultat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Passifs financiers à la juste valeur par résultat",
                    ),
                ),
                (
                    "depots_etablissements_credit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Dépôts des établissements de crédit",
                    ),
                ),
                (
                    "depots_clientele",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Dépôts de la clientèle",
                    ),
                ),
                (
                    "dettes_representees_par_titre",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Dettes représentées par un titre",
                    ),
                ),
                (
                    "passifs_impots_exigibles",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Passifs d’impôts exigibles",
                    ),
                ),
                (
                    "passifs_impots_differes",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Passifs d’impôts différés",
                    ),
                ),
                (
                    "comptes_regularisation_assimiles",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Comptes de régularisation et assimilés (Passif)",
                    ),
                ),
                (
                    "provisions",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Provisions",
                    ),
                ),
                (
                    "passifs_lies_actifs_non_courants_cedes",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Passifs liés à des actifs non courants destinés à être cédés",
                    ),
                ),
                (
                    "dettes_subordonnees",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Dettes subordonnées",
                    ),
                ),
                (
                    "capital_emis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Capital émis",
                    ),
                ),
                (
                    "primes_liees_capital",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Primes liées au capital social",
                    ),
                ),
                (
                    "reserves",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Réserves",
                    ),
                ),
                (
                    "ecarts_reevaluation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Écarts de réévaluation",
                    ),
                ),
                (
                    "resultat_net_exercice",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Résultat net de l’exercice",
                    ),
                ),
                (
                    "acheteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.acheteur",
                        verbose_name="Acheteur",
                    ),
                ),
                (
                    "annee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.annee",
                        verbose_name="Année Civile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Passif et Capitaux Propres IFRS",
                "verbose_name_plural": "Passifs et Capitaux Propres IFRS",
                "ordering": ["-annee", "-semestre"],
                "abstract": False,
                "unique_together": {("acheteur", "annee", "semestre")},
            },
        ),
        migrations.CreateModel(
            name="ResultatIFRS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_bilan",
                    models.CharField(
                        choices=[
                            ("annuel", "Bilan annuel"),
                            ("semestriel", "Bilan semestriel"),
                        ],
                        default="annuel",
                        max_length=20,
                        verbose_name="Type de bilan",
                    ),
                ),
                (
                    "semestre",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "1er semestre (Janvier - Juin)"),
                            (2, "2e semestre (Juillet - Décembre)"),
                        ],
                        help_text="Laisser vide si le bilan est annuel.",
                        null=True,
                        verbose_name="Semestre",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "produits_interets_assimiles",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Produits d’intérêts et assimilés",
                    ),
                ),
                (
                    "revenus_titres",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Revenus de titres",
                    ),
                ),
                (
                    "commissions_produits",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Commissions (produits)",
                    ),
                ),
                (
                    "gains_nets_actifs_financiers_jv_resultat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Gains nets sur actifs financiers à la JV par résultat",
                    ),
                ),
                (
                    "gains_nets_actifs_financiers_dispo_vente",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Gains nets sur actifs financiers disponibles à la vente",
                    ),
                ),
                (
                    "gains_nets_change",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Gains nets de change",
                    ),
                ),
                (
                    "autres_produits_exploitation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Autres produits d’exploitation",
                    ),
                ),
                (
                    "charges_interets_assimilees",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Charges d’intérêts et assimilées",
                    ),
                ),
                (
                    "commissions_charges",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Commissions (charges)",
                    ),
                ),
                (
                    "autres_charges_exploitation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Autres charges d’exploitation",
                    ),
                ),
                (
                    "frais_generaux",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Frais généraux",
                    ),
                ),
                (
                    "cout_du_risque",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Coût du risque",
                    ),
                ),
                (
                    "gains_ou_pertes_sur_autres_actifs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Gains ou pertes sur autres actifs",
                    ),
                ),
                (
                    "impots_sur_benefices",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Impôts sur les bénéfices",
                    ),
                ),
                (
                    "resultat_net_activites_non_poursuivies",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Résultat net des activités non poursuivies",
                    ),
                ),
                (
                    "acheteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.acheteur",
                        verbose_name="Acheteur",
                    ),
                ),
                (
                    "annee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.annee",
                        verbose_name="Année Civile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte de Résultat IFRS",
                "verbose_name_plural": "Comptes de Résultat IFRS",
                "ordering": ["-annee", "-semestre"],
                "abstract": False,
                "unique_together": {("acheteur", "annee", "semestre")},
            },
        ),
        migrations.CreateModel(
            name="RatiosIFRS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acheteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.acheteur",
                    ),
                ),
                (
                    "actif",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="main.actififrs",
                    ),
                ),
                (
                    "annee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.annee",
                    ),
                ),
                (
                    "passif",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="main.passififrs",
                    ),
                ),
                (
                    "resultat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="main.resultatifrs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ratio IFRS",
                "verbose_name_plural": "Ratios IFRS",
                "unique_together": {("acheteur", "annee")},
            },
        ),
    ]
