# Generated by Django 5.0.9 on 2025-07-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0061_actififrs_passififrs_resultatifrs_ratiosifrs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actififrs",
            name="actifs_financiers_detenus_jusqu_echeance",
        ),
        migrations.RemoveField(
            model_name="actififrs",
            name="actifs_financiers_disponibles_vente",
        ),
        migrations.RemoveField(
            model_name="actififrs",
            name="actifs_financiers_juste_valeur_par_resultat",
        ),
        migrations.RemoveField(
            model_name="actififrs",
            name="actifs_impots_differes",
        ),
        migrations.RemoveField(
            model_name="actififrs",
            name="actifs_impots_exigibles",
        ),
        migrations.RemoveField(
            model_name="actififrs",
            name="actifs_non_courants_cedes",
        ),
        migrations.RemoveField(
            model_name="actififrs",
            name="caisse_banques_centrales_ccp",
        ),
        migrations.RemoveField(
            model_name="actififrs",
            name="comptes_regularisation_assimiles",
        ),
        migrations.RemoveField(
            model_name="actififrs",
            name="ecart_acquisition",
        ),
        migrations.RemoveField(
            model_name="actififrs",
            name="immeubles_placement",
        ),
        migrations.RemoveField(
            model_name="actififrs",
            name="immobilisations_corporelles",
        ),
        migrations.RemoveField(
            model_name="actififrs",
            name="immobilisations_incorporelles",
        ),
        migrations.RemoveField(
            model_name="actififrs",
            name="prets_creances_clientele",
        ),
        migrations.RemoveField(
            model_name="actififrs",
            name="prets_creances_etablissements_credit",
        ),
        migrations.AddField(
            model_name="actififrs",
            name="autres_immobilisations_incorporelles",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Autres immobilisations incorporelles",
            ),
        ),
        migrations.AddField(
            model_name="actififrs",
            name="avances_et_acomptes",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Avances et acomptes",
            ),
        ),
        migrations.AddField(
            model_name="actififrs",
            name="batiments",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=18, verbose_name="Bâtiments"
            ),
        ),
        migrations.AddField(
            model_name="actififrs",
            name="brevets_et_licences",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Brevets et licences",
            ),
        ),
        migrations.AddField(
            model_name="actififrs",
            name="creances_a_court_terme",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Créances à court terme",
            ),
        ),
        migrations.AddField(
            model_name="actififrs",
            name="creances_diverses",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Créances diverses",
            ),
        ),
        migrations.AddField(
            model_name="actififrs",
            name="disponibilites_bancaires",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Disponibilités bancaires",
            ),
        ),
        migrations.AddField(
            model_name="actififrs",
            name="goodwill",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=18, verbose_name="Goodwill"
            ),
        ),
        migrations.AddField(
            model_name="actififrs",
            name="marques_et_droits_auteur",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Marques et droits d'auteur",
            ),
        ),
        migrations.AddField(
            model_name="actififrs",
            name="materiel_et_equipement",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Matériel et équipement",
            ),
        ),
        migrations.AddField(
            model_name="actififrs",
            name="matieres_premieres",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Matières premières",
            ),
        ),
        migrations.AddField(
            model_name="actififrs",
            name="participations_dans_des_societes",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Participations dans des sociétés",
            ),
        ),
        migrations.AddField(
            model_name="actififrs",
            name="prets_a_long_terme",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Prêts à long terme",
            ),
        ),
        migrations.AddField(
            model_name="actififrs",
            name="produits_finis",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Produits finis",
            ),
        ),
        migrations.AddField(
            model_name="actififrs",
            name="terrains",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=18, verbose_name="Terrains"
            ),
        ),
    ]
