# Generated by Django 5.0.9 on 2025-07-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0062_remove_actififrs_actifs_financiers_detenus_jusqu_echeance_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="passififrs",
            options={
                "ordering": ["-annee", "-semestre"],
                "verbose_name": "Passif IFRS",
                "verbose_name_plural": "Passifs IFRS",
            },
        ),
        migrations.RemoveField(
            model_name="passififrs",
            name="banques_centrales_ccp",
        ),
        migrations.RemoveField(
            model_name="passififrs",
            name="capital_emis",
        ),
        migrations.RemoveField(
            model_name="passififrs",
            name="comptes_regularisation_assimiles",
        ),
        migrations.RemoveField(
            model_name="passififrs",
            name="depots_clientele",
        ),
        migrations.RemoveField(
            model_name="passififrs",
            name="depots_etablissements_credit",
        ),
        migrations.RemoveField(
            model_name="passififrs",
            name="dettes_representees_par_titre",
        ),
        migrations.RemoveField(
            model_name="passififrs",
            name="dettes_subordonnees",
        ),
        migrations.RemoveField(
            model_name="passififrs",
            name="ecarts_reevaluation",
        ),
        migrations.RemoveField(
            model_name="passififrs",
            name="passifs_financiers_juste_valeur_par_resultat",
        ),
        migrations.RemoveField(
            model_name="passififrs",
            name="passifs_impots_differes",
        ),
        migrations.RemoveField(
            model_name="passififrs",
            name="passifs_impots_exigibles",
        ),
        migrations.RemoveField(
            model_name="passififrs",
            name="passifs_lies_actifs_non_courants_cedes",
        ),
        migrations.RemoveField(
            model_name="passififrs",
            name="primes_liees_capital",
        ),
        migrations.RemoveField(
            model_name="passififrs",
            name="provisions",
        ),
        migrations.RemoveField(
            model_name="passififrs",
            name="reserves",
        ),
        migrations.RemoveField(
            model_name="passififrs",
            name="resultat_net_exercice",
        ),
        migrations.AddField(
            model_name="passififrs",
            name="autres_provisions",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Autres provisions",
            ),
        ),
        migrations.AddField(
            model_name="passififrs",
            name="autres_reserves",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Autres réserves",
            ),
        ),
        migrations.AddField(
            model_name="passififrs",
            name="capital_social",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Capital social",
            ),
        ),
        migrations.AddField(
            model_name="passififrs",
            name="cotisations_sociales",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Cotisations sociales",
            ),
        ),
        migrations.AddField(
            model_name="passififrs",
            name="dettes_diverses",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Dettes diverses",
            ),
        ),
        migrations.AddField(
            model_name="passififrs",
            name="dettes_fournisseurs_a_court_terme",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Dettes fournisseurs à court terme",
            ),
        ),
        migrations.AddField(
            model_name="passififrs",
            name="dividendes_a_payer",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Dividendes à payer",
            ),
        ),
        migrations.AddField(
            model_name="passififrs",
            name="emprunts_bancaires_court_terme",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Emprunts bancaires à court terme",
            ),
        ),
        migrations.AddField(
            model_name="passififrs",
            name="emprunts_bancaires_long_terme",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Emprunts bancaires à long terme",
            ),
        ),
        migrations.AddField(
            model_name="passififrs",
            name="impots_sur_le_revenu",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Impôts sur le revenu",
            ),
        ),
        migrations.AddField(
            model_name="passififrs",
            name="obligations",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=18, verbose_name="Obligations"
            ),
        ),
        migrations.AddField(
            model_name="passififrs",
            name="primes_emission",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Primes d'émission",
            ),
        ),
        migrations.AddField(
            model_name="passififrs",
            name="provisions_pour_retraites_et_pensions",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Provisions pour retraites et pensions",
            ),
        ),
        migrations.AddField(
            model_name="passififrs",
            name="reserves_facultatives",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Réserves facultatives",
            ),
        ),
        migrations.AddField(
            model_name="passififrs",
            name="reserves_legales",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Réserves légales",
            ),
        ),
        migrations.AddField(
            model_name="passififrs",
            name="reserves_statutaires",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Réserves statutaires",
            ),
        ),
        migrations.AddField(
            model_name="passififrs",
            name="resultat_net_reporte",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Résultat net reporté",
            ),
        ),
    ]
