# Generated by Django 5.0.9 on 2025-07-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0064_remove_resultatifrs_autres_produits_exploitation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskrating",
            name="cotation_du_risque",
            field=models.CharField(
                blank=True,
                choices=[
                    ("non_douteux", "1. Non douteux"),
                    ("risque_faible", "2. Risque faible"),
                    ("risque_modere", "3. Risque modéré"),
                    ("mise_en_garde", "4. Mise en garde"),
                    ("peu_satisfaisant", "5. Peu satisfaisant"),
                    ("inacceptable", "6. Inacceptable"),
                ],
                max_length=50,
                null=True,
                verbose_name="Cotation du risque",
            ),
        ),
        migrations.AddField(
            model_name="riskrating",
            name="indice_du_risque",
            field=models.CharField(
                blank=True,
                choices=[
                    ("eleve", "1. Élevé"),
                    ("moyen", "2. Moyen"),
                    ("faible", "3. Faible"),
                ],
                max_length=50,
                null=True,
                verbose_name="Indice du risque",
            ),
        ),
    ]
