# Generated by Django 5.0.9 on 2025-08-25 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0065_riskrating_cotation_du_risque_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="Pays",
            field=models.ForeignKey(
                blank=True,
                help_text="Pays où se trouve l'entreprise ou le client.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.pays",
                verbose_name="Pays",
            ),
        ),
        migrations.AddField(
            model_name="offbalancesheet",
            name="deleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="offbalancesheet",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="offbalancesheet",
            name="en_faveur_clientele",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=100,
                null=True,
                verbose_name="Engagements en faveur de la clientèle",
            ),
        ),
        migrations.AddField(
            model_name="offbalancesheet",
            name="en_faveur_des_ets_credit",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=100,
                null=True,
                verbose_name="Engagements en faveur des établissements de crédit",
            ),
        ),
        migrations.AddField(
            model_name="offbalancesheet",
            name="engagement_sur_titre",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=100,
                null=True,
                verbose_name="Anciens engagements sur titres",
            ),
        ),
        migrations.AddField(
            model_name="offbalancesheet",
            name="engagement_sur_titre2",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=100,
                null=True,
                verbose_name="Anciens engagements sur titres (2)",
            ),
        ),
        migrations.AddField(
            model_name="offbalancesheet",
            name="pour_compte_clientele",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=100,
                null=True,
                verbose_name="Engagements pour le compte de la clientèle",
            ),
        ),
        migrations.AddField(
            model_name="offbalancesheet",
            name="pour_compte_ets_credit",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=100,
                null=True,
                verbose_name="Engagements pour le compte des établissements de crédit",
            ),
        ),
        migrations.AddField(
            model_name="offbalancesheet",
            name="recu_clientele",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=100,
                null=True,
                verbose_name="Anciens engagements reçus de la clientèle",
            ),
        ),
        migrations.AddField(
            model_name="offbalancesheet",
            name="recu_ets_credit",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=100,
                null=True,
                verbose_name="Anciens engagements reçus d'établissements de crédit",
            ),
        ),
        migrations.AddField(
            model_name="offbalancesheet",
            name="recu_ets_credit2",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=100,
                null=True,
                verbose_name="Anciens engagements reçus d'établissements de crédit (2)",
            ),
        ),
        migrations.AlterField(
            model_name="procedurecollective",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description détaillée de la procédure collective",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="procedurecollective",
            name="type_procedure",
            field=models.CharField(
                help_text="Type de procédure collective (ex: Redressement judiciaire, Liquidation...)",
                max_length=255,
                verbose_name="Type de procédure",
            ),
        ),
        migrations.AlterField(
            model_name="riskrating",
            name="cotation_du_risque",
            field=models.CharField(
                blank=True,
                choices=[
                    ("non_douteux", "Non douteux"),
                    ("risque_faible", "Risque faible"),
                    ("risque_modere", "Risque modéré"),
                    ("mise_en_garde", "Mise en garde"),
                    ("peu_satisfaisant", "Peu satisfaisant"),
                    ("inacceptable", "Inacceptable"),
                ],
                max_length=50,
                null=True,
                verbose_name="Cotation du risque",
            ),
        ),
        migrations.AlterField(
            model_name="riskrating",
            name="indice_du_risque",
            field=models.CharField(
                blank=True,
                choices=[("eleve", "Élevé"), ("moyen", "Moyen"), ("faible", "Faible")],
                max_length=50,
                null=True,
                verbose_name="Indice du risque",
            ),
        ),
    ]
