# Generated by Django 5.0.9 on 2025-08-25 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0066_commande_pays_offbalancesheet_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="date_envoi_client",
            field=models.DateTimeField(
                blank=True,
                help_text="Date et heure à laquelle le rapport a été envoyé au client.",
                null=True,
                verbose_name="Date d'envoi au client",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="email_envoye",
            field=models.BooleanField(
                default=False,
                help_text="Indique si le rapport a déjà été envoyé au client.",
                verbose_name="Email envoyé au client",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="validateur",
            field=models.ForeignKey(
                blank=True,
                help_text="Utilisateur responsable de la validation de cette commande.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commandes_validees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validateur responsable",
            ),
        ),
    ]
