# Generated by Django 5.0.9 on 2025-08-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0067_commande_date_envoi_client_commande_email_envoye_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commande",
            old_name="Pays",
            new_name="pays",
        ),
    ]
