# Generated by Django 5.0.9 on 2025-09-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0068_rename_pays_commande_pays"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeleAgeSociete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Libellé"
                    ),
                ),
                ("poids", models.FloatField(default=0.0, verbose_name="Poids")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de Création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de Mise à Jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle d'age de société",
                "verbose_name_plural": "Modèles d'age de société",
            },
        ),
        migrations.AddField(
            model_name="categorynacecode",
            name="poids",
            field=models.FloatField(default=0.0, verbose_name="Poids"),
        ),
        migrations.AddField(
            model_name="categorynafcode",
            name="poids",
            field=models.FloatField(default=0.0, verbose_name="Poids"),
        ),
        migrations.AddField(
            model_name="formejuridique",
            name="poids",
            field=models.FloatField(default=0.0, verbose_name="Poids"),
        ),
        migrations.AddField(
            model_name="modeleaviscommercial",
            name="poids",
            field=models.FloatField(default=0.0, verbose_name="Poids"),
        ),
        migrations.AddField(
            model_name="modelebail",
            name="poids",
            field=models.FloatField(default=0.0, verbose_name="Poids"),
        ),
        migrations.AddField(
            model_name="modelecomportementpaiement",
            name="poids",
            field=models.FloatField(default=0.0, verbose_name="Poids"),
        ),
        migrations.AddField(
            model_name="subcategorynacecode",
            name="poids",
            field=models.FloatField(default=0.0, verbose_name="Poids"),
        ),
        migrations.AddField(
            model_name="subcategorynafcode",
            name="poids",
            field=models.FloatField(default=0.0, verbose_name="Poids"),
        ),
    ]
