# Generated by Django 5.0.9 on 2025-11-08 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0069_modeleagesociete_categorynacecode_poids_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeleInterpretationScoringSansBilan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Libellé"
                    ),
                ),
                ("poids", models.FloatField(default=0.0, verbose_name="Poids")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de Création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de Mise à Jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle interpretation scoring sans bilan",
                "verbose_name_plural": "Modèles interpretations scoring sans bilan",
            },
        ),
        migrations.AlterField(
            model_name="riskrating",
            name="indice_du_risque",
            field=models.CharField(
                blank=True,
                choices=[
                    ("eleve", "Élevé"),
                    ("moyen", "Moyen"),
                    ("medium", "Moyen"),
                    ("faible", "Faible"),
                ],
                max_length=50,
                null=True,
                verbose_name="Indice du risque",
            ),
        ),
        migrations.CreateModel(
            name="ScoringSansBilanAcheteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "scoring_value",
                    models.FloatField(
                        default=0.0, verbose_name="Valeur du score de défaillance"
                    ),
                ),
                (
                    "interpretation",
                    models.TextField(
                        blank=True, max_length=10000000, verbose_name="Interprétation"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True, max_length=10000000, verbose_name="Commentaire"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de Création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de Mise à Jour"
                    ),
                ),
                (
                    "acheteur",
                    models.ForeignKey(
                        blank=True,
                        help_text="Acheteur spécifié",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main.acheteur",
                        verbose_name="Acheteur",
                    ),
                ),
                (
                    "age_company_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main.modeleagesociete",
                        verbose_name="Référence sur l'age de l'acheteur",
                    ),
                ),
                (
                    "avis_commercial_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.modeleaviscommercial",
                        verbose_name="Référence Avis Commercial",
                    ),
                ),
                (
                    "categorie_nace_ref",
                    models.ForeignKey(
                        blank=True,
                        help_text="Catégorie Code NACE à laquelle appartient l'acheteur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.categorynacecode",
                        verbose_name="Catégorie Code NACE",
                    ),
                ),
                (
                    "comportement_de_paiement_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main.modelecomportementpaiement",
                        verbose_name="Référence sur les locaux",
                    ),
                ),
                (
                    "forme_juridique",
                    models.ForeignKey(
                        blank=True,
                        help_text="Forme juridique de l'entreprise",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.formejuridique",
                        verbose_name="Forme Juridique",
                    ),
                ),
                (
                    "locaux_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main.modelebail",
                        verbose_name="Référence sur les locaux",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle interpretation scoring sans bilan",
                "verbose_name_plural": "Modèles interpretations scoring sans bilan",
            },
        ),
    ]
