# Generated by Django 5.0.9 on 2025-11-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0070_modeleinterpretationscoringsansbilan_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scoringsansbilanacheteur",
            name="categorie_nace_ref",
        ),
        migrations.AddField(
            model_name="scoringsansbilanacheteur",
            name="categories_nace_ref",
            field=models.ManyToManyField(
                blank=True,
                help_text="Catégories Code NACE auxquelles appartient l'acheteur",
                to="main.categorynacecode",
                verbose_name="Catégories Code NACE",
            ),
        ),
    ]
