# Generated by Django 5.0.9 on 2025-11-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0071_remove_scoringsansbilanacheteur_categorie_nace_ref_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoringsansbilanacheteur",
            name="libelle",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Libellé"
            ),
        ),
    ]
