# Generated by Django 5.0.9 on 2025-12-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0073_adminmails_acheteur_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmailinfo",
            name="cc_emails",
            field=models.TextField(blank=True, null=True, verbose_name="Emails en CC"),
        ),
        migrations.AddField(
            model_name="historicalmailinfo",
            name="custom_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Nombre de jours personnalisé"
            ),
        ),
        migrations.AddField(
            model_name="historicalmailinfo",
            name="formats_generes",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Formats générés"
            ),
        ),
        migrations.AddField(
            model_name="historicalmailinfo",
            name="subject",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Sujet"
            ),
        ),
        migrations.AddField(
            model_name="mailinfo",
            name="cc_emails",
            field=models.TextField(blank=True, null=True, verbose_name="Emails en CC"),
        ),
        migrations.AddField(
            model_name="mailinfo",
            name="custom_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Nombre de jours personnalisé"
            ),
        ),
        migrations.AddField(
            model_name="mailinfo",
            name="formats_generes",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Formats générés"
            ),
        ),
        migrations.AddField(
            model_name="mailinfo",
            name="subject",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Sujet"
            ),
        ),
    ]
