# Generated by Django 5.0.9 on 2025-12-16 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0074_historicalmailinfo_cc_emails_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donneesenregistrement",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.couleurcommentaire",
                verbose_name="Couleur Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="donneesenregistrement",
            name="nom_anterieur",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nom antérieur"
            ),
        ),
        migrations.AddField(
            model_name="historicaldonneesenregistrement",
            name="couleur_commentaire",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="main.couleurcommentaire",
                verbose_name="Couleur Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="historicaldonneesenregistrement",
            name="nom_anterieur",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nom antérieur"
            ),
        ),
        migrations.AddField(
            model_name="historicaltendance",
            name="alarmes",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Risque d'insolvabilité", "Risque d'insolvabilité"),
                    (
                        "Une procédure préliminaire a été demandée",
                        "Demande de composition juridique",
                    ),
                    (
                        "Une procédure prématurée a été suspendue",
                        "Une procédure prématurée a été suspendue",
                    ),
                    (
                        "La composition du tribunal à la suite d'un examen préliminaire",
                        "La composition du tribunal à la suite d'un examen préliminaire",
                    ),
                    (
                        "Ouverture de la composition judiciaire",
                        "Ouverture de la composition judiciaire",
                    ),
                    (
                        "Refus de l'homologation, la corruption est attendue",
                        "Refus de l'homologation, la corruption est attendue",
                    ),
                ],
                max_length=100,
                verbose_name="Alarmes",
            ),
        ),
        migrations.AddField(
            model_name="historicaltendance",
            name="plus_informations",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "L'entreprise demandée est considérée comme une grande entreprise",
                        "L'entreprise demandée est considérée comme une grande entreprise",
                    ),
                    (
                        "L'entreprise demandée est considérée comme une entreprise de taille moyenne",
                        "L'entreprise demandée est considérée comme une entreprise de taille moyenne",
                    ),
                    (
                        "L'entreprise demandée est considérée comme une petite entreprise",
                        "L'entreprise demandée est considérée comme une petite entreprise",
                    ),
                    ("Inconnu de nos sources", "Inconnu de nos sources"),
                ],
                max_length=100,
                verbose_name="Plus d'informations sur la notation",
            ),
        ),
        migrations.AddField(
            model_name="tendance",
            name="alarmes",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Risque d'insolvabilité", "Risque d'insolvabilité"),
                    (
                        "Une procédure préliminaire a été demandée",
                        "Demande de composition juridique",
                    ),
                    (
                        "Une procédure prématurée a été suspendue",
                        "Une procédure prématurée a été suspendue",
                    ),
                    (
                        "La composition du tribunal à la suite d'un examen préliminaire",
                        "La composition du tribunal à la suite d'un examen préliminaire",
                    ),
                    (
                        "Ouverture de la composition judiciaire",
                        "Ouverture de la composition judiciaire",
                    ),
                    (
                        "Refus de l'homologation, la corruption est attendue",
                        "Refus de l'homologation, la corruption est attendue",
                    ),
                ],
                max_length=100,
                verbose_name="Alarmes",
            ),
        ),
        migrations.AddField(
            model_name="tendance",
            name="plus_informations",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "L'entreprise demandée est considérée comme une grande entreprise",
                        "L'entreprise demandée est considérée comme une grande entreprise",
                    ),
                    (
                        "L'entreprise demandée est considérée comme une entreprise de taille moyenne",
                        "L'entreprise demandée est considérée comme une entreprise de taille moyenne",
                    ),
                    (
                        "L'entreprise demandée est considérée comme une petite entreprise",
                        "L'entreprise demandée est considérée comme une petite entreprise",
                    ),
                    ("Inconnu de nos sources", "Inconnu de nos sources"),
                ],
                max_length=100,
                verbose_name="Plus d'informations sur la notation",
            ),
        ),
        migrations.AlterField(
            model_name="comptefinancier",
            name="devise",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XAF", "XAF"),
                    ("XOF", "XOF"),
                    ("EUR", "EUR"),
                    ("USD", "USD"),
                    ("CHF", "CHF"),
                    ("GNF", "GNF"),
                    ("GHS", "GHS"),
                    ("MRU", "MRU"),
                    ("ZAR", "ZAR"),
                    ("DZD", "DZD"),
                    ("MAD", "MAD"),
                    ("TND", "TND"),
                    ("LYD", "LYD"),
                    ("SDG", "SDG"),
                    ("NGN", "NGN"),
                    ("KES", "KES"),
                    ("TZS", "TZS"),
                    ("UGX", "UGX"),
                    ("ETB", "ETB"),
                    ("EGP", "EGP"),
                    ("AOA", "AOA"),
                    ("MWK", "MWK"),
                    ("ZMW", "ZMW"),
                    ("BWP", "BWP"),
                ],
                default="XAF",
                max_length=20,
                verbose_name="Devise",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomptefinancier",
            name="devise",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XAF", "XAF"),
                    ("XOF", "XOF"),
                    ("EUR", "EUR"),
                    ("USD", "USD"),
                    ("CHF", "CHF"),
                    ("GNF", "GNF"),
                    ("GHS", "GHS"),
                    ("MRU", "MRU"),
                    ("ZAR", "ZAR"),
                    ("DZD", "DZD"),
                    ("MAD", "MAD"),
                    ("TND", "TND"),
                    ("LYD", "LYD"),
                    ("SDG", "SDG"),
                    ("NGN", "NGN"),
                    ("KES", "KES"),
                    ("TZS", "TZS"),
                    ("UGX", "UGX"),
                    ("ETB", "ETB"),
                    ("EGP", "EGP"),
                    ("AOA", "AOA"),
                    ("MWK", "MWK"),
                    ("ZMW", "ZMW"),
                    ("BWP", "BWP"),
                ],
                default="XAF",
                max_length=20,
                verbose_name="Devise",
            ),
        ),
    ]
