# Generated by Django 5.0.9 on 2025-12-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0075_donneesenregistrement_couleur_commentaire_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password_changed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date de la dernière modification du mot de passe.",
                null=True,
                verbose_name="password changed at",
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="password_changed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date de la dernière modification du mot de passe.",
                null=True,
                verbose_name="password changed at",
            ),
        ),
    ]
