# Generated by Django 5.0.9 on 2025-12-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0078_alter_historicalresume_capital_social_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalresume",
            name="capital_social",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Capital social de l'acheteur.",
                max_digits=100,
                null=True,
                verbose_name="Capital social",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresume",
            name="capitaux_propre",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Capitaux propres de l'acheteur.",
                max_digits=100,
                null=True,
                verbose_name="Capitaux propres",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresume",
            name="chiffre_affaire",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Chiffre d'affaire annuel de l'acheteur.",
                max_digits=100,
                null=True,
                verbose_name="Chiffre d'affaire",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresume",
            name="nombre_employe",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Nombre total d'employés dans l'entreprise.",
                max_digits=100,
                null=True,
                verbose_name="Nombre d'employés",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresume",
            name="resultat_net",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Résultat net après impôts.",
                max_digits=100,
                null=True,
                verbose_name="Résultat net",
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="capital_social",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Capital social de l'acheteur.",
                max_digits=100,
                null=True,
                verbose_name="Capital social",
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="capitaux_propre",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Capitaux propres de l'acheteur.",
                max_digits=100,
                null=True,
                verbose_name="Capitaux propres",
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="chiffre_affaire",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Chiffre d'affaire annuel de l'acheteur.",
                max_digits=100,
                null=True,
                verbose_name="Chiffre d'affaire",
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="nombre_employe",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Nombre total d'employés dans l'entreprise.",
                max_digits=100,
                null=True,
                verbose_name="Nombre d'employés",
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="resultat_net",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Résultat net après impôts.",
                max_digits=100,
                null=True,
                verbose_name="Résultat net",
            ),
        ),
    ]
