# Generated by Django 5.0.9 on 2025-12-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0079_alter_historicalresume_capital_social_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalriskrating",
            name="indice_du_risque",
            field=models.CharField(
                blank=True,
                choices=[
                    ("eleve", "Élevé"),
                    ("moyen", "Moyen"),
                    ("medium", "Medium"),
                    ("faible", "Faible"),
                ],
                max_length=50,
                null=True,
                verbose_name="Indice du risque",
            ),
        ),
        migrations.AlterField(
            model_name="riskrating",
            name="indice_du_risque",
            field=models.CharField(
                blank=True,
                choices=[
                    ("eleve", "Élevé"),
                    ("moyen", "Moyen"),
                    ("medium", "Medium"),
                    ("faible", "Faible"),
                ],
                max_length=50,
                null=True,
                verbose_name="Indice du risque",
            ),
        ),
    ]
