# Generated by Django 5.0.9 on 2025-12-23 10:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0080_alter_historicalriskrating_indice_du_risque_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="antecedantsjuridique",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Antécédent Juridique",
                "verbose_name_plural": "Antécédents Juridiques",
            },
        ),
        migrations.AlterModelOptions(
            name="responsableacheteur",
            options={
                "ordering": ["nom", "prenom"],
                "verbose_name": "Responsable Acheteur",
                "verbose_name_plural": "Responsables Acheteurs",
            },
        ),
        migrations.AlterField(
            model_name="compositionaction",
            name="pourcentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Pourcentage de détention (0-100) avec 2 décimales max",
                max_digits=100,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="Pourcentage",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcompositionaction",
            name="pourcentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Pourcentage de détention (0-100) avec 2 décimales max",
                max_digits=100,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="Pourcentage",
            ),
        ),
        migrations.AddIndex(
            model_name="responsableacheteur",
            index=models.Index(
                fields=["acheteur", "nom", "prenom"],
                name="main_respon_acheteu_968fdd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="responsableacheteur",
            index=models.Index(fields=["poste"], name="main_respon_poste_d5b9db_idx"),
        ),
        migrations.AddIndex(
            model_name="responsableacheteur",
            index=models.Index(fields=["sexe"], name="main_respon_sexe_606e88_idx"),
        ),
    ]
