# Generated by Django 5.0.9 on 2025-12-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0081_alter_antecedantsjuridique_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListeComportementsPaiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("libelle", models.TextField(max_length=255, verbose_name="libelle")),
                ("couleur", models.CharField(max_length=10, verbose_name="couleur")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ListeConditionAchat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="nom")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ListeConditionVente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="nom")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ListeImportation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("libelle", models.TextField(max_length=2000, verbose_name="nom")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ListeInformationsAvisCommercial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("libelle", models.TextField(max_length=255, verbose_name="libelle")),
                ("couleur", models.CharField(max_length=20, verbose_name="couleur")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ListeInformationsRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("libelle", models.TextField(max_length=255, verbose_name="libelle")),
                ("couleur", models.CharField(max_length=10, verbose_name="couleur")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Locaux",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="nom")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="advice",
            name="risque_potentiel_court_terme",
            field=models.TextField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Risques potentiel à court terme",
            ),
        ),
        migrations.AddField(
            model_name="geopolitics",
            name="efficacite",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Efficacité"
            ),
        ),
        migrations.AddField(
            model_name="geopolitics",
            name="etat_droit",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Etat de droit"
            ),
        ),
        migrations.AddField(
            model_name="geopolitics",
            name="liberte_expression",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Liberté d'expression"
            ),
        ),
        migrations.AddField(
            model_name="geopolitics",
            name="qualite",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                verbose_name="Qualité réglementaire",
            ),
        ),
        migrations.AddField(
            model_name="geopolitics",
            name="stabilite_politique",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Stabilité politique"
            ),
        ),
        migrations.AddField(
            model_name="historicaladvice",
            name="risque_potentiel_court_terme",
            field=models.TextField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Risques potentiel à court terme",
            ),
        ),
        migrations.AddField(
            model_name="historicalgeopolitics",
            name="efficacite",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Efficacité"
            ),
        ),
        migrations.AddField(
            model_name="historicalgeopolitics",
            name="etat_droit",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Etat de droit"
            ),
        ),
        migrations.AddField(
            model_name="historicalgeopolitics",
            name="liberte_expression",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Liberté d'expression"
            ),
        ),
        migrations.AddField(
            model_name="historicalgeopolitics",
            name="qualite",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                verbose_name="Qualité réglementaire",
            ),
        ),
        migrations.AddField(
            model_name="historicalgeopolitics",
            name="stabilite_politique",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Stabilité politique"
            ),
        ),
        migrations.AlterField(
            model_name="advice",
            name="dynamisme_long_terme",
            field=models.TextField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Dynamisme à long terme",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladvice",
            name="dynamisme_long_terme",
            field=models.TextField(
                blank=True,
                max_length=10000000,
                null=True,
                verbose_name="Dynamisme à long terme",
            ),
        ),
    ]
