# Generated by Django 5.0.9 on 2025-12-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0082_listecomportementspaiement_listeconditionachat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geopolitics",
            name="stabilite_politique",
        ),
        migrations.RemoveField(
            model_name="historicalgeopolitics",
            name="stabilite_politique",
        ),
        migrations.AddField(
            model_name="geopolitics",
            name="tabilite_politique",
            field=models.CharField(
                blank=True,
                help_text="Score de 0 à 10: 0=Très instable, 5=Moyen, 10=Très stable",
                max_length=4,
                null=True,
                verbose_name="Stabilité politique",
            ),
        ),
        migrations.AddField(
            model_name="historicalgeopolitics",
            name="tabilite_politique",
            field=models.CharField(
                blank=True,
                help_text="Score de 0 à 10: 0=Très instable, 5=Moyen, 10=Très stable",
                max_length=4,
                null=True,
                verbose_name="Stabilité politique",
            ),
        ),
        migrations.AlterField(
            model_name="geopolitics",
            name="efficacite",
            field=models.CharField(
                blank=True,
                help_text="Score de 0 à 10: 0=Très inefficace, 5=Moyen, 10=Très efficace",
                max_length=4,
                null=True,
                verbose_name="Efficacité gouvernementale",
            ),
        ),
        migrations.AlterField(
            model_name="geopolitics",
            name="etat_droit",
            field=models.CharField(
                blank=True,
                help_text="Score de 0 à 10: 0=Faible, 5=Moyen, 10=Forte application de la loi",
                max_length=4,
                null=True,
                verbose_name="Etat de droit",
            ),
        ),
        migrations.AlterField(
            model_name="geopolitics",
            name="liberte_expression",
            field=models.CharField(
                blank=True,
                help_text="Score de 0 à 10: 0=Très restrictive, 5=Moyenne, 10=Très libre",
                max_length=4,
                null=True,
                verbose_name="Liberté d'expression",
            ),
        ),
        migrations.AlterField(
            model_name="geopolitics",
            name="qualite",
            field=models.CharField(
                blank=True,
                help_text="Score de 0 à 10: 0=Mauvaise, 5=Moyenne, 10=Excellente réglementation",
                max_length=4,
                null=True,
                verbose_name="Qualité réglementaire",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgeopolitics",
            name="efficacite",
            field=models.CharField(
                blank=True,
                help_text="Score de 0 à 10: 0=Très inefficace, 5=Moyen, 10=Très efficace",
                max_length=4,
                null=True,
                verbose_name="Efficacité gouvernementale",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgeopolitics",
            name="etat_droit",
            field=models.CharField(
                blank=True,
                help_text="Score de 0 à 10: 0=Faible, 5=Moyen, 10=Forte application de la loi",
                max_length=4,
                null=True,
                verbose_name="Etat de droit",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgeopolitics",
            name="liberte_expression",
            field=models.CharField(
                blank=True,
                help_text="Score de 0 à 10: 0=Très restrictive, 5=Moyenne, 10=Très libre",
                max_length=4,
                null=True,
                verbose_name="Liberté d'expression",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgeopolitics",
            name="qualite",
            field=models.CharField(
                blank=True,
                help_text="Score de 0 à 10: 0=Mauvaise, 5=Moyenne, 10=Excellente réglementation",
                max_length=4,
                null=True,
                verbose_name="Qualité réglementaire",
            ),
        ),
    ]
