# Generated by Django 5.0.9 on 2025-12-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0083_remove_geopolitics_stabilite_politique_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="geopolitics",
            old_name="tabilite_politique",
            new_name="stabilite_politique",
        ),
        migrations.RenameField(
            model_name="historicalgeopolitics",
            old_name="tabilite_politique",
            new_name="stabilite_politique",
        ),
    ]
