# Generated by Django 5.0.9 on 2025-12-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0084_rename_tabilite_politique_geopolitics_stabilite_politique_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comptefinancier",
            name="type_bilan_ref",
        ),
        migrations.RemoveField(
            model_name="conditiondevente",
            name="comportement_de_paiement_ref",
        ),
        migrations.RemoveField(
            model_name="conditiondevente",
            name="recouvrement_de_dette_jugement_ref",
        ),
        migrations.RemoveField(
            model_name="historicalcomptefinancier",
            name="type_bilan_ref",
        ),
        migrations.RemoveField(
            model_name="historicalconditionachat",
            name="importation",
        ),
        migrations.RemoveField(
            model_name="historicalconditionachat",
            name="local",
        ),
        migrations.RemoveField(
            model_name="historicalconditiondevente",
            name="comportement_de_paiement_ref",
        ),
        migrations.RemoveField(
            model_name="historicalconditiondevente",
            name="local",
        ),
        migrations.RemoveField(
            model_name="historicalconditiondevente",
            name="recouvrement_de_dette_jugement_ref",
        ),
        migrations.RemoveField(
            model_name="historicalproprieteetactif",
            name="locaux",
        ),
        migrations.RemoveField(
            model_name="historicalproprieteetactif",
            name="locaux_ref",
        ),
        migrations.RemoveField(
            model_name="proprieteetactif",
            name="locaux_ref",
        ),
        migrations.AlterField(
            model_name="comptefinancier",
            name="credibilite_cabinet",
            field=models.CharField(
                blank=True,
                choices=[("OUI", "Oui"), ("NON", "Non")],
                max_length=200,
                verbose_name="Crédibilité du cabinet pour ACREMAC",
            ),
        ),
        migrations.RemoveField(
            model_name="conditionachat",
            name="importation",
        ),
        migrations.RemoveField(
            model_name="conditionachat",
            name="local",
        ),
        migrations.RemoveField(
            model_name="conditiondevente",
            name="local",
        ),
        migrations.AlterField(
            model_name="conditiondevente",
            name="recouvrement_de_dette_jugement",
            field=models.CharField(
                choices=[
                    (
                        "Aucune information négative n'a été trouvée",
                        "Aucune information négative n'a été trouvée",
                    ),
                    (
                        "Il n'existe aucune trace d'une quelconque action de recouvrement de créances par ACREMAC à l'encontre de cette entreprise",
                        "Il n'existe aucune trace d'une quelconque action de recouvrement de créances par ACREMAC à l'encontre de cette entreprise",
                    ),
                    (
                        "Selon nos sources, l'entreprise n'est pas en situation d'insolvabilité/procédure préliminaire/procédure de répartition des dettes",
                        "Selon nos sources, l'entreprise n'est pas en situation d'insolvabilité/procédure préliminaire/procédure de répartition des dettes",
                    ),
                    (
                        "Des actions en recouvrement judiciaire sont ouvertes contre l'acheteur",
                        "Des actions en recouvrement judiciaire sont ouvertes contre l'acheteur",
                    ),
                    (
                        "Des actions de recouvrement à l'amiable sont ouvertes contre l'acheteur",
                        "Des actions de recouvrement à l'amiable sont ouvertes contre l'acheteur",
                    ),
                    (
                        "Des cas de recouvrement fermés existent chez nos sources sur l'acheteur",
                        "Des cas de recouvrement fermés existent chez nos sources sur l'acheteur",
                    ),
                    ("Inconnu de nos sources", "Inconnu de nos sources"),
                ],
                default="--------",
                max_length=255,
                verbose_name="Recouvrement de dette jugement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomptefinancier",
            name="credibilite_cabinet",
            field=models.CharField(
                blank=True,
                choices=[("OUI", "Oui"), ("NON", "Non")],
                max_length=200,
                verbose_name="Crédibilité du cabinet pour ACREMAC",
            ),
        ),
        migrations.AlterField(
            model_name="historicalconditiondevente",
            name="recouvrement_de_dette_jugement",
            field=models.CharField(
                choices=[
                    (
                        "Aucune information négative n'a été trouvée",
                        "Aucune information négative n'a été trouvée",
                    ),
                    (
                        "Il n'existe aucune trace d'une quelconque action de recouvrement de créances par ACREMAC à l'encontre de cette entreprise",
                        "Il n'existe aucune trace d'une quelconque action de recouvrement de créances par ACREMAC à l'encontre de cette entreprise",
                    ),
                    (
                        "Selon nos sources, l'entreprise n'est pas en situation d'insolvabilité/procédure préliminaire/procédure de répartition des dettes",
                        "Selon nos sources, l'entreprise n'est pas en situation d'insolvabilité/procédure préliminaire/procédure de répartition des dettes",
                    ),
                    (
                        "Des actions en recouvrement judiciaire sont ouvertes contre l'acheteur",
                        "Des actions en recouvrement judiciaire sont ouvertes contre l'acheteur",
                    ),
                    (
                        "Des actions de recouvrement à l'amiable sont ouvertes contre l'acheteur",
                        "Des actions de recouvrement à l'amiable sont ouvertes contre l'acheteur",
                    ),
                    (
                        "Des cas de recouvrement fermés existent chez nos sources sur l'acheteur",
                        "Des cas de recouvrement fermés existent chez nos sources sur l'acheteur",
                    ),
                    ("Inconnu de nos sources", "Inconnu de nos sources"),
                ],
                default="--------",
                max_length=255,
                verbose_name="Recouvrement de dette jugement",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltendance",
            name="plus_informations",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "40 Cette société est une filiale d'un groupe",
                        "40 Cette société est une filiale d'un groupe",
                    ),
                    (
                        "35 Cette société est une société autonome",
                        "35 Cette société est une société autonome",
                    ),
                    (
                        "30 En raison de ses liens avec le groupe, elle est considérée comme une filiale indépendante",
                        "30 En raison de ses liens avec le groupe, elle est considérée comme une filiale indépendante",
                    ),
                    (
                        "25 Cette entreprise est considérée comme une grande entreprise",
                        "25 Cette entreprise est considérée comme une grande entreprise",
                    ),
                    (
                        "20 Cette entreprise est considérée comme une entreprise de taille moyenne",
                        "20 Cette entreprise est considérée comme une entreprise de taille moyenne",
                    ),
                    (
                        "15 Cette entreprise est considérée comme une petite entreprise",
                        "15 Cette entreprise est considérée comme une petite entreprise",
                    ),
                    ("10 Inconnu de nos sources", "10 Inconnu de nos sources"),
                ],
                max_length=100,
                verbose_name="Plus d'informations sur la notation",
            ),
        ),
        migrations.RemoveField(
            model_name="proprieteetactif",
            name="locaux",
        ),
        migrations.AlterField(
            model_name="tendance",
            name="plus_informations",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "40 Cette société est une filiale d'un groupe",
                        "40 Cette société est une filiale d'un groupe",
                    ),
                    (
                        "35 Cette société est une société autonome",
                        "35 Cette société est une société autonome",
                    ),
                    (
                        "30 En raison de ses liens avec le groupe, elle est considérée comme une filiale indépendante",
                        "30 En raison de ses liens avec le groupe, elle est considérée comme une filiale indépendante",
                    ),
                    (
                        "25 Cette entreprise est considérée comme une grande entreprise",
                        "25 Cette entreprise est considérée comme une grande entreprise",
                    ),
                    (
                        "20 Cette entreprise est considérée comme une entreprise de taille moyenne",
                        "20 Cette entreprise est considérée comme une entreprise de taille moyenne",
                    ),
                    (
                        "15 Cette entreprise est considérée comme une petite entreprise",
                        "15 Cette entreprise est considérée comme une petite entreprise",
                    ),
                    ("10 Inconnu de nos sources", "10 Inconnu de nos sources"),
                ],
                max_length=100,
                verbose_name="Plus d'informations sur la notation",
            ),
        ),
        migrations.AddField(
            model_name="conditionachat",
            name="importation",
            field=models.ManyToManyField(
                blank=True, related_name="importation", to="main.listeconditionachat"
            ),
        ),
        migrations.AddField(
            model_name="conditionachat",
            name="local",
            field=models.ManyToManyField(
                blank=True, related_name="local", to="main.listeconditionachat"
            ),
        ),
        migrations.AddField(
            model_name="conditiondevente",
            name="local",
            field=models.ManyToManyField(
                blank=True, related_name="local", to="main.listeconditionvente"
            ),
        ),
        migrations.AddField(
            model_name="proprieteetactif",
            name="locaux",
            field=models.ManyToManyField(
                blank=True, related_name="Locaux", to="main.locaux"
            ),
        ),
    ]
