# Generated by Django 5.0.9 on 2025-12-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0085_remove_comptefinancier_type_bilan_ref_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalportableacheteur",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Portable d'Acheteur",
                "verbose_name_plural": "historical Portables d'Acheteurs",
            },
        ),
        migrations.AlterModelOptions(
            name="portableacheteur",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Portable d'Acheteur",
                "verbose_name_plural": "Portables d'Acheteurs",
            },
        ),
        migrations.RemoveField(
            model_name="historicaloperationethistorique",
            name="importation",
        ),
        migrations.AlterField(
            model_name="historicalportableacheteur",
            name="portable",
            field=models.TextField(
                help_text="Format: +241 XX XX XX XX ou 0X XX XX XX",
                max_length=100,
                verbose_name="Numéro portable",
            ),
        ),
        migrations.RemoveField(
            model_name="operationethistorique",
            name="importation",
        ),
        migrations.AlterField(
            model_name="portableacheteur",
            name="portable",
            field=models.TextField(
                help_text="Format: +241 XX XX XX XX ou 0X XX XX XX",
                max_length=100,
                verbose_name="Numéro portable",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="portableacheteur",
            unique_together={("acheteur", "portable")},
        ),
        migrations.AddIndex(
            model_name="portableacheteur",
            index=models.Index(
                fields=["acheteur"], name="main_portab_acheteu_60e9f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portableacheteur",
            index=models.Index(
                fields=["created_at"], name="main_portab_created_2cb042_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portableacheteur",
            index=models.Index(
                fields=["portable"], name="main_portab_portabl_579594_idx"
            ),
        ),
        migrations.AddField(
            model_name="operationethistorique",
            name="importation",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="importation",
                to="main.listeimportation",
            ),
        ),
    ]
