# Generated by Django 5.0.9 on 2025-12-29 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0086_alter_historicalportableacheteur_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listecomportementspaiement",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="listecomportementspaiement",
            name="deleted_by_cascade",
        ),
        migrations.RemoveField(
            model_name="listeconditionachat",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="listeconditionachat",
            name="deleted_by_cascade",
        ),
        migrations.RemoveField(
            model_name="listeconditionvente",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="listeconditionvente",
            name="deleted_by_cascade",
        ),
        migrations.RemoveField(
            model_name="listeimportation",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="listeimportation",
            name="deleted_by_cascade",
        ),
        migrations.RemoveField(
            model_name="listeinformationsaviscommercial",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="listeinformationsaviscommercial",
            name="deleted_by_cascade",
        ),
        migrations.RemoveField(
            model_name="listeinformationsrating",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="listeinformationsrating",
            name="deleted_by_cascade",
        ),
        migrations.RemoveField(
            model_name="locaux",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="locaux",
            name="deleted_by_cascade",
        ),
        migrations.AddField(
            model_name="historicalproprieteetactif",
            name="locaux_ref",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="main.modelebail",
                verbose_name="Référence sur les locaux",
            ),
        ),
        migrations.AddField(
            model_name="proprieteetactif",
            name="locaux_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.modelebail",
                verbose_name="Référence sur les locaux",
            ),
        ),
    ]
