# Generated by Django 5.0.9 on 2025-12-29 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0087_remove_listecomportementspaiement_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comptefinancier",
            name="type_bilan_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.modelebilan",
                verbose_name="Référence Type de bilan",
            ),
        ),
        migrations.AddField(
            model_name="historicalcomptefinancier",
            name="type_bilan_ref",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="main.modelebilan",
                verbose_name="Référence Type de bilan",
            ),
        ),
    ]
