# Generated by Django 5.0.9 on 2025-12-29 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0088_comptefinancier_type_bilan_ref_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditiondevente",
            name="comportement_de_paiement_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.modelecomportementpaiement",
                verbose_name="Référence sur les locaux",
            ),
        ),
        migrations.AddField(
            model_name="conditiondevente",
            name="recouvrement_de_dette_jugement_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.modelecomportementjugement",
                verbose_name="Référence sur les locaux",
            ),
        ),
        migrations.AddField(
            model_name="historicalconditiondevente",
            name="comportement_de_paiement_ref",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="main.modelecomportementpaiement",
                verbose_name="Référence sur les locaux",
            ),
        ),
        migrations.AddField(
            model_name="historicalconditiondevente",
            name="recouvrement_de_dette_jugement_ref",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="main.modelecomportementjugement",
                verbose_name="Référence sur les locaux",
            ),
        ),
    ]
