# Generated by Django 5.0.9 on 2026-01-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0089_conditiondevente_comportement_de_paiement_ref_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprocedurecollective",
            name="impact_assureur",
            field=models.TextField(
                blank=True,
                help_text="Résumé de l’impact et des mesures prises par l’assureur crédit",
                null=True,
                verbose_name="Impact pour l’assureur crédit",
            ),
        ),
        migrations.AddField(
            model_name="historicalprocedurecollective",
            name="montant_creance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Montant en FCFA",
                max_digits=15,
                null=True,
                verbose_name="Montant total des créances déclarées",
            ),
        ),
        migrations.AddField(
            model_name="historicalprocedurecollective",
            name="numero_dossier",
            field=models.CharField(
                blank=True,
                help_text="Référence officielle du dossier",
                max_length=100,
                null=True,
                verbose_name="Numéro de dossier",
            ),
        ),
        migrations.AddField(
            model_name="historicalprocedurecollective",
            name="secteur_activite",
            field=models.CharField(
                blank=True,
                help_text="Secteur d'activité de l'entreprise concernée",
                max_length=255,
                null=True,
                verbose_name="Secteur d'activité",
            ),
        ),
        migrations.AddField(
            model_name="historicalprocedurecollective",
            name="tribunal",
            field=models.CharField(
                blank=True,
                help_text="Nom du tribunal compétent",
                max_length=255,
                null=True,
                verbose_name="Tribunal compétent",
            ),
        ),
        migrations.AddField(
            model_name="procedurecollective",
            name="impact_assureur",
            field=models.TextField(
                blank=True,
                help_text="Résumé de l’impact et des mesures prises par l’assureur crédit",
                null=True,
                verbose_name="Impact pour l’assureur crédit",
            ),
        ),
        migrations.AddField(
            model_name="procedurecollective",
            name="montant_creance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Montant en FCFA",
                max_digits=15,
                null=True,
                verbose_name="Montant total des créances déclarées",
            ),
        ),
        migrations.AddField(
            model_name="procedurecollective",
            name="numero_dossier",
            field=models.CharField(
                blank=True,
                help_text="Référence officielle du dossier",
                max_length=100,
                null=True,
                verbose_name="Numéro de dossier",
            ),
        ),
        migrations.AddField(
            model_name="procedurecollective",
            name="secteur_activite",
            field=models.CharField(
                blank=True,
                help_text="Secteur d'activité de l'entreprise concernée",
                max_length=255,
                null=True,
                verbose_name="Secteur d'activité",
            ),
        ),
        migrations.AddField(
            model_name="procedurecollective",
            name="tribunal",
            field=models.CharField(
                blank=True,
                help_text="Nom du tribunal compétent",
                max_length=255,
                null=True,
                verbose_name="Tribunal compétent",
            ),
        ),
    ]
