# Config Nginx INITIALE — HTTP only (avant l'obtention du certificat SSL)
# Utiliser ce fichier pour le premier lancement, PUIS passer à bucrep.conf
# après avoir obtenu les certificats Let's Encrypt.

upstream django {
    server web:8000;
}

server {
    listen 80;
    server_name bucrep.net www.bucrep.net;
    client_max_body_size 20M;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/main/media/;
    }

    location / {
        proxy_pass         http://django;
        proxy_set_header   Host              bucrep.net;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name application.bucrep.net;
    client_max_body_size 20M;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/main/media/;
    }

    location / {
        proxy_pass         http://django;
        proxy_set_header   Host              application.bucrep.net;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}
