"""
Importe CategoryNafCode et SubCategoryNafCode depuis Documents/NACE_NAF ENTREPRISE FRANCAIS (1).docx

Usage :
    python manage.py import_naf_from_doc
    python manage.py import_naf_from_doc --dry-run      # aperçu sans sauvegarder
    python manage.py import_naf_from_doc --clear        # vide les tables avant import

Structure :
    CategoryNafCode  → Sections NAF (A, B, C, … Q)
    SubCategoryNafCode → Tous les codes du document (ex. "01.1A", "21.2G", …)
"""

from django.core.management.base import BaseCommand
from django.db import transaction

# ──────────────────────────────────────────────────────────────────────────────
# Catégories NAF (sections A–Q) avec libellés propres
# ──────────────────────────────────────────────────────────────────────────────
NAF_CATEGORIES = [
    ("A", "Agriculture, chasse, sylviculture",                                             0.5),
    ("B", "Pêche, aquaculture, services annexes",                                          0.5),
    ("C", "Industries extractives",                                                        1.0),
    ("D", "Industrie manufacturière",                                                      1.0),
    ("E", "Production et distribution d'électricité, de gaz et d'eau",                    1.0),
    ("F", "Construction",                                                                  0.1),
    ("G", "Commerce ; réparations automobile et d'articles domestiques",                   0.2),
    ("H", "Hôtels et restaurants",                                                         0.1),
    ("I", "Transports et communications",                                                  0.2),
    ("J", "Activités financières",                                                         1.0),
    ("K", "Immobilier, locations et services aux entreprises",                             0.5),
    ("L", "Administration publique",                                                       0.0),
    ("M", "Éducation",                                                                     0.0),
    ("N", "Santé et action sociale",                                                       0.0),
    ("O", "Services collectifs, sociaux et personnels",                                    0.1),
    ("P", "Activités des ménages en tant qu'employeurs",                                   0.0),
    ("Q", "Activités extra-territoriales",                                                 0.0),
]

# ──────────────────────────────────────────────────────────────────────────────
# Codes NAF complets extraits du document
# Format : (section, code, libelle)
# ──────────────────────────────────────────────────────────────────────────────
NAF_CODES = [
    # ── A — Agriculture, chasse, sylviculture ─────────────────────────────────
    ("A","01","Agriculture, chasse, services annexes"),
    ("A","01.1","Culture"),
    ("A","01.1A","Culture de céréales ; cultures industrielles"),
    ("A","01.1C","Culture de légumes ; horticulture ; pépinières"),
    ("A","01.1D","Horticulture ; pépinières"),
    ("A","01.1F","Culture fruitière"),
    ("A","01.1G","Viticulture"),
    ("A","01.2","Élevage"),
    ("A","01.2A","Élevage de bovins"),
    ("A","01.2C","Élevage d'ovins, caprins et équidés"),
    ("A","01.2E","Élevage de porcins"),
    ("A","01.2G","Élevage de volailles"),
    ("A","01.2J","Élevage d'autres animaux"),
    ("A","01.3","Culture et élevage associés"),
    ("A","01.3Z","Culture et élevage associés"),
    ("A","01.4","Services annexes à l'agriculture et aménagement des paysages"),
    ("A","01.4A","Services annexes à l'agriculture"),
    ("A","01.4B","Aménagement des paysages"),
    ("A","01.5","Chasse"),
    ("A","01.5Z","Chasse"),
    ("A","02","Sylviculture, exploitation forestière, services annexes"),
    ("A","02.0","Sylviculture, exploitation forestière, services annexes"),
    ("A","02.0A","Sylviculture"),
    ("A","02.0C","Exploitation forestière"),
    ("A","02.0E","Services annexes à l'exploitation forestière"),
    # ── B — Pêche, aquaculture ────────────────────────────────────────────────
    ("B","05","Pêche, aquaculture, services annexes"),
    ("B","05.0","Pêche, aquaculture, services annexes"),
    ("B","05.0A","Pêche"),
    ("B","05.0C","Pisciculture, aquaculture"),
    # ── C — Industries extractives ────────────────────────────────────────────
    ("C","10","Extraction de houille, de lignite et de tourbe"),
    ("C","10.1","Extraction et agglomération de la houille"),
    ("C","10.1Z","Extraction et agglomération de la houille"),
    ("C","10.2","Extraction et agglomération du lignite"),
    ("C","10.2Z","Extraction et agglomération du lignite"),
    ("C","10.3","Extraction et agglomération de la tourbe"),
    ("C","10.3Z","Extraction et agglomération de la tourbe"),
    ("C","11","Extraction d'hydrocarbures"),
    ("C","11.1","Extraction de pétrole brut et de gaz naturel"),
    ("C","11.1Z","Extraction de pétrole brut et de gaz naturel"),
    ("C","12","Extraction de minerais d'uranium"),
    ("C","12.0","Extraction de minerais d'uranium"),
    ("C","12.0Z","Extraction de minerais d'uranium"),
    ("C","13","Extraction de minerais métalliques"),
    ("C","13.1","Extraction de minerais de fer"),
    ("C","13.1Z","Extraction de minerais de fer"),
    ("C","13.2","Extraction de minerais métalliques non ferreux"),
    ("C","13.2A","Extraction de minerais d'or et d'argent"),
    ("C","13.2C","Extraction d'autres minerais non ferreux"),
    ("C","14","Autres industries extractives"),
    ("C","14.1","Extraction de pierres"),
    ("C","14.1A","Extraction de pierres ornementales et de construction"),
    ("C","14.1C","Extraction de calcaire industriel, de gypse et de craie"),
    ("C","14.1E","Extraction d'ardoise"),
    ("C","14.2","Extraction de sables et d'argiles"),
    ("C","14.2A","Production de sables et de granulats"),
    ("C","14.2C","Extraction d'argiles et de kaolin"),
    ("C","14.3","Extraction de minéraux pour l'industrie chimique et d'engrais"),
    ("C","14.3Z","Extraction de minéraux pour l'industrie chimique et d'engrais"),
    ("C","14.4","Production de sel"),
    ("C","14.4Z","Production de sel"),
    ("C","14.5","Autres industries extractives"),
    ("C","14.5A","Extraction de pierres et minéraux divers"),
    ("C","14.5C","Services annexes aux industries extractives"),
    # ── D — Industrie manufacturière ──────────────────────────────────────────
    ("D","15","Industries alimentaires"),
    ("D","15.1","Industrie des viandes"),
    ("D","15.1A","Production de viandes de boucherie"),
    ("D","15.1C","Production de viandes de volailles"),
    ("D","15.1E","Préparation de produits à base de viandes"),
    ("D","15.1G","Charcuterie"),
    ("D","15.2","Industrie du poisson"),
    ("D","15.2Z","Industrie du poisson"),
    ("D","15.3","Industrie des fruits et légumes"),
    ("D","15.3A","Transformation et conservation de pommes de terre"),
    ("D","15.3B","Préparation de jus de fruits et légumes"),
    ("D","15.3C","Transformation et conservation de légumes"),
    ("D","15.3D","Transformation et conservation de fruits"),
    ("D","15.4","Industrie des corps gras"),
    ("D","15.4A","Fabrication d'huiles et graisses brutes"),
    ("D","15.4C","Fabrication d'huiles et graisses raffinées"),
    ("D","15.4E","Fabrication de margarine"),
    ("D","15.5","Industrie laitière"),
    ("D","15.5A","Fabrication de lait liquide et de produits frais"),
    ("D","15.5C","Fabrication de beurre"),
    ("D","15.5D","Fabrication de fromages"),
    ("D","15.5F","Fabrication de glaces et sorbets"),
    ("D","15.6","Travail des grains ; fabrication d'amidons et de produits amylacés"),
    ("D","15.6A","Meunerie"),
    ("D","15.6C","Autres activités du travail des grains"),
    ("D","15.6E","Fabrication de produits amylacés"),
    ("D","15.7","Fabrication d'aliments pour animaux"),
    ("D","15.7A","Fabrication d'aliments pour animaux de ferme"),
    ("D","15.7C","Fabrication d'aliments pour animaux de compagnie"),
    ("D","15.8","Autres industries alimentaires"),
    ("D","15.8A","Fabrication industrielle de pain et de pâtisserie fraîche"),
    ("D","15.8B","Cuisson de produits de boulangerie-pâtisserie"),
    ("D","15.8C","Boulangerie et boulangerie-pâtisserie"),
    ("D","15.8D","Pâtisserie"),
    ("D","15.8E","Fabrication de biscottes, biscuits, pâtisseries de conservation"),
    ("D","15.8F","Fabrication de sucre"),
    ("D","15.8G","Chocolaterie, confiserie"),
    ("D","15.8H","Fabrication de pâtes alimentaires"),
    ("D","15.8J","Transformation du thé et du café"),
    ("D","15.8K","Fabrication de condiments et assaisonnements"),
    ("D","15.8L","Fabrication d'aliments diététiques et de régime"),
    ("D","15.8M","Fabrication d'autres produits alimentaires"),
    ("D","15.9","Industrie des boissons"),
    ("D","15.9A","Production d'eaux de vie naturelles"),
    ("D","15.9B","Fabrication de spiritueux"),
    ("D","15.9C","Production de vins d'appellation d'origine contrôlée"),
    ("D","15.9D","Vinification"),
    ("D","15.9E","Cidre et vins de fruits"),
    ("D","15.9F","Autres boissons fermentées"),
    ("D","15.9G","Brasserie"),
    ("D","15.9H","Malterie"),
    ("D","15.9J","Industrie des eaux de table et des boissons rafraîchissantes"),
    ("D","16","Fabrication de produits à base de tabac"),
    ("D","16.0","Fabrication de produits à base de tabac"),
    ("D","16.0Z","Fabrication de produits à base de tabac"),
    ("D","17","Industrie textile"),
    ("D","17.1","Filature de l'industrie cotonnière"),
    ("D","17.1A","Filature de coton et assimilé"),
    ("D","17.1C","Texturation, retordage, moulinage de coton"),
    ("D","17.2","Filature de l'industrie lainière — cycle cardé"),
    ("D","17.2Z","Filature de l'industrie lainière — cycle cardé"),
    ("D","17.3","Filature de l'industrie lainière — cycle peigné"),
    ("D","17.3Z","Filature de l'industrie lainière — cycle peigné"),
    ("D","17.4","Filature de la soie et textiles spéciaux"),
    ("D","17.4A","Moulinage et texturation de la soie et textiles assimilés"),
    ("D","17.4C","Fabrication de fils retors ou câblés"),
    ("D","17.5","Préparation et teinture de fibres ; filature d'autres fibres"),
    ("D","17.5A","Préparation de fibres textiles et filature de lin"),
    ("D","17.5B","Préparation et filature du chanvre et du jute"),
    ("D","17.5C","Préparation et filature d'autres fibres"),
    ("D","17.5D","Fabrication de fils à coudre"),
    ("D","17.5E","Teinture de fibres textiles"),
    ("D","17.6","Tissage de l'industrie cotonnière"),
    ("D","17.6Z","Tissage de l'industrie cotonnière"),
    ("D","17.7","Tissage de l'industrie lainière"),
    ("D","17.7A","Tissage de tissus de laine cardée"),
    ("D","17.7B","Tissage de tissus de laine peignée"),
    ("D","17.8","Tissage de soieries et autres textiles"),
    ("D","17.8A","Tissage de soieries"),
    ("D","17.8B","Tissage d'autres textiles"),
    ("D","17.9","Ennoblissement des textiles"),
    ("D","17.9A","Blanchiment, teinture de fils"),
    ("D","17.9B","Ennoblissement du tissu de coton"),
    ("D","17.9C","Ennoblissement du tissu de laine"),
    ("D","17.9D","Ennoblissement de la soie et d'autres textiles"),
    ("D","17.9E","Fabrication de tulles, dentelles et broderies"),
    ("D","17.9F","Fabrication de rubans, bolduc et similaires"),
    ("D","17.9G","Fabrication de passementerie"),
    ("D","17.9H","Fabrication d'étoffes à mailles"),
    ("D","17.9J","Fabrication de textiles non tissés"),
    ("D","17.9K","Fabrication d'autres textiles"),
    ("D","18","Industrie de l'habillement"),
    ("D","18.1","Fabrication de vêtements en cuir"),
    ("D","18.1Z","Fabrication de vêtements en cuir"),
    ("D","18.2","Fabrication d'autres vêtements"),
    ("D","18.2A","Fabrication de vêtements de travail"),
    ("D","18.2B","Fabrication de vêtements sur mesure"),
    ("D","18.2C","Fabrication de vêtements de dessus pour hommes et garçonnets"),
    ("D","18.2D","Fabrication de vêtements de dessus pour femmes et fillettes"),
    ("D","18.2E","Fabrication de vêtements de sport et de loisir"),
    ("D","18.2F","Fabrication de vêtements pour bébés et de sous-vêtements"),
    ("D","18.2G","Fabrication de vêtements de dessous"),
    ("D","18.2H","Fabrication de corsets, gaines et similaires"),
    ("D","18.2J","Fabrication de vêtements et accessoires divers"),
    ("D","18.3","Apprêt et teinture de fourrures ; fabrication d'articles en fourrure"),
    ("D","18.3Z","Apprêt et teinture de fourrures ; fabrication d'articles en fourrure"),
    ("D","19","Industrie du cuir et de la chaussure"),
    ("D","19.1","Apprêt et tannage des cuirs ; maroquinerie"),
    ("D","19.1A","Apprêt et tannage des cuirs"),
    ("D","19.1B","Fabrication d'articles de voyage et de maroquinerie"),
    ("D","19.2","Fabrication de chaussures"),
    ("D","19.2A","Fabrication de chaussures de ville"),
    ("D","19.2B","Fabrication de chaussures de sport, de travail et de sécurité"),
    ("D","19.2C","Fabrication d'autres chaussures"),
    ("D","19.3","Fabrication d'autres articles en cuir"),
    ("D","19.3Z","Fabrication d'autres articles en cuir"),
    ("D","20","Travail du bois et fabrication d'articles en bois"),
    ("D","20.1","Sciage et rabotage du bois ; imprégnation du bois"),
    ("D","20.1A","Sciage et rabotage du bois"),
    ("D","20.1B","Imprégnation du bois"),
    ("D","20.2","Fabrication de panneaux de bois"),
    ("D","20.2Z","Fabrication de panneaux de bois"),
    ("D","20.3","Fabrication de charpentes et de menuiseries"),
    ("D","20.3A","Fabrication de charpentes"),
    ("D","20.3B","Fabrication de menuiseries"),
    ("D","20.4","Fabrication d'emballages en bois"),
    ("D","20.4Z","Fabrication d'emballages en bois"),
    ("D","20.5","Fabrication d'objets divers en bois ; vannerie"),
    ("D","20.5A","Fabrication d'objets divers en bois"),
    ("D","20.5C","Fabrication d'articles en liège, vannerie et sparterie"),
    ("D","21","Industrie du papier et du carton"),
    ("D","21.1","Fabrication de pâte à papier, de papier et de carton"),
    ("D","21.1A","Fabrication de pâte à papier"),
    ("D","21.1C","Fabrication de papier et de carton"),
    ("D","21.2","Fabrication d'articles en papier ou en carton"),
    ("D","21.2A","Fabrication de carton ondulé et d'emballages en papier ou en carton"),
    ("D","21.2B","Fabrication de cartonnages"),
    ("D","21.2C","Fabrication d'emballages en papier"),
    ("D","21.2E","Fabrication d'articles en papier à usage sanitaire ou domestique"),
    ("D","21.2G","Fabrication d'articles de papeterie"),
    ("D","21.2J","Fabrication de papiers peints"),
    ("D","21.2L","Fabrication d'autres articles en papier ou en carton"),
    ("D","22","Édition, imprimerie, reproduction"),
    ("D","22.1","Édition"),
    ("D","22.1A","Édition de livres"),
    ("D","22.1B","Édition de journaux"),
    ("D","22.1C","Édition de revues et périodiques"),
    ("D","22.1E","Édition d'enregistrements sonores"),
    ("D","22.1G","Autres activités d'édition"),
    ("D","22.2","Imprimerie"),
    ("D","22.2A","Imprimerie de journaux"),
    ("D","22.2C","Autre imprimerie"),
    ("D","22.2E","Reliure"),
    ("D","22.2G","Composition et photogravure"),
    ("D","22.2J","Autres activités graphiques"),
    ("D","22.3","Reproduction d'enregistrements"),
    ("D","22.3A","Reproduction d'enregistrements sonores"),
    ("D","22.3C","Reproduction d'enregistrements vidéo"),
    ("D","22.3E","Reproduction d'enregistrements informatiques"),
    ("D","23","Cokéfaction, raffinage, industries nucléaires"),
    ("D","23.1","Cokéfaction"),
    ("D","23.1Z","Cokéfaction"),
    ("D","23.2","Raffinage de pétrole"),
    ("D","23.2Z","Raffinage de pétrole"),
    ("D","23.3","Élaboration et transformation de matières nucléaires"),
    ("D","23.3Z","Élaboration et transformation de matières nucléaires"),
    ("D","24","Industrie chimique"),
    ("D","24.1","Industrie chimique de base"),
    ("D","24.1A","Fabrication de gaz industriels"),
    ("D","24.1C","Fabrication de colorants et de pigments"),
    ("D","24.1E","Fabrication d'autres produits chimiques inorganiques de base"),
    ("D","24.1G","Fabrication de produits pétrochimiques"),
    ("D","24.1H","Fabrication de produits azotés et d'engrais"),
    ("D","24.1J","Fabrication de matières plastiques de base"),
    ("D","24.1K","Fabrication de caoutchouc synthétique"),
    ("D","24.2","Fabrication de produits agrochimiques"),
    ("D","24.2Z","Fabrication de produits agrochimiques"),
    ("D","24.3","Fabrication de peintures et vernis"),
    ("D","24.3Z","Fabrication de peintures et vernis"),
    ("D","24.4","Industrie pharmaceutique"),
    ("D","24.4A","Fabrication de produits pharmaceutiques de base"),
    ("D","24.4B","Fabrication de médicaments"),
    ("D","24.4C","Fabrication d'autres produits pharmaceutiques"),
    ("D","24.5","Fabrication de savons, détergents et produits d'entretien"),
    ("D","24.5A","Fabrication de savons, détergents et produits d'entretien"),
    ("D","24.5B","Fabrication de parfums et de produits pour la toilette"),
    ("D","24.6","Fabrication d'autres produits chimiques"),
    ("D","24.6A","Fabrication de produits explosifs"),
    ("D","24.6B","Fabrication de colles et gélatines"),
    ("D","24.6C","Fabrication d'huiles essentielles"),
    ("D","24.6D","Fabrication de produits chimiques pour la photographie"),
    ("D","24.6E","Fabrication de supports de données"),
    ("D","24.6F","Fabrication de produits chimiques divers"),
    ("D","24.7","Fabrication de fibres artificielles ou synthétiques"),
    ("D","24.7Z","Fabrication de fibres artificielles ou synthétiques"),
    ("D","25","Fabrication de produits en caoutchouc et en plastique"),
    ("D","25.1","Fabrication de produits en caoutchouc"),
    ("D","25.1A","Fabrication de pneumatiques"),
    ("D","25.1B","Rechapage de pneumatiques"),
    ("D","25.1C","Fabrication d'autres articles en caoutchouc"),
    ("D","25.2","Fabrication de produits en matières plastiques"),
    ("D","25.2A","Fabrication de plaques, feuilles, tubes et profilés en plastique"),
    ("D","25.2B","Fabrication d'emballages en matières plastiques"),
    ("D","25.2C","Fabrication d'éléments en plastique pour la construction"),
    ("D","25.2D","Fabrication de pièces techniques en plastique"),
    ("D","25.2E","Fabrication d'articles de ménage en plastique"),
    ("D","25.2F","Fabrication d'articles divers en plastique"),
    ("D","26","Fabrication d'autres produits minéraux non métalliques"),
    ("D","26.1","Fabrication de verre et d'articles en verre"),
    ("D","26.1A","Fabrication de verre plat"),
    ("D","26.1B","Façonnage et transformation du verre plat"),
    ("D","26.1C","Fabrication de verre creux"),
    ("D","26.1D","Fabrication de fibres de verre"),
    ("D","26.1E","Fabrication et façonnage d'articles techniques en verre"),
    ("D","26.1F","Fabrication de verre pour usage domestique ou de décoration"),
    ("D","26.2","Fabrication de produits céramiques"),
    ("D","26.2A","Fabrication de produits céramiques à usage domestique ou ornemental"),
    ("D","26.2B","Fabrication d'appareils sanitaires en céramique"),
    ("D","26.2C","Fabrication d'isolateurs et pièces isolantes en céramique"),
    ("D","26.2D","Fabrication d'autres produits céramiques à usage technique"),
    ("D","26.2E","Fabrication d'autres produits céramiques"),
    ("D","26.2F","Fabrication de carreaux en céramique"),
    ("D","26.3","Fabrication de carreaux en céramique"),
    ("D","26.3Z","Fabrication de carreaux en céramique"),
    ("D","26.4","Fabrication de briques, tuiles et produits de construction"),
    ("D","26.4Z","Fabrication de briques, tuiles et produits de construction"),
    ("D","26.5","Fabrication de ciment, chaux et plâtre"),
    ("D","26.5A","Fabrication de ciment"),
    ("D","26.5B","Fabrication de chaux"),
    ("D","26.5C","Fabrication de plâtre"),
    ("D","26.6","Fabrication d'ouvrages en béton ou en plâtre"),
    ("D","26.6A","Fabrication d'éléments en béton pour la construction"),
    ("D","26.6B","Fabrication de plâtre et d'ouvrages en plâtre"),
    ("D","26.6C","Fabrication de béton prêt à l'emploi"),
    ("D","26.6D","Fabrication de mortiers et bétons secs"),
    ("D","26.6E","Fabrication d'ouvrages en fibre-ciment"),
    ("D","26.6F","Fabrication d'autres ouvrages en béton ou en plâtre"),
    ("D","26.7","Taille, façonnage et finissage de la pierre ornementale et de construction"),
    ("D","26.7Z","Taille, façonnage et finissage de la pierre"),
    ("D","26.8","Fabrication de produits minéraux divers"),
    ("D","26.8A","Fabrication de produits abrasifs"),
    ("D","26.8C","Fabrication de produits minéraux divers"),
    ("D","27","Métallurgie"),
    ("D","27.1","Sidérurgie"),
    ("D","27.1Z","Sidérurgie"),
    ("D","27.2","Fabrication de tubes"),
    ("D","27.2A","Fabrication de tubes en fonte"),
    ("D","27.2C","Fabrication de tubes en acier"),
    ("D","27.3","Tréfilage, étirage"),
    ("D","27.3A","Étirement à froid"),
    ("D","27.3C","Laminage à froid de feuillards"),
    ("D","27.3E","Production de profilés à froid"),
    ("D","27.3G","Tréfilage à froid"),
    ("D","27.4","Production de métaux non ferreux"),
    ("D","27.4A","Production de métaux précieux"),
    ("D","27.4C","Production d'aluminium"),
    ("D","27.4E","Production de plomb, de zinc ou d'étain"),
    ("D","27.4G","Production de cuivre"),
    ("D","27.4H","Production d'autres métaux non ferreux"),
    ("D","27.5","Fonderie"),
    ("D","27.5A","Fonderie de fonte"),
    ("D","27.5C","Fonderie d'acier"),
    ("D","27.5E","Fonderie de métaux légers"),
    ("D","27.5G","Fonderie d'autres métaux non ferreux"),
    ("D","28","Fabrication de produits métalliques"),
    ("D","28.1","Fabrication d'éléments en métal pour la construction"),
    ("D","28.1A","Fabrication de structures métalliques"),
    ("D","28.1C","Fabrication de portes et fenêtres en métal"),
    ("D","28.2","Fabrication de réservoirs métalliques et de chaudières"),
    ("D","28.2A","Fabrication de réservoirs et citernes métalliques"),
    ("D","28.2C","Fabrication de chaudières pour le chauffage central"),
    ("D","28.3","Fabrication de générateurs de vapeur"),
    ("D","28.3Z","Fabrication de générateurs de vapeur"),
    ("D","28.4","Forge, estampage, matriçage, métallurgie des poudres"),
    ("D","28.4A","Forge, estampage, matriçage ; métallurgie des poudres"),
    ("D","28.4B","Découpage, emboutissage"),
    ("D","28.5","Traitement et revêtement des métaux"),
    ("D","28.5A","Traitement et revêtement des métaux"),
    ("D","28.5C","Décolletage"),
    ("D","28.6","Fabrication de coutellerie, d'outillage et de quincaillerie"),
    ("D","28.6A","Fabrication de coutellerie"),
    ("D","28.6B","Fabrication d'outillage à main"),
    ("D","28.6C","Fabrication de serrurerie et ferronnerie"),
    ("D","28.7","Fabrication d'autres produits métalliques"),
    ("D","28.7A","Fabrication de fûts et emballages métalliques similaires"),
    ("D","28.7B","Fabrication d'emballages légers en métal"),
    ("D","28.7C","Fabrication d'articles en fils métalliques"),
    ("D","28.7D","Visserie et boulonnerie"),
    ("D","28.7E","Fabrication de produits métalliques divers"),
    ("D","29","Fabrication de machines et équipements"),
    ("D","29.1","Fabrication d'équipements mécaniques"),
    ("D","29.1A","Fabrication de moteurs et turbines"),
    ("D","29.1C","Fabrication de pompes et compresseurs"),
    ("D","29.1D","Fabrication de robinets et de vannes"),
    ("D","29.1E","Fabrication d'engrenages et organes mécaniques de transmission"),
    ("D","29.2","Fabrication de machines d'usage général"),
    ("D","29.2A","Fabrication de fours et brûleurs"),
    ("D","29.2B","Fabrication de matériel de levage et de manutention"),
    ("D","29.2C","Fabrication de matériel de bureau"),
    ("D","29.2D","Fabrication d'outils portatifs à moteur incorporé"),
    ("D","29.2E","Fabrication d'équipements aérauliques et frigorifiques industriels"),
    ("D","29.2F","Fabrication d'équipements aérauliques et frigorifiques industriels"),
    ("D","29.2G","Fabrication de machines et équipements divers"),
    ("D","29.3","Fabrication de machines agricoles et forestières"),
    ("D","29.3A","Fabrication de tracteurs agricoles"),
    ("D","29.3B","Fabrication d'autres machines agricoles"),
    ("D","29.4","Fabrication de machines-outils"),
    ("D","29.4A","Fabrication de machines-outils à métaux"),
    ("D","29.4B","Fabrication d'autres machines-outils"),
    ("D","29.5","Fabrication d'autres machines d'usage spécifique"),
    ("D","29.5A","Fabrication de machines pour la métallurgie"),
    ("D","29.5B","Fabrication de machines pour l'extraction ou la construction"),
    ("D","29.5C","Fabrication de machines pour les industries alimentaires"),
    ("D","29.5D","Fabrication de machines pour les industries textiles"),
    ("D","29.5E","Fabrication de machines pour les industries du papier et du carton"),
    ("D","29.5F","Fabrication de machines diverses d'usage spécifique"),
    ("D","29.6","Fabrication d'armes et de munitions"),
    ("D","29.6Z","Fabrication d'armes et de munitions"),
    ("D","29.7","Fabrication d'appareils domestiques"),
    ("D","29.7A","Fabrication d'appareils électroménagers"),
    ("D","29.7C","Fabrication d'appareils ménagers non électriques"),
    ("D","30","Fabrication de machines de bureau et de matériel informatique"),
    ("D","30.0","Fabrication de machines de bureau et de matériel informatique"),
    ("D","30.0Z","Fabrication de machines de bureau et de matériel informatique"),
    ("D","31","Fabrication de machines et appareils électriques"),
    ("D","31.1","Fabrication de moteurs, génératrices et transformateurs électriques"),
    ("D","31.1Z","Fabrication de moteurs, génératrices et transformateurs électriques"),
    ("D","31.2","Fabrication de matériel de distribution et de commande électrique"),
    ("D","31.2Z","Fabrication de matériel de distribution et de commande électrique"),
    ("D","31.3","Fabrication de fils et câbles isolés"),
    ("D","31.3Z","Fabrication de fils et câbles isolés"),
    ("D","31.4","Fabrication d'accumulateurs et de piles électriques"),
    ("D","31.4Z","Fabrication d'accumulateurs et de piles électriques"),
    ("D","31.5","Fabrication de lampes et d'appareils d'éclairage"),
    ("D","31.5Z","Fabrication de lampes et d'appareils d'éclairage"),
    ("D","31.6","Fabrication d'autres matériels électriques"),
    ("D","31.6A","Fabrication de matériels électriques pour moteurs et véhicules"),
    ("D","31.6B","Fabrication d'autres matériels électriques"),
    ("D","32","Fabrication d'équipements de radio, télévision et communication"),
    ("D","32.1","Fabrication de composants électroniques"),
    ("D","32.1A","Fabrication de composants passifs et de condensateurs"),
    ("D","32.1B","Fabrication de résistances"),
    ("D","32.1C","Fabrication de circuits intégrés"),
    ("D","32.1D","Fabrication d'autres composants électroniques"),
    ("D","32.2","Fabrication d'appareils d'émission et de transmission"),
    ("D","32.2Z","Fabrication d'appareils d'émission et de transmission"),
    ("D","32.3","Fabrication d'appareils de réception et de traitement du signal"),
    ("D","32.3Z","Fabrication d'appareils de réception et de traitement du signal"),
    ("D","33","Fabrication d'instruments médicaux, de précision, d'optique"),
    ("D","33.1","Fabrication de matériel médico-chirurgical et d'orthopédie"),
    ("D","33.1A","Fabrication de matériel médico-chirurgical"),
    ("D","33.1B","Fabrication de lunettes"),
    ("D","33.2","Fabrication d'instruments de mesure et de contrôle"),
    ("D","33.2A","Fabrication d'équipements d'aide à la navigation"),
    ("D","33.2B","Fabrication d'instruments de mesure et de contrôle"),
    ("D","33.3","Fabrication d'équipements de contrôle des processus industriels"),
    ("D","33.3Z","Fabrication d'équipements de contrôle des processus industriels"),
    ("D","33.4","Fabrication d'instruments d'optique et de matériel photographique"),
    ("D","33.4Z","Fabrication d'instruments d'optique et de matériel photographique"),
    ("D","33.5","Fabrication de montres et horloges"),
    ("D","33.5Z","Fabrication de montres et horloges"),
    ("D","34","Industrie automobile"),
    ("D","34.1","Construction de véhicules automobiles"),
    ("D","34.1Z","Construction de véhicules automobiles"),
    ("D","34.2","Fabrication de carrosseries, remorques et semi-remorques"),
    ("D","34.2Z","Fabrication de carrosseries, remorques et semi-remorques"),
    ("D","34.3","Fabrication d'équipements automobiles"),
    ("D","34.3Z","Fabrication d'équipements automobiles"),
    ("D","35","Construction navale, aéronautique et ferroviaire"),
    ("D","35.1","Construction et réparation navales"),
    ("D","35.1A","Construction de bâtiments de guerre"),
    ("D","35.1B","Construction de bateaux de plaisance"),
    ("D","35.1C","Construction et réparation d'autres bâtiments"),
    ("D","35.2","Construction de matériel ferroviaire roulant"),
    ("D","35.2Z","Construction de matériel ferroviaire roulant"),
    ("D","35.3","Construction aéronautique et spatiale"),
    ("D","35.3A","Construction de moteurs pour l'aéronautique"),
    ("D","35.3B","Construction de cellules d'aéronefs"),
    ("D","35.3C","Construction d'aéronefs"),
    ("D","35.3D","Fabrication d'équipements pour l'aéronautique et le spatial"),
    ("D","35.4","Fabrication de motocycles et de bicyclettes"),
    ("D","35.4A","Fabrication de motocycles"),
    ("D","35.4B","Fabrication de véhicules pour invalides"),
    ("D","35.4C","Fabrication de bicyclettes et de véhicules pour invalides"),
    ("D","35.5","Fabrication d'autres matériels de transport"),
    ("D","35.5Z","Fabrication d'autres matériels de transport"),
    ("D","36","Fabrication de meubles et industries diverses"),
    ("D","36.1","Fabrication de meubles"),
    ("D","36.1A","Fabrication de sièges"),
    ("D","36.1B","Fabrication de meubles de bureau et de magasin"),
    ("D","36.1C","Fabrication de meubles de cuisine"),
    ("D","36.1D","Fabrication de meubles de chambre"),
    ("D","36.1E","Fabrication d'autres meubles et industries connexes de l'ameublement"),
    ("D","36.2","Fabrication de bijouterie et d'articles similaires"),
    ("D","36.2A","Frappe de monnaie"),
    ("D","36.2B","Bijouterie, joaillerie, orfèvrerie"),
    ("D","36.2C","Bijouterie fantaisie"),
    ("D","36.3","Fabrication d'instruments de musique"),
    ("D","36.3Z","Fabrication d'instruments de musique"),
    ("D","36.4","Fabrication d'articles de sport"),
    ("D","36.4Z","Fabrication d'articles de sport"),
    ("D","36.5","Fabrication de jeux et jouets"),
    ("D","36.5Z","Fabrication de jeux et jouets"),
    ("D","36.6","Industries manufacturières diverses"),
    ("D","36.6A","Fabrication de stylos et crayons"),
    ("D","36.6B","Fabrication de parapluies et de cannes"),
    ("D","36.6C","Fabrication d'articles de brosserie"),
    ("D","36.6D","Fabrication de bougies et articles similaires"),
    ("D","36.6E","Fabrication d'autres produits manufacturés"),
    ("D","37","Récupération"),
    ("D","37.1","Récupération de matières métalliques recyclables"),
    ("D","37.1Z","Récupération de matières métalliques recyclables"),
    ("D","37.2","Récupération de matières non métalliques recyclables"),
    ("D","37.2Z","Récupération de matières non métalliques recyclables"),
    # ── E — Électricité, gaz, eau ─────────────────────────────────────────────
    ("E","40","Production et distribution d'électricité, de gaz et de chaleur"),
    ("E","40.1","Production et distribution d'électricité"),
    ("E","40.1A","Production d'électricité"),
    ("E","40.1C","Transport d'électricité"),
    ("E","40.1E","Distribution et commerce d'électricité"),
    ("E","40.1F","Commerce d'électricité"),
    ("E","40.2","Production et distribution de gaz"),
    ("E","40.2A","Production de gaz"),
    ("E","40.2B","Distribution et commerce de gaz par conduites"),
    ("E","40.3","Production et distribution de chaleur"),
    ("E","40.3Z","Production et distribution de chaleur"),
    ("E","41","Captage, traitement et distribution d'eau"),
    ("E","41.0","Captage, traitement et distribution d'eau"),
    ("E","41.0Z","Captage, traitement et distribution d'eau"),
    # ── F — Construction ──────────────────────────────────────────────────────
    ("F","45","Construction"),
    ("F","45.1","Préparation des sites"),
    ("F","45.1A","Démolition et terrassements"),
    ("F","45.1B","Terrassements en grande masse"),
    ("F","45.1D","Forages et sondages"),
    ("F","45.2","Construction d'ouvrages de bâtiment ou de génie civil"),
    ("F","45.2A","Construction de maisons individuelles"),
    ("F","45.2B","Construction de bâtiments divers"),
    ("F","45.2C","Construction d'ouvrages d'art"),
    ("F","45.2D","Travaux souterrains"),
    ("F","45.2E","Construction de lignes électriques et de communication"),
    ("F","45.2F","Construction de voies ferrées"),
    ("F","45.2G","Construction de routes"),
    ("F","45.2H","Construction de pistes et de terrains de sport"),
    ("F","45.2J","Travaux d'installation"),
    ("F","45.2K","Travaux de construction spécialisés"),
    ("F","45.2L","Autres travaux de construction"),
    ("F","45.2M","Construction de chaufferies"),
    ("F","45.2N","Construction de chaussées et de sols sportifs"),
    ("F","45.3","Travaux d'installation"),
    ("F","45.3A","Travaux d'installation électrique"),
    ("F","45.3B","Travaux d'isolation"),
    ("F","45.3C","Installation d'eau et de gaz"),
    ("F","45.3D","Installation d'équipements thermiques et de climatisation"),
    ("F","45.3E","Installation d'antennes et de matériel de communication"),
    ("F","45.3F","Installation d'autres équipements"),
    ("F","45.4","Travaux de finition"),
    ("F","45.4A","Plâtrerie"),
    ("F","45.4B","Menuiserie et vitrerie"),
    ("F","45.4C","Parqueterie"),
    ("F","45.4D","Revêtements de sols et de murs"),
    ("F","45.4E","Peinture et vitrerie"),
    ("F","45.4F","Travaux de finition"),
    ("F","45.5","Location avec opérateur de matériel de construction"),
    ("F","45.5Z","Location avec opérateur de matériel de construction"),
    # ── G — Commerce ──────────────────────────────────────────────────────────
    ("G","50","Commerce et réparation automobile"),
    ("G","50.1","Commerce de véhicules automobiles"),
    ("G","50.1Z","Commerce de véhicules automobiles"),
    ("G","50.2","Entretien et réparation de véhicules automobiles"),
    ("G","50.2Z","Entretien et réparation de véhicules automobiles"),
    ("G","50.3","Commerce de pièces et équipements automobiles"),
    ("G","50.3A","Commerce en gros de pièces et équipements automobiles"),
    ("G","50.3B","Commerce de détail de pièces et équipements automobiles"),
    ("G","50.4","Commerce et réparation de motocycles"),
    ("G","50.4Z","Commerce et réparation de motocycles"),
    ("G","50.5","Commerce de détail de carburants"),
    ("G","50.5Z","Commerce de détail de carburants"),
    ("G","51","Commerce de gros"),
    ("G","51.1","Intermédiaires du commerce"),
    ("G","51.1A","Intermédiaires en matières premières agricoles, animaux vivants et textiles"),
    ("G","51.1B","Intermédiaires en combustibles, minéraux et produits chimiques"),
    ("G","51.1C","Intermédiaires en bois, matériaux et outillage"),
    ("G","51.1D","Intermédiaires en machines, équipements industriels, et autres"),
    ("G","51.1E","Intermédiaires en ameublement et articles ménagers"),
    ("G","51.1F","Intermédiaires en produits alimentaires, boissons et tabac"),
    ("G","51.1G","Intermédiaires en biens de consommation non alimentaires"),
    ("G","51.1H","Intermédiaires en produits divers"),
    ("G","51.2","Commerce de gros de matières premières agricoles"),
    ("G","51.2A","Commerce de gros de céréales et aliments pour animaux"),
    ("G","51.2B","Commerce de gros de fleurs et plantes"),
    ("G","51.2C","Commerce de gros d'animaux vivants"),
    ("G","51.2D","Commerce de gros de cuirs et peaux"),
    ("G","51.2E","Commerce de gros de tabac non manufacturé"),
    ("G","51.3","Commerce de gros de produits alimentaires, boissons et tabac"),
    ("G","51.3A","Commerce de gros de fruits et légumes"),
    ("G","51.3B","Commerce de gros de viandes"),
    ("G","51.3C","Commerce de gros de produits laitiers"),
    ("G","51.3D","Commerce de gros de boissons"),
    ("G","51.3E","Commerce de gros de tabac"),
    ("G","51.3F","Commerce de gros de sucre, chocolat et confiserie"),
    ("G","51.3G","Commerce de gros de café, thé, cacao et épices"),
    ("G","51.3H","Commerce de gros de poissons et produits de la mer"),
    ("G","51.3J","Commerce de gros alimentaire non spécialisé"),
    ("G","51.3K","Commerce de gros de produits alimentaires divers"),
    ("G","51.4","Commerce de gros de biens de consommation non alimentaires"),
    ("G","51.4A","Commerce de gros de textiles"),
    ("G","51.4B","Commerce de gros d'habillement et de chaussures"),
    ("G","51.4C","Commerce de gros d'appareils électroménagers"),
    ("G","51.4D","Commerce de gros de vaisselle, verrerie et produits d'entretien"),
    ("G","51.4E","Commerce de gros de parfumerie et produits de beauté"),
    ("G","51.4F","Commerce de gros pharmaceutique"),
    ("G","51.4G","Commerce de gros de meubles et articles d'ameublement"),
    ("G","51.4H","Commerce de gros de papeterie et fournitures de bureau"),
    ("G","51.4J","Commerce de gros de livres, revues et journaux"),
    ("G","51.4K","Commerce de gros d'articles de loisirs"),
    ("G","51.4L","Commerce de gros de produits de consommation divers"),
    ("G","51.5","Commerce de gros de produits intermédiaires"),
    ("G","51.5A","Commerce de gros de combustibles"),
    ("G","51.5B","Commerce de gros de minerais et métaux"),
    ("G","51.5C","Commerce de gros de bois et matériaux de construction"),
    ("G","51.5D","Commerce de gros de quincaillerie et fournitures"),
    ("G","51.5E","Commerce de gros de machines"),
    ("G","51.5F","Commerce de gros de fournitures industrielles diverses"),
    ("G","51.6","Commerce de gros de machines, équipements et fournitures"),
    ("G","51.6A","Commerce de gros de matériel agricole"),
    ("G","51.6B","Commerce de gros de machines-outils"),
    ("G","51.6C","Commerce de gros de machines pour l'industrie"),
    ("G","51.6D","Commerce de gros d'équipements de transport"),
    ("G","51.6E","Commerce de gros de machines de bureau et d'informatique"),
    ("G","51.6F","Commerce de gros d'équipements divers"),
    ("G","51.7","Autres commerces de gros"),
    ("G","51.7A","Commerce de gros de déchets et débris"),
    ("G","51.7B","Autres commerces de gros"),
    ("G","52","Commerce de détail"),
    ("G","52.1","Commerce de détail en magasin non spécialisé"),
    ("G","52.1A","Commerce de détail de produits surgelés"),
    ("G","52.1B","Hypermarchés"),
    ("G","52.1C","Supermarchés"),
    ("G","52.1D","Petites surfaces alimentaires"),
    ("G","52.1E","Magasins populaires"),
    ("G","52.1F","Commerce de détail non spécialisé à prédominance alimentaire"),
    ("G","52.1G","Commerce de détail non spécialisé"),
    ("G","52.2","Commerce de détail alimentaire en magasin spécialisé"),
    ("G","52.2A","Commerce de détail de fruits et légumes"),
    ("G","52.2B","Commerce de détail de viandes et produits à base de viande"),
    ("G","52.2C","Commerce de détail de poissons et produits de la mer"),
    ("G","52.2D","Commerce de détail de pain, pâtisserie et confiserie"),
    ("G","52.2E","Commerce de détail de boissons"),
    ("G","52.2F","Commerce de détail de tabac"),
    ("G","52.2G","Commerce de détail de produits alimentaires divers"),
    ("G","52.3","Commerce de détail de produits pharmaceutiques et médicaux"),
    ("G","52.3A","Commerce de détail de produits pharmaceutiques"),
    ("G","52.3B","Commerce de détail d'articles médicaux et orthopédiques"),
    ("G","52.3C","Commerce de détail de parfumerie et de produits de beauté"),
    ("G","52.4","Commerce de détail non alimentaire en magasin spécialisé"),
    ("G","52.4A","Commerce de détail de textiles"),
    ("G","52.4B","Commerce de détail d'habillement"),
    ("G","52.4C","Commerce de détail de la chaussure"),
    ("G","52.4D","Commerce de détail de maroquinerie et d'articles de voyage"),
    ("G","52.4E","Commerce de détail de meubles"),
    ("G","52.4F","Commerce de détail d'équipements du foyer"),
    ("G","52.4G","Commerce de détail d'appareils électroménagers et de radio-télévision"),
    ("G","52.4H","Commerce de détail de quincaillerie et bricolage"),
    ("G","52.4J","Commerce de détail de livres, journaux et papeterie"),
    ("G","52.4K","Commerce de détail de revêtements de sol et murs"),
    ("G","52.4L","Commerce de détail de matériaux de construction"),
    ("G","52.4M","Commerce de détail d'optique et de photographie"),
    ("G","52.4N","Commerce de détail d'horlogerie et de bijouterie"),
    ("G","52.4P","Commerce de détail de jeux et jouets"),
    ("G","52.4Q","Commerce de détail d'articles de sport"),
    ("G","52.4R","Commerce de détail de fleurs et plantes"),
    ("G","52.4S","Commerce de détail d'animaux de compagnie et aliments"),
    ("G","52.4T","Commerce de détail de produits divers"),
    ("G","52.5","Commerce de détail de biens d'occasion"),
    ("G","52.5Z","Commerce de détail de biens d'occasion"),
    ("G","52.6","Commerce de détail hors magasin"),
    ("G","52.6A","Vente par correspondance"),
    ("G","52.6B","Commerce de détail de marché"),
    ("G","52.6C","Vente à domicile"),
    ("G","52.6D","Autres commerces hors magasin"),
    ("G","52.7","Réparation d'articles personnels et domestiques"),
    ("G","52.7A","Réparation de chaussures et d'articles en cuir"),
    ("G","52.7B","Réparation de matériel électronique grand public"),
    ("G","52.7C","Réparation d'appareils électroménagers"),
    ("G","52.7D","Réparation de montres, horloges et bijoux"),
    ("G","52.7E","Réparation d'articles divers"),
    # ── H — Hôtels et restaurants ─────────────────────────────────────────────
    ("H","55","Hôtels et restaurants"),
    ("H","55.1","Hôtels"),
    ("H","55.1A","Hôtels avec restaurant"),
    ("H","55.1C","Hôtels touristiques sans restaurant"),
    ("H","55.1E","Autres hôtels"),
    ("H","55.2","Campings"),
    ("H","55.2A","Auberges de jeunesse et refuges"),
    ("H","55.2B","Campings"),
    ("H","55.2C","Hébergements touristiques divers"),
    ("H","55.3","Restaurants"),
    ("H","55.3A","Restauration de type traditionnel"),
    ("H","55.3B","Restauration de type rapide"),
    ("H","55.4","Débits de boissons"),
    ("H","55.4A","Cafés tabacs"),
    ("H","55.4B","Débits de boissons"),
    ("H","55.5","Cantines et traiteurs"),
    ("H","55.5A","Restauration collective sous contrat"),
    ("H","55.5B","Traiteurs, organisation de réceptions"),
    # ── I — Transports et communications ─────────────────────────────────────
    ("I","60","Transports terrestres"),
    ("I","60.1","Transports ferroviaires"),
    ("I","60.1Z","Transports ferroviaires"),
    ("I","60.2","Transports urbains et routiers"),
    ("I","60.2A","Transports réguliers de voyageurs"),
    ("I","60.2B","Taxis"),
    ("I","60.2C","Transports routiers de voyageurs occasionnels"),
    ("I","60.2D","Téléphériques et remontées mécaniques"),
    ("I","60.2E","Transports routiers de marchandises de proximité"),
    ("I","60.2F","Transports routiers de marchandises interurbains"),
    ("I","60.2G","Déménagement"),
    ("I","60.3","Transports par conduites"),
    ("I","60.3Z","Transports par conduites"),
    ("I","61","Transports par eau"),
    ("I","61.1","Transports maritimes et côtiers"),
    ("I","61.1A","Transports maritimes de passagers"),
    ("I","61.1B","Transports maritimes de fret"),
    ("I","61.2","Transports fluviaux"),
    ("I","61.2A","Transports fluviaux de passagers"),
    ("I","61.2B","Transports fluviaux de fret"),
    ("I","62","Transports aériens"),
    ("I","62.1","Transports aériens réguliers"),
    ("I","62.1Z","Transports aériens réguliers"),
    ("I","62.2","Transports aériens non réguliers"),
    ("I","62.2Z","Transports aériens non réguliers"),
    ("I","62.3","Transports spatiaux"),
    ("I","62.3Z","Transports spatiaux"),
    ("I","63","Services auxiliaires des transports"),
    ("I","63.1","Manutention et entreposage"),
    ("I","63.1A","Manutention portuaire"),
    ("I","63.1B","Manutention non portuaire"),
    ("I","63.1C","Entreposage frigorifique"),
    ("I","63.1D","Entreposage non frigorifique"),
    ("I","63.2","Autres services auxiliaires des transports"),
    ("I","63.2A","Gestion d'infrastructures de transports terrestres"),
    ("I","63.2B","Gestion de ports et voies navigables"),
    ("I","63.2C","Gestion d'aéroports et d'aérodromes"),
    ("I","63.2D","Services auxiliaires des transports terrestres"),
    ("I","63.2E","Services auxiliaires des transports par eau"),
    ("I","63.2F","Services auxiliaires des transports aériens"),
    ("I","63.3","Agences de voyage et tourisme"),
    ("I","63.3Z","Agences de voyage et tourisme"),
    ("I","63.4","Organisation du transport de fret"),
    ("I","63.4A","Messagerie, fret express"),
    ("I","63.4B","Affrètement et organisation des transports"),
    ("I","64","Postes et télécommunications"),
    ("I","64.1","Activités de la poste"),
    ("I","64.1A","Activités de la poste nationale"),
    ("I","64.1B","Autres activités de courrier"),
    ("I","64.2","Télécommunications"),
    ("I","64.2A","Télécommunications filaires"),
    ("I","64.2B","Télécommunications sans fil"),
    ("I","64.2C","Télécommunications par satellite"),
    ("I","64.2D","Autres activités de télécommunications"),
    ("I","64.2E","Activités de transmission"),
    # ── J — Activités financières ─────────────────────────────────────────────
    ("J","65","Intermédiation financière"),
    ("J","65.1","Intermédiation monétaire"),
    ("J","65.1A","Banque centrale"),
    ("J","65.1C","Autres intermédiations monétaires"),
    ("J","65.1D","Banques mutualistes"),
    ("J","65.1E","Caisses d'épargne"),
    ("J","65.2","Autres intermédiations financières"),
    ("J","65.2A","Crédit-bail"),
    ("J","65.2B","Distribution de crédit"),
    ("J","65.2C","Activités de capital-risque"),
    ("J","65.2D","Sociétés financières d'investissement"),
    ("J","65.2E","Organismes de placement en valeurs mobilières"),
    ("J","65.2F","Autres intermédiations financières"),
    ("J","66","Assurance"),
    ("J","66.0","Assurance"),
    ("J","66.0A","Assurance vie"),
    ("J","66.0B","Assurance capitalisation"),
    ("J","66.0C","Assurances dommages"),
    ("J","66.0D","Réassurance"),
    ("J","66.0E","Institutions de retraite et caisses de prévoyance"),
    ("J","67","Auxiliaires financiers et d'assurance"),
    ("J","67.1","Auxiliaires financiers"),
    ("J","67.1A","Administration de marchés financiers"),
    ("J","67.1B","Autres auxiliaires financiers"),
    ("J","67.2","Auxiliaires d'assurance"),
    ("J","67.2Z","Auxiliaires d'assurance"),
    # ── K — Immobilier, locations et services aux entreprises ─────────────────
    ("K","70","Activités immobilières"),
    ("K","70.1","Activités immobilières pour compte propre"),
    ("K","70.1A","Promotion immobilière"),
    ("K","70.1B","Promotion immobilière de bureaux"),
    ("K","70.1C","Promotion immobilière d'infrastructures"),
    ("K","70.2","Location de biens immobiliers"),
    ("K","70.2A","Location de logements"),
    ("K","70.2B","Location de bureaux et locaux"),
    ("K","70.3","Marchands de biens immobiliers"),
    ("K","70.3A","Administration d'immeubles résidentiels"),
    ("K","70.3B","Administration de biens immobiliers non résidentiels"),
    ("K","71","Location sans opérateur"),
    ("K","71.1","Location de véhicules automobiles"),
    ("K","71.1Z","Location de véhicules automobiles"),
    ("K","71.2","Location d'autres matériels de transport"),
    ("K","71.2A","Location de matériels de transports terrestre spéciaux"),
    ("K","71.2B","Location d'autres matériels de transport"),
    ("K","71.3","Location de machines et équipements"),
    ("K","71.3A","Location de machines et équipements agricoles"),
    ("K","71.3B","Location de machines et équipements pour la construction"),
    ("K","71.3C","Location de machines de bureau et de matériel informatique"),
    ("K","71.3D","Location d'autres machines et équipements"),
    ("K","71.4","Location d'articles de loisirs et de sport"),
    ("K","71.4Z","Location d'articles de loisirs et de sport"),
    ("K","72","Activités informatiques"),
    ("K","72.1","Conseil en systèmes informatiques"),
    ("K","72.1Z","Conseil en systèmes informatiques"),
    ("K","72.2","Réalisation de logiciels"),
    ("K","72.2A","Édition de logiciels"),
    ("K","72.2B","Réalisation de logiciels"),
    ("K","72.3","Traitement de données"),
    ("K","72.3Z","Traitement de données"),
    ("K","72.4","Activités de banques de données"),
    ("K","72.4Z","Activités de banques de données"),
    ("K","72.5","Entretien et réparation de machines de bureau et de matériel informatique"),
    ("K","72.5Z","Entretien et réparation de machines de bureau et informatique"),
    ("K","72.6","Autres activités rattachées à l'informatique"),
    ("K","72.6Z","Autres activités rattachées à l'informatique"),
    ("K","73","Recherche et développement"),
    ("K","73.1","Recherche et développement en sciences physiques et naturelles"),
    ("K","73.1Z","Recherche et développement en sciences physiques et naturelles"),
    ("K","73.2","Recherche et développement en sciences humaines et sociales"),
    ("K","73.2Z","Recherche et développement en sciences humaines et sociales"),
    ("K","74","Services fournis principalement aux entreprises"),
    ("K","74.1","Activités juridiques, comptables, de conseil et audit"),
    ("K","74.1A","Activités juridiques"),
    ("K","74.1B","Activités comptables"),
    ("K","74.1C","Activités de conseil pour les affaires et la gestion"),
    ("K","74.1D","Activités des sièges sociaux"),
    ("K","74.1E","Administration d'entreprises"),
    ("K","74.1F","Activités de consultance"),
    ("K","74.1G","Autres activités de conseil"),
    ("K","74.2","Activités d'architecture et d'ingénierie"),
    ("K","74.2A","Activités d'architecture"),
    ("K","74.2B","Métreurs, géomètres"),
    ("K","74.2C","Ingénierie et études techniques"),
    ("K","74.3","Activités de contrôle et analyses techniques"),
    ("K","74.3A","Contrôle technique automobile"),
    ("K","74.3B","Analyse, essais et inspections techniques"),
    ("K","74.4","Publicité"),
    ("K","74.4A","Création et placement de publicité"),
    ("K","74.4B","Régie publicitaire de médias"),
    ("K","74.5","Sélection et fourniture de personnel"),
    ("K","74.5A","Sélection et placement de personnel"),
    ("K","74.5B","Travail temporaire"),
    ("K","74.6","Enquêtes et sécurité"),
    ("K","74.6Z","Enquêtes et sécurité"),
    ("K","74.7","Activités de nettoyage"),
    ("K","74.7A","Nettoyage de locaux"),
    ("K","74.7B","Désinfection, désinsectisation, dératisation"),
    ("K","74.8","Activités diverses de services aux entreprises"),
    ("K","74.8A","Studios et ateliers photographiques avec prise de vues"),
    ("K","74.8B","Façonnage et routage"),
    ("K","74.8C","Secrétariat et traduction"),
    ("K","74.8D","Organisation de foires et salons"),
    ("K","74.8E","Activités de services divers"),
    ("K","74.8F","Activités spécialisées diverses"),
    # ── L — Administration publique ───────────────────────────────────────────
    ("L","75","Administration publique"),
    ("L","75.1","Administration publique générale"),
    ("L","75.1A","Administration publique générale"),
    ("L","75.1C","Tutelle des activités sociales"),
    ("L","75.1E","Tutelle des activités économiques"),
    ("L","75.1G","Affaires étrangères"),
    ("L","75.2","Services de la société"),
    ("L","75.2A","Administration publique (tutelle) de la santé, formation, culture"),
    ("L","75.2B","Défense"),
    ("L","75.2C","Justice"),
    ("L","75.2D","Activités d'ordre public et de sécurité"),
    ("L","75.2E","Services du feu et secours"),
    ("L","75.3","Sécurité sociale obligatoire"),
    ("L","75.3Z","Sécurité sociale obligatoire"),
    # ── M — Éducation ─────────────────────────────────────────────────────────
    ("M","80","Éducation"),
    ("M","80.1","Enseignement primaire"),
    ("M","80.1Z","Enseignement primaire"),
    ("M","80.2","Enseignement secondaire"),
    ("M","80.2A","Enseignement secondaire général"),
    ("M","80.2B","Enseignement secondaire technique ou professionnel"),
    ("M","80.3","Enseignement supérieur"),
    ("M","80.3Z","Enseignement supérieur"),
    ("M","80.4","Formation permanente et autres activités d'enseignement"),
    ("M","80.4A","Formation des adultes et formation continue"),
    ("M","80.4B","Autres enseignements"),
    # ── N — Santé et action sociale ───────────────────────────────────────────
    ("N","85","Santé et action sociale"),
    ("N","85.1","Activités pour la santé humaine"),
    ("N","85.1A","Activités hospitalières"),
    ("N","85.1C","Pratique médicale"),
    ("N","85.1E","Pratique dentaire"),
    ("N","85.1F","Activités des professionnels de la rééducation, appareillage et podologie"),
    ("N","85.1G","Laboratoires d'analyses médicales"),
    ("N","85.1H","Ambulances"),
    ("N","85.1J","Activités de santé humaine non classées ailleurs"),
    ("N","85.2","Activités vétérinaires"),
    ("N","85.2Z","Activités vétérinaires"),
    ("N","85.3","Action sociale"),
    ("N","85.3A","Accueil des enfants handicapés"),
    ("N","85.3B","Accueil des adultes handicapés"),
    ("N","85.3C","Aide par le travail, ateliers protégés"),
    ("N","85.3D","Accueil des personnes âgées"),
    ("N","85.3E","Autres hébergements sociaux"),
    ("N","85.3F","Action sociale sans hébergement"),
    ("N","85.3G","Garderies et crèches"),
    # ── O — Services collectifs, sociaux et personnels ────────────────────────
    ("O","90","Assainissement, voirie et gestion des déchets"),
    ("O","90.0","Assainissement, voirie et gestion des déchets"),
    ("O","90.0A","Collecte et traitement des eaux usées"),
    ("O","90.0B","Collecte et traitement des autres déchets"),
    ("O","90.0C","Décharge"),
    ("O","90.0D","Récupération de déchets triés"),
    ("O","90.0E","Traitement des autres déchets solides"),
    ("O","90.0F","Activités de dépollution"),
    ("O","91","Activités associatives diverses"),
    ("O","91.1","Activités des organisations patronales et consulaires"),
    ("O","91.1A","Activités des organisations patronales et consulaires"),
    ("O","91.1B","Organisations professionnelles"),
    ("O","91.2","Syndicats de salariés"),
    ("O","91.2Z","Syndicats de salariés"),
    ("O","91.3","Autres organisations associatives"),
    ("O","91.3A","Organisations religieuses"),
    ("O","91.3B","Organisations politiques"),
    ("O","91.3C","Organisations associatives"),
    ("O","91.3D","Activités associatives diverses"),
    ("O","92","Activités récréatives, culturelles et sportives"),
    ("O","92.1","Activités cinématographiques et vidéo"),
    ("O","92.1A","Production de films"),
    ("O","92.1B","Distribution de films"),
    ("O","92.1C","Projection de films"),
    ("O","92.2","Activités de radio et de télévision"),
    ("O","92.2A","Activités de radio"),
    ("O","92.2B","Activités de télévision"),
    ("O","92.3","Autres activités du spectacle"),
    ("O","92.3A","Activités de spectacle"),
    ("O","92.3B","Autres activités artistiques et de spectacle"),
    ("O","92.3C","Gestion de salles de spectacles"),
    ("O","92.3D","Manèges, dancings et autres activités récréatives"),
    ("O","92.3E","Activités culturelles diverses"),
    ("O","92.4","Agences de presse"),
    ("O","92.4Z","Agences de presse"),
    ("O","92.5","Gestion de bibliothèques, archives, musées"),
    ("O","92.5A","Gestion des bibliothèques"),
    ("O","92.5B","Gestion du patrimoine culturel"),
    ("O","92.5C","Gestion du patrimoine naturel"),
    ("O","92.6","Activités sportives"),
    ("O","92.6A","Gestion d'installations sportives"),
    ("O","92.6B","Autres activités sportives"),
    ("O","92.7","Activités récréatives diverses"),
    ("O","92.7A","Jeux de hasard et d'argent"),
    ("O","92.7B","Autres activités récréatives"),
    ("O","93","Services personnels"),
    ("O","93.0","Services personnels"),
    ("O","93.0A","Blanchisseries-teintureries"),
    ("O","93.0B","Coiffure"),
    ("O","93.0C","Soins de beauté"),
    ("O","93.0D","Pompes funèbres"),
    ("O","93.0E","Entretien corporel"),
    ("O","93.0F","Activités de services personnels divers"),
    # ── P — Activités des ménages ─────────────────────────────────────────────
    ("P","95","Activités des ménages en tant qu'employeurs de personnel domestique"),
    ("P","95.0","Activités des ménages en tant qu'employeurs de personnel domestique"),
    ("P","95.0Z","Activités des ménages en tant qu'employeurs de personnel domestique"),
    ("P","96","Activités indifférenciées des ménages en tant que producteurs de biens"),
    ("P","96.0","Activités indifférenciées des ménages"),
    ("P","96.0Z","Activités indifférenciées des ménages"),
    # ── Q — Activités extra-territoriales ─────────────────────────────────────
    ("Q","99","Activités extra-territoriales"),
    ("Q","99.0","Activités extra-territoriales"),
    ("Q","99.0Z","Activités extra-territoriales"),
]


class Command(BaseCommand):
    help = "Importe CategoryNafCode et SubCategoryNafCode depuis les données du document officiel"

    def add_arguments(self, parser):
        parser.add_argument("--dry-run", action="store_true",
                            help="Affiche ce qui serait importé sans rien sauvegarder.")
        parser.add_argument("--clear", action="store_true",
                            help="Vide CategoryNafCode et SubCategoryNafCode avant l'import.")

    def handle(self, *args, **options):
        from main.models import CategoryNafCode, SubCategoryNafCode

        dry_run = options["dry_run"]
        clear   = options["clear"]

        self.stdout.write(f"Catégories NAF à importer : {len(NAF_CATEGORIES)}")
        self.stdout.write(f"Codes NAF à importer      : {len(NAF_CODES)}")

        if dry_run:
            self._preview()
            return

        with transaction.atomic():
            if clear:
                sub_n = SubCategoryNafCode.objects.count()
                cat_n = CategoryNafCode.objects.count()
                SubCategoryNafCode.objects.all().delete()
                CategoryNafCode.objects.all().delete()
                self.stdout.write(self.style.WARNING(
                    f"Tables vidées : {cat_n} catégorie(s), {sub_n} sous-catégorie(s)."
                ))

            # ── Étape 1 : Catégories ───────────────────────────────────────
            cat_cache: dict[str, CategoryNafCode] = {}
            cat_created = cat_skipped = 0

            for code, libelle, poids in NAF_CATEGORIES:
                cat, created = CategoryNafCode.objects.update_or_create(
                    code=code,
                    defaults={"libelle": libelle, "active": True, "poids": poids},
                )
                cat_cache[code] = cat
                if created:
                    cat_created += 1
                else:
                    cat_skipped += 1

            self.stdout.write(
                f"Catégories : {cat_created} créée(s), {cat_skipped} mise(s) à jour."
            )

            # ── Étape 2 : Codes (sous-catégories) ─────────────────────────
            sub_created = sub_skipped = sub_error = 0
            total = len(NAF_CODES)

            for i, (section, code, libelle) in enumerate(NAF_CODES, 1):
                cat = cat_cache.get(section)
                if not cat:
                    sub_error += 1
                    self.stdout.write(self.style.ERROR(
                        f"  Catégorie '{section}' introuvable pour code '{code}'"
                    ))
                    continue

                poids = cat.poids

                sub, created = SubCategoryNafCode.objects.update_or_create(
                    code=code,
                    defaults={
                        "category": cat,
                        "libelle": libelle,
                        "active": True,
                        "poids": poids,
                    },
                )
                if created:
                    sub_created += 1
                else:
                    sub_skipped += 1

                # Affichage de progression tous les 100
                if i % 100 == 0:
                    self.stdout.write(f"  {i}/{total} traités…")

            self.stdout.write(
                f"Codes NAF : {sub_created} créé(s), {sub_skipped} mis à jour, "
                f"{sub_error} erreur(s)."
            )

        self.stdout.write(self.style.SUCCESS("Import NAF terminé avec succès."))

    def _preview(self):
        from collections import defaultdict
        grouped: dict[str, list] = defaultdict(list)
        for section, code, libelle in NAF_CODES:
            grouped[section].append((code, libelle))

        self.stdout.write("\n--- PREVIEW (dry-run) ---")
        for section, libelle_cat, _ in NAF_CATEGORIES:
            codes = grouped.get(section, [])
            self.stdout.write(f"\n[CAT] {section} — {libelle_cat} ({len(codes)} codes)")
            for code, lib in codes[:5]:
                self.stdout.write(f"  [SUB] {code:12} {lib[:60]}")
            if len(codes) > 5:
                self.stdout.write(f"  ... +{len(codes)-5} autres")
        self.stdout.write(
            f"\nTotal : {len(NAF_CATEGORIES)} catégories, {len(NAF_CODES)} codes."
        )
