name: Deploy Bucrep App

on:
  push:
    branches:
      # Branche sur laquelle on veut executer le deploiement
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    # Precise et confirme l'utilisation de ubuntu derniere version (latest)
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - name: Checkout Code
      # Consulter documentation de l'action : checkout@v3
      uses: actions/checkout@v3

    - name: Utilisation python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installation dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  #  - name: Run test
  #    run: python manage.py test

   # - name: Run SonarQube Scan
    #  uses: SonarSource/sonarqube-scan-action@master
   #   with:
  #      projectBaseDir: .
  #    env:
  #      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}








  build:
    # Precise et confirme l'utilisation de ubuntu derniere version (latest)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      # Consulter documentation de l'action : checkout@v3
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
    # Consulter documentation de l'action docker : setup-buildx-action@v3
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
    # Consulter documentation de l'action docker : login-action@v2
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/bucrep:latest .

    - name: Scan Docker Image with Docker Scout
      uses: docker/scout-action@v1
      with:
        image: ${{ secrets.DOCKER_USERNAME }}/bucrep:latest
        dockerhub-user: ${{ secrets.DOCKER_USERNAME }}
        dockerhub-password: ${{ secrets.DOCKER_PASSWORD }}
        command: cves


    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/bucrep:latest




    # - name: Deploy to VPS via SSH
    # Consulter documentation de l'action docker : login-action@v2
    #   uses: appleboy/ssh-action@v1.0.0
    #   with:
    #     host: ${{ secrets.VPS_HOST }}
    #     username: ${{ secrets.VPS_USER }}
    #    key: ${{ secrets.VPS_SSH_KEY }}
    #    script: |
    #      bash /home/${{ secrets.VPS_USER }}/deploy_latest.sh

  deploy:
    if: github.ref == 'refs/heads/main'
    # Precise et confirme l'utilisation de ubuntu derniere version (latest)
    runs-on: ubuntu-latest

    steps:
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/bucrep:latest
